window.diabetesRecipes = [
  {
    slug: "cucumber-tomato-salad",
    title: "Cucumber Tomato Salad",
    category: "Fresh sides",
    date: "2024-12-27",
    image: "assets/recipe-covers/cucumber-tomato-salad.webp",
    originalCard: "assets/recipe-cards/cucumber-tomato-card.png",
    excerpt: "A refreshing, nutrient-packed cucumber and tomato salad with herbs and a light vinaigrette.",
    tags: ["Side", "Low Carb", "Quick"],
    prepTime: "15 min",
    cookTime: "0 min",
    servings: "4 portions",
    diabetesNote: "Fresh vegetables add crunch, volume, and hydration without a large glucose load.",
    carbAwareness: "Pair with protein and a planned carbohydrate portion for a complete meal.",
    ingredients: ["10 oz cherry tomatoes, halved", "1 English cucumber", "1/2 small red onion, thinly sliced", "2 tbsp oil", "2 tbsp red wine vinegar or white wine vinegar", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "1 tbsp chopped fresh or dried parsley", "1 tsp honey, optional"],
    instructions: ["Trim the cucumber ends, halve lengthwise, then slice into 1/4-inch half rounds.", "Place cucumber, tomatoes, and sliced red onion in a medium bowl.", "Whisk oil, vinegar, honey, salt, and pepper.", "Pour dressing over the salad and toss gently.", "Stir in herbs if using. Serve immediately or chill for one to two hours."],
    nutrition: ["Calories not listed", "Rich in vitamins A and C", "Hydrating vegetables"]
  },
  {
    slug: "cottage-cheese-blueberries-hemp-seeds",
    title: "Cottage Cheese with Blueberries and Hemp Seeds",
    category: "High-protein snack",
    date: "2024-12-29",
    image: "assets/recipe-covers/cottage-cheese-blueberries.webp",
    originalCard: "assets/recipe-cards/cottage-cheese-blueberries-card.png",
    excerpt: "A high-protein, nutrient-dense snack with berries, antioxidants, and healthy fats.",
    tags: ["Breakfast", "High Protein", "Quick"],
    prepTime: "5 min",
    cookTime: "0 min",
    servings: "2",
    diabetesNote: "Protein from cottage cheese and fiber from berries can support steadier morning energy.",
    carbAwareness: "Keep fruit portions intentional and pair with protein or fat.",
    ingredients: ["2 cup cottage cheese, whole-milk", "1/2 cup blueberries", "1/4 cup hemp seeds"],
    instructions: ["Add cottage cheese to serving cups.", "Top with blueberries and hemp seeds.", "Optional toppings include raspberries, strawberries, walnuts, almonds, ground flax, and pumpkin seeds."],
    nutrition: ["Nutrition not listed on original card", "High-protein", "Contains dairy and hemp seeds"]
  },
  {
    slug: "bolognese-spaghetti-squash",
    title: "Bolognese with Spaghetti Squash",
    category: "Balanced dinner",
    date: "2025-01-06",
    image: "assets/recipe-covers/bolognese-spaghetti-squash.webp",
    originalCard: "assets/recipe-cards/bolognese-spaghetti-squash-card.png",
    excerpt: "A low-carb, fiber-rich twist on classic Italian bolognese using spaghetti squash.",
    tags: ["Dinner", "Lower Carb", "Comfort"],
    prepTime: "30 min",
    cookTime: "15 min",
    servings: "4",
    diabetesNote: "Spaghetti squash can lower refined carbohydrate load while keeping a familiar meal format.",
    carbAwareness: "Add a measured whole-grain side if your meal plan needs more carbohydrates.",
    ingredients: ["2 lb spaghetti squash", "4 scallions, chopped", "3 cloves garlic, minced or pressed", "1 lb ground beef", "3 oz pancetta", "1 tsp dried oregano", "1 cup canned chopped tomatoes", "1 cup full-fat mozzarella cheese, crumbled", "Salt, to taste", "Black pepper, to taste"],
    instructions: ["Preheat oven to 400 F. Pierce spaghetti squash and roast 30-40 minutes until tender.", "Cut squash in half, remove seeds, and pull flesh apart into spaghetti-like strands.", "Saute pancetta and beef until cooked through, then remove and set aside.", "Saute scallions, garlic, and oregano until fragrant.", "Add beef mixture and chopped tomatoes; simmer for 15 minutes.", "Season with salt and pepper.", "Plate spaghetti squash and top with sauce, cheese, and fresh herbs if desired."],
    nutrition: ["697 calories", "10g carbohydrates", "55g total fat", "2g fiber", "38g protein"]
  },
  {
    slug: "chocolate-fudge-shake",
    title: "Chocolate Fudge Shake",
    category: "High-protein idea",
    date: "2025-01-12",
    image: "assets/recipe-covers/chocolate-fudge-shake.webp",
    originalCard: "assets/recipe-cards/chocolate-fudge-shake-card.png",
    excerpt: "A creamy chocolate shake made with coconut milk, cocoa, frozen zucchini, dates, almond butter, and collagen powder.",
    tags: ["Snack", "High Protein", "Dessert"],
    prepTime: "4 hr",
    cookTime: "3 min",
    servings: "2",
    diabetesNote: "Dessert-style foods can fit better when protein, fiber, and portion size are considered.",
    carbAwareness: "Dates count as carbohydrate; check sweetener and fruit amounts against your meal plan.",
    ingredients: ["1 cup canned coconut milk", "1 cup zucchini, chopped and frozen", "1/4 cup unsweetened cocoa powder", "2 medjool dates, pitted and chopped", "2 tbsp almond butter", "Pinch of salt", "1/2 cup water, or more as needed", "3 scoops unflavored and unsweetened collagen powder"],
    instructions: ["Chop and freeze zucchini.", "Add all ingredients to a blender and process until smooth and creamy.", "Add more water as needed to process."],
    nutrition: ["475 calories", "32g carbohydrates", "35g total fat", "6g fiber", "22g protein"]
  },
  {
    slug: "high-protein-rosemary-focaccia",
    title: "High-Protein Rosemary Focaccia",
    category: "Meal prep",
    date: "2025-01-06",
    image: "assets/recipe-covers/rosemary-focaccia.webp",
    originalCard: "assets/recipe-cards/rosemary-focaccia-card.png",
    excerpt: "A savory low-carb bread made with mozzarella, cream cheese, almond flour, eggs, and rosemary.",
    tags: ["High Protein", "Side", "Meal Prep"],
    prepTime: "10 min",
    cookTime: "20 min",
    servings: "10",
    diabetesNote: "Higher-protein baked options may fit better than refined bread when portions are planned.",
    carbAwareness: "Bread-style foods still count as carbohydrate; pair with protein and vegetables.",
    ingredients: ["3 cup full-fat shredded mozzarella cheese", "5 oz cream cheese", "2 cup almond flour", "1 tbsp baking powder", "1 tsp garlic powder", "3 eggs", "2 tsp dried rosemary", "1 tsp salt"],
    instructions: ["Preheat oven to 425 F and line a baking sheet with parchment paper.", "Microwave mozzarella and cream cheese for 90 seconds, stir, then microwave again if needed until melted.", "Whisk almond flour, baking powder, and garlic powder until no lumps appear.", "Add eggs and melted cheese mixture; process into a dough ball.", "Press dough into a flat rectangle about 1/4 inch thick.", "Drizzle with olive oil and sprinkle with rosemary and salt.", "Bake 10-12 minutes, checking frequently, until edges brown.", "Cool briefly before cutting. Reheat in toaster oven if desired."],
    nutrition: ["297 calories", "7g carbohydrates", "25g total fat", "3g fiber", "15g protein"]
  },
  {
    slug: "chicken-salad-collard-wraps",
    title: "Chicken Salad Collard Wraps",
    category: "Low-carb lunch",
    date: "2025-01-06",
    image: "assets/recipe-covers/chicken-salad-collard-wraps.webp",
    originalCard: "assets/recipe-cards/chicken-salad-collard-wraps-card.png",
    excerpt: "A low-carb wrap with chicken salad, avocado, herbs, walnuts, and collard leaves.",
    tags: ["Lunch", "Low Carb", "High Protein"],
    prepTime: "15 min",
    cookTime: "5 min",
    servings: "2",
    diabetesNote: "Leafy wraps can lower refined carbohydrate load while keeping lunch filling.",
    carbAwareness: "Add fruit or whole grains on the side if your meal plan calls for more carbohydrates.",
    ingredients: ["4 collard leaves, trimmed", "2 cups chicken breast, pre-cooked", "1/4 cup unsweetened mayonnaise", "2 scallions, chopped", "2 tbsp parsley, chopped", "1/3 cup raw walnuts, chopped", "Salt, to taste", "Black pepper, to taste", "1/2 avocado, sliced"],
    instructions: ["Shred cooked chicken into a large bowl.", "Remove collard stems, shave thick spines, and blanch briefly in hot water to soften.", "Chop scallions, parsley, and walnuts; slice avocado.", "Mix chicken with mayonnaise, scallions, parsley, walnuts, salt, and pepper.", "Place collard leaf stem-side up, add chicken mixture and avocado, then roll into a wrap.", "Repeat with remaining collard leaves."],
    nutrition: ["638 calories", "9g carbohydrates", "52g total fat", "5g fiber", "40g protein"]
  },
  {
    slug: "chicken-sausage-kale-skillet",
    title: "Chicken Sausage Kale Skillet",
    category: "Quick skillet",
    date: "2025-01-06",
    image: "assets/recipe-covers/chicken-sausage-kale-skillet.webp",
    originalCard: "assets/recipe-cards/chicken-sausage-kale-skillet-card.png",
    excerpt: "A nutrient-dense skillet with chicken sausage and kale.",
    tags: ["Dinner", "Quick Meals", "High Protein"],
    prepTime: "10 min",
    cookTime: "5 min",
    servings: "2",
    diabetesNote: "A protein-and-vegetable base can anchor a balanced plate.",
    carbAwareness: "Check sausage labels for added sugars and sodium.",
    ingredients: ["12 oz uncured, unsweetened gluten-free sausage", "8 oz kale, spines removed and chopped"],
    instructions: ["Remove spines from kale and chop leaves.", "Slice sausage and preheat a heavy skillet.", "Brown sausage on all sides.", "Stir in kale, remove from heat, and cover to allow kale to wilt."],
    nutrition: ["599 calories", "7g carbohydrates", "53g total fat", "5g fiber", "23g protein"]
  },
  {
    slug: "dijon-salmon-spinach",
    title: "Dijon Salmon with Spinach",
    category: "Heart-healthy dinner",
    date: "2025-01-06",
    image: "assets/recipe-covers/dijon-salmon-spinach.webp",
    originalCard: "assets/recipe-cards/dijon-salmon-spinach-card.png",
    excerpt: "Baked Dijon salmon served over spinach with lemon and herbs.",
    tags: ["Heart Healthy", "Dinner", "Protein"],
    prepTime: "15 min",
    cookTime: "15 min",
    servings: "4",
    diabetesNote: "Omega-3-rich fish and non-starchy vegetables make this a strong glucose-aware dinner.",
    carbAwareness: "Pair with a measured portion of beans, lentils, quinoa, or brown rice if you need more energy.",
    ingredients: ["1 1/2 lb salmon, cut into filets", "2 tbsp Dijon mustard", "2 cloves garlic, crushed", "1 1/2 tbsp olive oil", "1/2 lemon, juiced", "1 tbsp maple syrup", "1/4 cup scallions, chopped", "Parchment paper", "6 cup spinach", "1 lemon, juiced", "2 tbsp olive oil"],
    instructions: ["De-bone salmon filets and preheat oven to 400 F.", "Crush garlic, juice lemon, chop scallions, and line a baking sheet with parchment.", "Arrange filets on baking sheet.", "Mix mustard, garlic, oil, lemon juice, and maple syrup.", "Spoon mixture over filets and bake 12-15 minutes until cooked through.", "Toss spinach with lemon juice, olive oil, and salt.", "Serve salmon over spinach."],
    nutrition: ["388 calories", "8g carbohydrates", "23g total fat", "0g fiber", "35g protein"]
  },
  {
    slug: "low-carb-easy-tiramisu",
    title: "Low-Carb Easy Tiramisu",
    category: "Dessert",
    date: "2025-01-30",
    image: "assets/recipe-covers/low-carb-tiramisu.webp",
    originalCard: "assets/recipe-cards/low-carb-tiramisu-card.png",
    excerpt: "A lighter tiramisu-style dessert with almond crumble, Greek yogurt, mascarpone, coffee, and cocoa.",
    tags: ["Dessert", "Low Carb", "Treat"],
    prepTime: "15 min",
    cookTime: "3 min",
    servings: "6",
    diabetesNote: "Lower-carb desserts can still affect glucose; portion and timing matter.",
    carbAwareness: "Enjoy as part of a planned meal rather than alone on an empty stomach.",
    ingredients: ["1/2 cup almond flour", "1/4 cup plus 1 1/2 tbsp erythritol or other sugar substitute, divided", "1 tsp ground cinnamon", "1/4 tsp salt", "1 tbsp espresso or strong coffee", "2 cup plain nonfat Greek yogurt", "3 tbsp mascarpone cheese", "1 tbsp dark rum", "2 tsp orange zest", "1 tsp vanilla extract", "1 tsp cocoa powder"],
    instructions: ["Toast almond flour in a skillet over medium heat for 3 minutes or until golden.", "Mix toasted almond flour with 1 1/2 tbsp erythritol, cinnamon, salt, and espresso.", "Divide almond mixture among 6 serving glasses.", "Mix yogurt, mascarpone, remaining erythritol, rum, orange zest, and vanilla.", "Spoon cream mixture over almond base and dust with cocoa before serving."],
    nutrition: ["140 calories", "14g carbohydrates", "8g total fat", "1g fiber", "10g protein"]
  },
  {
    slug: "mediterranean-zucchini",
    title: "Mediterranean Zucchini",
    category: "Vegetable side",
    date: "2025-01-13",
    image: "assets/recipe-covers/mediterranean-zucchini.webp",
    originalCard: "assets/recipe-cards/mediterranean-zucchini-card.png",
    excerpt: "Baked zucchini with olive oil, lemon zest, herbs, red pepper flakes, and Parmesan.",
    tags: ["Heart Healthy", "Low Carb", "Side"],
    prepTime: "10 min",
    cookTime: "20 min",
    servings: "4",
    diabetesNote: "Non-starchy vegetables add volume, fiber, and color with fewer carbohydrates.",
    carbAwareness: "Use this to fill half your plate.",
    ingredients: ["2 zucchini, 5-6 oz each, cut in half lengthwise", "2 tsp olive oil", "1/2 tsp lemon zest", "1/2 tsp dried basil", "1/2 tsp dried oregano", "1/8 tsp crushed red pepper flakes", "1/8 tsp salt", "4 tsp grated Parmesan cheese"],
    instructions: ["Preheat oven to 400 F.", "Place zucchini cut side up on a baking sheet and drizzle with oil.", "Mix lemon zest, basil, oregano, red pepper flakes, and salt.", "Sprinkle herb mixture over zucchini.", "Bake 20 minutes or until just tender.", "Sprinkle each half with 1 tsp Parmesan and let stand 5 minutes before serving."],
    nutrition: ["40 calories", "3g carbohydrates", "3g total fat", "1g fiber", "1g protein"]
  },
  {
    slug: "turkey-herb-burger",
    title: "Turkey Herb Burger",
    category: "Protein mains",
    date: "2025-01-06",
    image: "assets/recipe-covers/turkey-herb-burger.webp",
    originalCard: "assets/recipe-cards/turkey-herb-burger-card.png",
    excerpt: "A lean ground turkey burger with fresh basil, mint, chives, and dried sage.",
    tags: ["Lunch", "Dinner", "Protein"],
    prepTime: "10 min",
    cookTime: "5 min",
    servings: "4",
    diabetesNote: "Lean protein can support fullness and make carbohydrate portions easier to plan.",
    carbAwareness: "Choose whole-grain buns or lettuce wraps depending on your glucose goals.",
    ingredients: ["1 1/2 lb lean ground turkey", "1/4 cup fresh basil, finely chopped", "1/4 cup fresh mint, finely chopped", "1/4 cup chives, finely chopped", "1 tsp dried sage"],
    instructions: ["Combine turkey, basil, mint, chives, and sage in a large bowl.", "Add salt and pepper to taste.", "Mix gently and form into 4 patties.", "Preheat grill or griddle pan to medium-high.", "Grill and brown burgers for about 6 minutes on each side or until cooked through."],
    nutrition: ["256 calories", "1g carbohydrates", "1g total fat", "13g fiber", "34g protein"]
  },
  {
    slug: "turkey-meatball-wonton-soup-bok-choy-carrots",
    title: "Turkey Meatball Wonton Soup with Bok Choy & Carrots",
    category: "Soup",
    date: "2025-01-30",
    image: "assets/recipe-covers/turkey-meatball-wonton-soup.webp",
    originalCard: "assets/recipe-cards/turkey-meatball-wonton-soup-card.png",
    excerpt: "A diabetes-friendly Asian-fusion soup with turkey meatballs, bok choy, carrots, ginger, garlic, and cilantro.",
    tags: ["Dinner", "Soup", "High Protein"],
    prepTime: "10 min",
    cookTime: "15 min",
    servings: "6",
    diabetesNote: "Brothy meals with vegetables and protein can be filling without feeling heavy.",
    carbAwareness: "Breadcrumbs count as carbohydrates; portion soup intentionally.",
    ingredients: ["8 cup low sodium chicken broth", "4 tsp toasted sesame oil", "1 1/2 tbsp lower sodium soy sauce", "2 tsp Thai style chili garlic sauce", "1 tsp fish sauce", "4 cloves garlic, minced", "1 tbsp fresh ginger paste", "1 bunch fresh cilantro, minced", "1 bunch green onion, minced", "1 lb lean ground turkey", "1 cup panko bread crumbs", "1 tsp lower sodium soy sauce", "2 eggs", "1/2 tsp Chinese five-spice powder", "8 baby bok choy, roots trimmed and roughly chopped", "1 cup shredded carrots"],
    instructions: ["Heat broth, sesame oil, soy sauce, chili-garlic sauce, and fish sauce in a large pot.", "Add half the garlic, ginger, cilantro, and green onions to the pot.", "Transfer remaining aromatics to a bowl.", "Mix turkey, breadcrumbs, soy sauce, eggs, five-spice, and aromatics by hand.", "Form rounded meatballs and drop into the pot.", "Simmer 5-6 minutes until meatballs are cooked through.", "Add bok choy and carrots and cook 4-5 minutes more."],
    nutrition: ["280 calories", "20g carbohydrates", "11g total fat", "4g fiber", "26g protein"]
  }
];

window.diabetesResearch = [
  {
    slug: "walking-after-meals",
    title: "Walking After Meals and Blood Sugar",
    category: "Physical Activity",
    year: "2022",
    source: "Sports Medicine",
    summary: "Short walks after eating may help reduce post-meal glucose spikes for some people.",
    takeaway: "Movement does not need to be intense to matter. A short walk after meals can be a practical glucose habit.",
    findings: ["Light walking after meals can improve post-meal glucose response.", "Breaking up sitting time may support metabolic health.", "The best routine is one a person can repeat consistently."]
  },
  {
    slug: "high-fiber-foods-a1c",
    title: "High-Fiber Foods and A1C",
    category: "Carbohydrates",
    year: "2021",
    source: "Diabetes Care",
    summary: "Higher-fiber eating patterns are associated with better glycemic outcomes in many studies.",
    takeaway: "Fiber can slow digestion and support fullness. Beans, lentils, vegetables, berries, oats, and seeds are practical places to start.",
    findings: ["Fiber-rich diets may improve A1C modestly.", "Whole-food fiber is preferred over relying only on supplements.", "Increasing fiber gradually can reduce digestive discomfort."]
  },
  {
    slug: "mediterranean-diet-type-2",
    title: "Mediterranean Diet and Type 2 Diabetes",
    category: "Diet Patterns",
    year: "2020",
    source: "BMJ",
    summary: "Mediterranean-style eating is linked with cardiometabolic benefits for people with or at risk for type 2 diabetes.",
    takeaway: "The pattern matters: vegetables, beans, fish, olive oil, nuts, fruit, and minimally processed grains.",
    findings: ["Diet quality can support glucose and heart health.", "Unsaturated fats may be helpful when replacing refined carbohydrates or saturated fats.", "Cultural adaptation matters for long-term adherence."]
  },
  {
    slug: "protein-breakfast-glucose",
    title: "Protein at Breakfast and Post-Meal Glucose",
    category: "Blood Sugar & A1C",
    year: "2019",
    source: "Journal of Nutrition",
    summary: "Adding protein to breakfast may improve fullness and reduce glucose swings compared with refined carbohydrate breakfasts.",
    takeaway: "Breakfast does not need to be carb-free. Pairing carbs with protein and fiber is often more realistic.",
    findings: ["Protein can increase satiety.", "Meal composition affects post-meal glucose.", "Individual responses vary."]
  },
  {
    slug: "sleep-and-glucose",
    title: "Sleep and Glucose Control",
    category: "Sleep",
    year: "2023",
    source: "NIH",
    summary: "Short or disrupted sleep can make glucose regulation harder for some people.",
    takeaway: "Blood sugar care is not only about food. Sleep routines can be part of a diabetes plan.",
    findings: ["Sleep loss may affect insulin sensitivity.", "Consistent sleep timing may support metabolic routines.", "Stress and sleep often interact."]
  },
  {
    slug: "heart-health-diabetes",
    title: "Heart Health Risk in Diabetes",
    category: "Heart Health",
    year: "2024",
    source: "American Diabetes Association",
    summary: "Diabetes care often includes cardiovascular risk reduction, not only glucose management.",
    takeaway: "Heart-healthy eating, blood pressure awareness, movement, and glucose care are connected.",
    findings: ["Cardiovascular prevention is central in diabetes care.", "Food quality and lipid patterns matter.", "Nutrition counseling can support multiple risk factors."]
  }
];
