import { getExpansionContent } from "./siteExpansionContent";

const sources = {
  weight: ["NIDDK: Treatment for Overweight & Obesity", "https://www.niddk.nih.gov/health-information/weight-management/adult-overweight-obesity/treatment"],
  medication: ["NIDDK: Prescription Medications to Treat Overweight & Obesity", "https://www.niddk.nih.gov/health-information/weight-management/prescription-medications-treat-overweight-obesity"],
  pcos: ["Office on Women's Health: Polycystic Ovary Syndrome", "https://womenshealth.gov/a-z-topics/polycystic-ovary-syndrome"],
  thyroid: ["NIDDK: Hypothyroidism", "https://www.niddk.nih.gov/health-information/endocrine-diseases/hypothyroidism"],
  digestive: ["NIDDK: Eating, Diet & Nutrition for IBS", "https://www.niddk.nih.gov/health-information/digestive-diseases/irritable-bowel-syndrome/eating-diet-nutrition"],
  sports: ["NIH Office of Dietary Supplements: Exercise and Athletic Performance", "https://ods.od.nih.gov/factsheets/ExerciseAndAthleticPerformance-Consumer/"],
  menopause: ["Office on Women's Health: Menopause and Your Health", "https://womenshealth.gov/menopause/menopause-and-your-health"],
  heart: ["American Heart Association: Diet and Lifestyle Recommendations", "https://www.heart.org/en/healthy-living/healthy-eating/eat-smart/nutrition-basics/aha-diet-and-lifestyle-recommendations"],
  pregnancy: ["ACOG: Healthy Eating During Pregnancy", "https://www.acog.org/womens-health/faqs/healthy-eating-during-pregnancy"],
  eating: ["NIMH: Eating Disorders - What You Need to Know", "https://www.nimh.nih.gov/health/publications/eating-disorders"],
  celiac: ["NIDDK: Diagnosis of Celiac Disease", "https://www.niddk.nih.gov/health-information/digestive-diseases/celiac-disease/diagnosis"],
  kidney: ["NIDDK: Healthy Eating for Adults with Chronic Kidney Disease", "https://www.niddk.nih.gov/health-information/kidney-disease/chronic-kidney-disease-ckd/healthy-eating-adults-chronic-kidney-disease"],
  cancer: ["National Cancer Institute: Nutrition During Cancer Treatment", "https://www.cancer.gov/about-cancer/treatment/side-effects/nutrition"],
  cholesterol: ["American Heart Association: Understanding Cholesterol and Lipids", "https://www.heart.org/en/health-topics/cholesterol/your-complete-guide-to-understanding-cholesterol-and-lipids"],
  allergies: ["FDA: Food Allergies", "https://www.fda.gov/food/nutrition-food-labeling-and-critical-foods/food-allergies"],
};

const shared = {
  en: {
    eyebrow: "Plain-language nutrition guide",
    overviewLabel: "First, what this means",
    focusLabel: "What we can work on together",
    visitLabel: "What your first visit can look like",
    urgentLabel: "Please contact a medical professional promptly if",
    faqLabel: "A few useful answers",
    sourcesLabel: "Medical sources reviewed for this guide",
    disclaimer: "This page is for general education. It does not diagnose a condition or replace your physician, specialist, therapist, or emergency care.",
    relatedLabel: "You may also want to read",
    bookingTitle: "Want to ask whether this service fits your needs?",
    bookingText: "Use the free 15-minute consultation to describe your situation. We will explain whether the next appointment should be with a dietitian, a physician, or another specialist.",
    bookingButton: "Book a free 15-minute consultation",
  },
  "zh-CN": {
    eyebrow: "把营养和身体讲明白",
    overviewLabel: "先说清楚，这到底是什么",
    focusLabel: "营养师可以和你一起做什么",
    visitLabel: "第一次见面通常会怎么聊",
    urgentLabel: "出现这些情况，请尽快联系医生或急诊",
    faqLabel: "大家经常会问",
    sourcesLabel: "本页参考的医学资料",
    disclaimer: "本页用于一般健康教育，不能代替医生诊断、专科治疗、心理治疗或急诊处理。",
    relatedLabel: "你可能也想了解",
    bookingTitle: "想先确认这项服务是否合适？",
    bookingText: "可以预约一次免费的 15 分钟咨询，说明你的情况。我们会告诉你下一次应该预约营养师、医生，还是其他专科人员。",
    bookingButton: "免费预约 15 分钟咨询",
  },
};

const spanishGuide = {
  eyebrow: "Guía nutricional en lenguaje claro",
  overviewLabel: "Qué significa y qué conviene revisar",
  focusLabel: "En qué puede ayudarle la dietista",
  visitLabel: "Qué ocurre en la primera visita",
  urgentLabel: "Busque atención médica sin demora si presenta",
  faqLabel: "Preguntas frecuentes",
  sourcesLabel: "Fuentes médicas consultadas",
  disclaimer: "Esta página ofrece educación general. No diagnostica una condición ni reemplaza a su médico, especialista, terapeuta o servicio de urgencias.",
  relatedLabel: "También puede consultar",
  bookingTitle: "¿Quiere confirmar si este servicio corresponde a su situación?",
  bookingText: "Reserve una consulta gratuita de 15 minutos y describa lo que necesita. Le explicaremos si la siguiente cita debe ser con una dietista, un médico u otro especialista.",
  bookingButton: "Consulta gratuita de 15 minutos",
  overview: ["La recomendación depende de sus síntomas, diagnóstico, medicamentos, análisis, alimentación y objetivos. Una sola lista de alimentos no sirve para todas las personas.", "La dietista trabaja junto con la atención médica que ya recibe. Las decisiones sobre diagnóstico, medicamentos y tratamiento corresponden a los profesionales autorizados."],
  focus: ["Revisar cómo come ahora y qué se ha vuelto difícil.", "Relacionar comidas, síntomas, medicamentos, horarios y resultados de laboratorio.", "Elegir cambios concretos que pueda aplicar en casa, en el trabajo y al comer fuera.", "Preparar preguntas para su médico cuando algo necesite evaluación clínica."],
  visit: ["Revisamos su historia de salud, medicamentos, suplementos, síntomas y comidas habituales.", "Acordamos una o dos prioridades para comenzar.", "Sale con pasos claros y un plan de seguimiento."],
  urgent: ["Síntomas repentinos o intensos, desmayo, dolor en el pecho, dificultad para respirar o confusión.", "Vómitos persistentes, deshidratación, sangrado o incapacidad para comer y beber.", "Cualquier señal que su equipo médico le haya indicado tratar como una urgencia."],
  faq: [{ q: "¿Recibiré una dieta estándar?", a: "No. Las recomendaciones dependen de su salud, alimentos habituales, cultura, horario, presupuesto y preferencias." }, { q: "¿La dietista puede cambiar mis medicamentos?", a: "No. Puede ayudarle a registrar alimentos y síntomas, pero las recetas y dosis corresponden al profesional que las indicó." }],
};

const en = {
  "weight-loss": {
    title: "Weight loss without a one-size-fits-all diet",
    shortTitle: "Weight Loss",
    intro: "Weight is affected by appetite, sleep, medicines, stress, health conditions, food access, culture, and daily routine. We start with the whole picture, not a list of foods to ban.",
    overview: [
      "A useful weight-care plan should improve health and still be possible on an ordinary week. It may include meal structure, movement, sleep, behavior support, medication, or medical evaluation, depending on your needs.",
      "The scale is only one measure. Energy, strength, blood pressure, lab results, digestion, and your relationship with food may matter just as much. We set goals with you and avoid shame-based coaching.",
    ],
    focus: ["Build meals that are filling enough, with protein, fiber, and foods you actually enjoy.", "Spot the times when hunger, stress, schedule, or medication makes eating harder to manage.", "Choose a few changes that can survive restaurant meals, travel, family food, and busy days.", "Coordinate with your medical team if symptoms, medicines, or lab results may be affecting weight."],
    visit: ["Review your health history, weight history, medicines, sleep, movement, and what eating looks like now.", "Agree on what success means to you, including health goals that are not a number on the scale.", "Leave with two or three practical actions, not a perfect meal plan that falls apart in a week."],
    urgent: ["Weight is changing quickly without trying.", "You are fainting, vomiting repeatedly, unable to eat, or becoming dehydrated.", "Thoughts about food, weight, or exercise are causing severe distress or unsafe behaviors."],
    faq: [{ q: "Do I have to count every calorie?", a: "No. Tracking can help some people, but it is not required. Portion awareness, meal timing, hunger cues, and repeatable meal patterns are other useful tools." }, { q: "How fast should weight change?", a: "There is no safe target that fits everyone. Your health, starting point, medicines, and history matter. We focus on a pace that protects nutrition, muscle, and daily function." }, { q: "Can I still eat cultural or restaurant foods?", a: "Yes. A plan that excludes your real life is unlikely to last. We work with the foods you already eat and decide where changes would help most." }],
    image: "generated/weight-habits-lifestyle.png",
    imageAlt: "Balanced meal and everyday weight-care planning",
    sources: [sources.weight],
    related: ["glp1", "pcos", "thyroid-health"],
  },
  glp1: {
    title: "Eating well while taking a GLP-1 medicine",
    shortTitle: "GLP-1 Support",
    intro: "GLP-1 and related medicines can change hunger, fullness, digestion, and food tolerance. Nutrition support helps you eat enough, protect muscle, and manage common side effects while your prescriber manages the medication.",
    overview: [
      "Medicines such as semaglutide, liraglutide, and tirzepatide are prescribed for specific medical reasons. They are not interchangeable, and the right dose, warnings, and follow-up must come from a qualified prescriber.",
      "Because appetite can become much smaller, simply eating less is not the whole goal. Protein, fluids, fiber, vitamins, and enough overall energy still matter. The plan may need to change during dose increases or when nausea, constipation, or early fullness appears.",
    ],
    focus: ["Use smaller, slower meals and identify portions that feel comfortable.", "Spread protein and fluids through the day instead of trying to catch up at dinner.", "Adjust fiber, fat, meal timing, and food texture when nausea, reflux, diarrhea, or constipation occurs.", "Plan for travel, restaurant meals, dose changes, and what to discuss with your prescriber."],
    visit: ["Review the exact medicine, dose schedule, other medicines, symptoms, and how much you are currently able to eat and drink.", "Check for signs that intake may be too low, including weakness, rapid weight change, dehydration, or difficulty meeting protein needs.", "Create a simple eating and hydration plan, plus a clear list of symptoms to report to the prescribing clinician."],
    urgent: ["Severe or persistent abdominal pain, especially with vomiting.", "Repeated vomiting, very dark urine, dizziness, or being unable to keep fluids down.", "Signs of an allergic reaction, severe weakness, confusion, or symptoms that feel sudden or dangerous."],
    faq: [{ q: "Should I skip meals if I am not hungry?", a: "Regular large meals may feel difficult, but going all day with almost no food can make protein, fluid, and nutrient intake too low. Small meals or snacks may be easier." }, { q: "Do I need protein shakes?", a: "Not automatically. Food can often meet your needs. A shake can be useful when solid food is difficult, but we choose one based on your tolerance, medical history, and total intake." }, { q: "Can a dietitian change my dose?", a: "No. Medication prescribing and dose changes belong to your prescriber. We help you track nutrition and symptoms so that conversation is clearer." }],
    image: "generated/glp1-training.webp",
    imageAlt: "GLP-1 medication and nutrition planning",
    sources: [sources.medication],
    related: ["weight-loss", "digestive-health", "medical-weight-loss"],
  },
  "medical-weight-loss": {
    title: "Medical weight care with nutrition built in",
    shortTitle: "Medical Weight Loss",
    intro: "Medical weight care looks at possible health drivers, treatment options, and nutrition together. Medication may be one tool, but it should not be the only conversation.",
    overview: ["A medical evaluation may review blood pressure, symptoms, sleep, medicines, weight history, family history, and relevant lab results. The goal is to understand risk and choose care that fits the person, not to prescribe automatically.", "When medication is appropriate, nutrition follow-up can help protect muscle, maintain hydration, manage side effects, and build habits that remain useful if treatment changes."],
    focus: ["Prepare a clear food, symptom, and weight history for the medical visit.", "Build meals around health needs such as blood pressure, cholesterol, digestion, or PCOS.", "Monitor appetite, food tolerance, hydration, strength, and realistic progress.", "Coordinate questions for the physician and decide what needs medical follow-up."],
    visit: ["Start with a dietitian assessment and clarify your main health priorities.", "Arrange physician evaluation when clinical review or prescribing may be useful.", "Follow up with practical nutrition changes and coordinated symptom monitoring."],
    urgent: ["New chest pain, trouble breathing, fainting, or one-sided weakness.", "Rapid unexplained weight change, severe swelling, or inability to eat and drink.", "A serious reaction or severe symptoms after starting or changing a medicine."],
    faq: [{ q: "Does medical weight care always mean medication?", a: "No. The medical visit helps determine whether medicine is appropriate. Nutrition, sleep, movement, and treatment of related conditions may be the main plan." }, { q: "Will I still see a dietitian?", a: "Yes. The dietitian focuses on the day-to-day eating, symptoms, and habits that medication alone does not solve." }],
    image: "generated/weight-management-care.png",
    imageAlt: "Coordinated medical and nutrition weight care",
    sources: [sources.weight, sources.medication],
    related: ["weight-loss", "glp1", "heart-health"],
  },
  pcos: {
    title: "PCOS nutrition without blaming your body",
    shortTitle: "PCOS",
    intro: "Polycystic ovary syndrome can affect periods, ovulation, skin, hair, insulin response, and long-term health. It is a hormone-related condition, not something you caused by eating the wrong food.",
    overview: ["PCOS looks different from person to person. Some people have irregular periods, acne, excess hair growth, difficulty conceiving, or changes in weight; others have only a few signs. Diagnosis and medication decisions belong to your medical clinician.", "There is no single 'PCOS diet.' Regular meals, adequate protein and fiber, enjoyable movement, sleep support, and attention to cholesterol or blood sugar can help, but the plan should match your symptoms and goals."],
    focus: ["Create a meal rhythm that reduces long gaps, strong cravings, and energy crashes.", "Add fiber, protein, and satisfying fats without removing all carbohydrates.", "Support fertility, sports, digestive, or weight goals without piling on conflicting rules.", "Coordinate nutrition with medications, lab results, and plans for pregnancy."],
    visit: ["Review symptoms, menstrual history, labs, medicines, supplements, and what you have already tried.", "Choose the one or two problems that matter most now, such as energy, meal regularity, cholesterol, or food stress.", "Build a flexible plan and decide what should be discussed with your gynecologist or primary-care clinician."],
    urgent: ["Very heavy bleeding, severe pelvic pain, fainting, or possible pregnancy with concerning symptoms.", "New severe depression, self-harm thoughts, or eating behaviors that feel unsafe.", "Symptoms suggesting very high blood sugar, such as marked thirst, frequent urination, vomiting, or confusion."],
    faq: [{ q: "Do I have to stop eating carbohydrates?", a: "No. Carbohydrates can remain part of a balanced PCOS plan. Type, portion, meal balance, and what is practical for you matter more than banning an entire food group." }, { q: "Will losing weight cure PCOS?", a: "PCOS is not defined by body size and weight loss is not a cure. Some people choose weight goals, while others focus on symptoms, labs, fertility, strength, or eating regularity." }],
    image: "meal-planning.webp",
    imageAlt: "PCOS nutrition discussion and meal planning",
    sources: [sources.pcos],
    related: ["weight-loss", "pregnancy-postpartum", "heart-health"],
  },
  "thyroid-health": {
    title: "Thyroid nutrition: what food can and cannot do",
    shortTitle: "Thyroid Health",
    intro: "An underactive thyroid can affect energy, temperature tolerance, periods, cholesterol, and weight. These symptoms overlap with many other conditions, so blood testing and medical diagnosis matter.",
    overview: ["Hypothyroidism is usually treated with thyroid hormone medicine. Food cannot replace that medicine, and taking extra iodine does not automatically help. Large amounts of iodine from kelp or supplements may make some thyroid conditions worse.", "Nutrition support is most useful for building adequate meals, managing cholesterol or constipation, reviewing supplements, and arranging food or mineral timing around thyroid medicine when your clinician advises it."],
    focus: ["Check whether long gaps, very low intake, or low fiber are worsening fatigue or constipation.", "Review iodine, biotin, calcium, iron, and herbal supplements before assuming they are safe for the thyroid.", "Build a heart-supportive pattern if cholesterol is elevated.", "Prepare questions about medicine timing and repeat blood tests for your prescribing clinician."],
    visit: ["Review diagnosis, lab history, medicine schedule, symptoms, supplements, and usual meals.", "Separate what may respond to nutrition from what needs thyroid medication or further testing.", "Choose simple changes for bowel regularity, energy, or cholesterol while medical follow-up continues."],
    urgent: ["Severe drowsiness, confusion, trouble breathing, very low body temperature, or a major slowing of body functions.", "Pregnancy or a new positive pregnancy test while being treated for thyroid disease; contact your clinician promptly.", "A racing or irregular heartbeat, severe weakness, or new symptoms after changing thyroid medicine."],
    faq: [{ q: "Should I take iodine or kelp?", a: "Do not start high-dose iodine or kelp on your own. Too much iodine can worsen some autoimmune thyroid conditions. Ask your clinician to review the exact product." }, { q: "Can thyroid medicine interact with food?", a: "Absorption can be affected by timing and by some supplements, including calcium and iron. Follow your prescription instructions and ask your clinician or pharmacist about spacing." }],
    image: "heart-health.webp",
    imageAlt: "Everyday food planning for thyroid health",
    sources: [sources.thyroid],
    related: ["weight-loss", "high-cholesterol", "pregnancy-postpartum"],
  },
  "digestive-health": {
    title: "Digestive nutrition without cutting out everything",
    shortTitle: "Digestive Health",
    intro: "Bloating, pain, constipation, diarrhea, reflux, and early fullness can have many causes. The first step is understanding the pattern and making sure symptoms that need medical testing are not being treated as a food intolerance.",
    overview: ["For conditions such as IBS, different strategies help different people. Fiber type and amount, meal timing, hydration, stress, sleep, and specific fermentable carbohydrates may matter. A long list of forbidden foods is rarely a good starting point.", "A low-FODMAP approach, when appropriate, is meant to be a short structured trial followed by reintroduction. Staying on an overly restricted diet can make eating harder and reduce variety unnecessarily."],
    focus: ["Map symptoms against meals, bowel patterns, medicines, sleep, and stress without assuming one food is always the cause.", "Adjust fiber gradually and choose the type that fits constipation, diarrhea, or mixed symptoms.", "Use a structured elimination and reintroduction only when it has a clear purpose.", "Keep enough calories, protein, and variety while symptoms are being investigated."],
    visit: ["Review the symptom timeline, medical tests, bowel pattern, medicines, supplements, and current restrictions.", "Choose one testable change rather than changing ten foods at once.", "Track response and decide what should be reintroduced or referred back to a gastroenterology clinician."],
    urgent: ["Blood or black stool, persistent vomiting, severe or worsening abdominal pain, or inability to pass stool or gas.", "Unintentional weight loss, fever, anemia, dehydration, or symptoms that wake you repeatedly at night.", "New trouble swallowing, food getting stuck, or persistent pain with swallowing."],
    faq: [{ q: "Do I need a food-sensitivity test?", a: "Many commercial sensitivity panels do not diagnose the cause of digestive symptoms. Start with your medical history and appropriate clinical testing rather than a broad list of foods to avoid." }, { q: "Is low FODMAP a forever diet?", a: "No. It is generally used as a time-limited trial with careful reintroduction, so you can identify your own tolerances and return to the widest comfortable diet." }],
    image: "meal-planning.webp",
    imageAlt: "Gentle, varied meal planning for digestive symptoms",
    sources: [sources.digestive],
    related: ["celiac-disease", "food-allergies", "glp1"],
  },
  "sports-nutrition": {
    title: "Sports nutrition for training, recovery, and real schedules",
    shortTitle: "Sports Nutrition",
    intro: "Performance nutrition is not only for elite athletes. Recreational runners, strength trainees, dancers, active older adults, and students can all benefit from enough fuel, fluids, and recovery food.",
    overview: ["Training increases the need for energy and may change carbohydrate, protein, fluid, and electrolyte needs. Eating too little can reduce performance, slow recovery, raise injury risk, and affect hormones, mood, or bone health.", "Supplements come after the basics. Only a limited number have solid evidence for specific uses, and products can contain unnecessary or undisclosed ingredients. Food and a consistent training plan remain the foundation."],
    focus: ["Time carbohydrates and protein around training without turning the day into constant tracking.", "Estimate hydration and electrolyte needs from workout length, heat, sweat, and medical history.", "Plan portable meals and snacks for school, work, travel, or competitions.", "Review supplements for evidence, dose, side effects, interactions, and third-party testing."],
    visit: ["Review training type, frequency, goals, injuries, schedule, food intake, sleep, and supplements.", "Check for signs of under-fueling, including fatigue, recurrent injury, missed periods, poor recovery, or declining performance.", "Build a training-day and rest-day plan using familiar foods and realistic preparation."],
    urgent: ["Confusion, fainting, chest pain, severe shortness of breath, or signs of heat illness during activity.", "Rapid weight loss, repeated injuries, missed periods, or being unable to eat enough for training.", "Use of an unknown supplement followed by palpitations, severe anxiety, vomiting, or other sudden symptoms."],
    faq: [{ q: "Do I need a protein powder?", a: "Not necessarily. Many people can meet protein needs with food. Powder is a convenience option when timing, appetite, travel, or food access makes that difficult." }, { q: "Should I train fasted to burn more fat?", a: "Fasted training is not automatically better and may reduce workout quality or make fueling inadequate. The answer depends on session intensity, duration, tolerance, and your overall intake." }],
    image: "generated/meal-planning-colorful.png",
    imageAlt: "Colorful foods used for sports nutrition and recovery",
    sources: [sources.sports],
    related: ["weight-loss", "heart-health", "eating-disorders"],
  },
  "menopause-nutrition": {
    title: "Nutrition through perimenopause and menopause",
    shortTitle: "Menopause",
    intro: "Menopause is a normal life stage, but changes in sleep, body composition, cholesterol, bone health, and symptoms can make old eating routines feel different. You do not need a detox or a punishing diet.",
    overview: ["Lower estrogen and aging can affect bone density and cardiovascular risk. Protein, calcium, vitamin D, fiber, healthy fats, strength activity, and enough total food all matter, but needs vary with medical history and medicines.", "Hot flashes, sleep disruption, mood, and digestive symptoms can also affect eating. We look for personal triggers and practical supports rather than handing everyone the same restriction list."],
    focus: ["Spread protein across meals and support strength-building activity.", "Review calcium, vitamin D, and bone-health needs with your medical team.", "Build a heart-supportive pattern rich in fiber and unsaturated fats.", "Plan for sleep-deprived days, appetite changes, hot-flash triggers, and busy caregiving routines."],
    visit: ["Review symptoms, menstrual changes, sleep, bone and heart history, medicines, supplements, and food intake.", "Identify whether the first priority is strength, cholesterol, bowel comfort, meal regularity, or weight concerns.", "Create a plan that supports long-term health without treating normal aging as a failure."],
    urgent: ["Bleeding after menopause, very heavy bleeding, or severe pelvic pain.", "New chest pain, trouble breathing, one-sided weakness, or sudden severe headache.", "Rapid unexplained weight loss, persistent vomiting, or inability to eat."],
    faq: [{ q: "Is menopause weight gain inevitable?", a: "Body composition and energy needs can change, but experiences vary. Strength training, adequate protein, sleep support, and a sustainable eating pattern may help health even when the scale is not the only focus." }, { q: "Do I need calcium and vitamin D supplements?", a: "Not everyone needs the same dose. Food intake, age, bone density, lab results, medicines, and kidney history matter. Review supplements with your clinician." }],
    image: "team/xiaofang-tan.webp",
    imageAlt: "Nutrition support for midlife and menopause",
    sources: [sources.menopause],
    related: ["heart-health", "high-cholesterol", "weight-loss"],
  },
  "heart-health": {
    title: "Heart-healthy eating that still tastes like your food",
    shortTitle: "Heart Health",
    intro: "Heart nutrition is about the overall pattern, not one miracle ingredient. Small changes to sodium, fats, fiber, cooking methods, and meal balance can support blood pressure, cholesterol, and long-term cardiovascular health.",
    overview: ["A heart-supportive pattern usually emphasizes vegetables, fruits, whole grains, beans, nuts, fish or other lean proteins, and unsaturated fats. It limits rather than demonizes sodium, added sugars, heavily processed foods, and saturated fat.", "The best pattern must also fit your culture, budget, chewing ability, kidney function, medicines, and cooking situation. Some people still need medication even when they eat well."],
    focus: ["Find the biggest sodium sources in packaged foods, sauces, restaurant meals, and preserved foods.", "Replace some saturated fats with nuts, seeds, fish, avocado, or liquid plant oils.", "Increase soluble fiber and plant foods at a pace your digestion tolerates.", "Turn medical goals into grocery, restaurant, and family-meal decisions."],
    visit: ["Review blood pressure, cholesterol, relevant diagnoses, medicines, lab results, and usual meals.", "Choose the changes most likely to matter instead of trying to make every meal perfect.", "Set up a plan for label reading, cooking, eating out, and follow-up measurements."],
    urgent: ["Chest pressure or pain, trouble breathing, fainting, cold sweat, or pain spreading to the arm, jaw, back, or stomach.", "Sudden facial droop, arm weakness, speech trouble, confusion, or severe headache.", "Rapid swelling, sudden weight gain with shortness of breath, or symptoms your heart-care team told you to treat urgently."],
    faq: [{ q: "Do I have to stop using salt completely?", a: "Usually no. We first identify where most sodium is coming from and reduce it strategically. Your clinician may give a specific target based on blood pressure, heart, or kidney health." }, { q: "Is coconut oil heart healthy?", a: "Coconut oil is high in saturated fat. For routine cooking, liquid plant oils rich in unsaturated fat are generally a more heart-supportive choice." }],
    image: "generated/heart-health-foods.png",
    imageAlt: "Foods that support an overall heart-healthy eating pattern",
    sources: [sources.heart],
    related: ["high-cholesterol", "kidney-health", "weight-loss"],
  },
  "pregnancy-postpartum": {
    title: "Pregnancy and postpartum nutrition, one stage at a time",
    shortTitle: "Pregnancy & Postpartum",
    intro: "Nutrition needs change before pregnancy, during each trimester, and after delivery. The goal is enough nourishment and food safety, not eating perfectly or following a weight-loss plan during pregnancy.",
    overview: ["Folic acid, iron, calcium, vitamin D, iodine, choline, protein, omega-3 fats, and overall energy support parent and baby. A prenatal vitamin helps fill important gaps, but the exact product and extra supplements should be reviewed with your obstetric clinician.", "Nausea, reflux, constipation, gestational conditions, food access, cultural practices, and breastfeeding can all change the plan. Small frequent meals or easier foods may be more useful than an idealized menu."],
    focus: ["Build meals and snacks around current appetite, nausea, energy, and prenatal nutrient needs.", "Review food-safety questions, fish choices, caffeine, supplements, and herbal products.", "Support iron, bowel regularity, blood sugar, or breastfeeding needs when relevant.", "Create a low-effort postpartum food plan before the baby arrives."],
    visit: ["Review pregnancy stage, symptoms, lab results, prenatal vitamin, medicines, food safety, and feeding plans.", "Prioritize the nutrients or symptoms that need attention now rather than changing everything at once.", "Coordinate questions for the obstetric or pediatric team and update the plan as pregnancy or feeding changes."],
    urgent: ["Heavy bleeding, severe abdominal pain, fainting, severe headache, vision changes, chest pain, trouble breathing, or sudden swelling.", "Persistent vomiting or being unable to keep fluids down.", "Thoughts of harming yourself or the baby, severe panic, confusion, or feeling disconnected from reality."],
    faq: [{ q: "Do I need to eat for two?", a: "Nutrient needs rise, but energy needs do not simply double. Appetite, trimester, activity, and medical guidance matter. Focus on quality and adequacy rather than a slogan." }, { q: "Can I try to lose weight during pregnancy?", a: "Intentional weight loss during pregnancy is generally not the goal. Discuss weight, nausea, blood sugar, or appetite concerns with your obstetric clinician and dietitian." }],
    image: "nutrition-education.jpeg",
    imageAlt: "Nutrition planning during pregnancy and postpartum",
    sources: [sources.pregnancy],
    related: ["pcos", "food-allergies", "digestive-health"],
  },
  "eating-disorders": {
    title: "Eating-disorder nutrition with safety and compassion",
    shortTitle: "Eating Disorders",
    intro: "Eating disorders are serious mental and physical health conditions. They can affect people at any body size, age, gender, or background, and recovery usually needs a coordinated team.",
    overview: ["Nutrition care is not about willpower or simply telling someone to eat normally. A dietitian works with medical and mental-health clinicians to restore regular nourishment, reduce dangerous behaviors, rebuild food flexibility, and monitor physical risk.", "Weight-loss advice can be harmful when an eating disorder is active or suspected. Safety, medical stability, and recovery goals come first."],
    focus: ["Rebuild a regular eating pattern at a pace directed by the treatment team.", "Reduce food rules and anxiety while protecting medical and emotional safety.", "Plan support for meals, school, work, family, restaurants, and difficult times of day.", "Coordinate closely with a physician and therapist rather than treating nutrition in isolation."],
    visit: ["Discuss current intake, food rules, behaviors, symptoms, treatment history, and the people already on your care team.", "Identify immediate safety needs and whether medical assessment should happen before outpatient nutrition work.", "Agree on a structured next step and how the dietitian, therapist, physician, and support people will communicate."],
    urgent: ["Fainting, chest pain, irregular heartbeat, confusion, severe weakness, vomiting blood, or inability to keep food or fluids down.", "Self-harm or suicide thoughts, feeling unable to stay safe, or rapidly escalating eating-disorder behaviors.", "A clinician has warned about unstable vital signs, electrolyte problems, or refeeding risk."],
    faq: [{ q: "Do I need to look underweight to get help?", a: "No. Eating disorders occur at every body size, and serious medical complications can be present without a certain appearance." }, { q: "Can I work on weight loss and eating-disorder recovery together?", a: "When an eating disorder is active, intentional weight loss can conflict with recovery and safety. Your coordinated treatment team should guide priorities." }],
    image: "mosaic/dietitian-support.jpg",
    imageAlt: "Supportive conversation with a registered dietitian",
    sources: [sources.eating],
    related: ["digestive-health", "sports-nutrition", "weight-loss"],
  },
  "celiac-disease": {
    title: "Celiac nutrition beyond a gluten-free label",
    shortTitle: "Celiac Disease",
    intro: "Celiac disease is an autoimmune condition in which gluten damages the small intestine. It is different from a wheat allergy or a self-identified gluten sensitivity, and accurate testing matters.",
    overview: ["Do not start a gluten-free diet before celiac testing unless your medical clinician tells you to. Removing gluten can change blood-test and biopsy results and make diagnosis harder.", "After diagnosis, treatment requires a strict lifelong gluten-free diet, attention to cross-contact, label reading, restaurant communication, and correction of possible nutrient deficiencies. The goal is a complete, nourishing diet, not only buying gluten-free packaged foods."],
    focus: ["Find hidden sources of wheat, barley, rye, malt, and cross-contact in the kitchen or restaurant.", "Build balanced meals from naturally gluten-free grains, proteins, dairy or alternatives, fruits, and vegetables.", "Review fiber, iron, folate, vitamin B12, vitamin D, calcium, and other nutrients when relevant.", "Create practical plans for family kitchens, travel, school, faith gatherings, and eating out."],
    visit: ["Confirm where you are in the testing or diagnosis process and review symptoms, labs, and current restrictions.", "Map the highest cross-contact risks and the biggest nutrition gaps.", "Build a stepwise gluten-free routine and a list of questions for gastroenterology follow-up."],
    urgent: ["Severe dehydration, repeated vomiting, black or bloody stool, or intense abdominal pain.", "Rapid unintentional weight loss, marked weakness, or inability to eat enough.", "Signs of a serious allergic reaction; celiac disease and wheat allergy are different and anaphylaxis needs emergency care."],
    faq: [{ q: "Should I stop gluten now to see if I feel better?", a: "If celiac disease is possible, talk with your clinician before stopping. Testing is most accurate while you are still eating gluten." }, { q: "Are oats gluten free?", a: "Oats are naturally gluten free, but cross-contact is common and some people with celiac disease need additional guidance. Choose appropriately labeled products and follow your care team's advice." }],
    image: "generated/carb-education-foods.png",
    imageAlt: "Naturally gluten-free foods for celiac nutrition",
    sources: [sources.celiac],
    related: ["digestive-health", "food-allergies", "pregnancy-postpartum"],
  },
  "kidney-health": {
    title: "Kidney nutrition based on your stage and lab results",
    shortTitle: "Kidney Health",
    intro: "There is no single kidney diet. Sodium, protein, potassium, phosphorus, and fluid needs depend on kidney function, lab results, medicines, whether you receive dialysis, and whether you are eating enough.",
    overview: ["Cutting out every high-potassium or high-protein food without a reason can cause poor nutrition. Early kidney disease may require only a few changes, while advanced disease or dialysis can require a very different plan.", "A kidney dietitian translates lab results and medical instructions into meals while protecting calories, protein, enjoyment, and cultural foods."],
    focus: ["Find major sodium sources and lower them without making food tasteless.", "Match protein amount and sources to kidney stage and dialysis status.", "Adjust potassium, phosphorus, or fluids only when labs and the medical plan call for it.", "Review supplements and salt substitutes, many of which can contain potassium or other risky ingredients."],
    visit: ["Review kidney diagnosis, recent labs, blood pressure, medicines, swelling, urine changes, dialysis status, and current intake.", "Identify which nutrients truly need attention now and which foods do not need to be removed.", "Create meal, grocery, restaurant, and follow-up plans that change when lab results change."],
    urgent: ["Trouble breathing, chest pain, confusion, severe weakness, or a very irregular heartbeat.", "Rapid swelling, very little urine, sudden weight gain from fluid, or being unable to keep fluids down.", "Your kidney team has given you a specific emergency threshold for potassium, blood pressure, or fluid symptoms."],
    faq: [{ q: "Do I have to avoid bananas, tomatoes, and beans?", a: "Not everyone with kidney disease needs a low-potassium diet. Your blood potassium, medicines, stage, portions, and preparation methods determine what fits." }, { q: "Should I eat less protein?", a: "Some people not on dialysis need moderate protein, while people on dialysis may need more. Too little can cause malnutrition, so use an individualized target." }],
    image: "generated/meal-planning-care.png",
    imageAlt: "Individualized meal planning for kidney health",
    sources: [sources.kidney],
    related: ["heart-health", "high-cholesterol", "weight-loss"],
  },
  "cancer-nutrition": {
    title: "Nutrition before, during, and after cancer treatment",
    shortTitle: "Cancer Nutrition",
    intro: "Cancer and its treatment can change appetite, taste, swallowing, digestion, weight, strength, and the ability to cook or shop. Nutrition goals must follow the treatment plan and may look different from everyday wellness advice.",
    overview: ["During treatment, maintaining strength and preventing malnutrition may matter more than weight loss or eating an ideal diet. Some people need extra protein and calories, smaller frequent meals, softer textures, or liquids that are easier to tolerate.", "Supplements, fasting, and restrictive cancer diets can interact with treatment or worsen low intake. Discuss them with the oncology team before starting."],
    focus: ["Manage nausea, early fullness, taste changes, mouth soreness, diarrhea, constipation, or swallowing problems.", "Increase protein, calories, and fluids in the form you can tolerate.", "Plan easy foods and family support for treatment days and periods of fatigue.", "Coordinate supplements, tube-feeding questions, and symptom changes with oncology."],
    visit: ["Review cancer type, treatment schedule, side effects, weight and intake changes, labs, medicines, and supplements.", "Identify the most urgent nutrition barrier and choose foods or textures that address it.", "Set clear thresholds for calling the oncology team and update the plan as treatment changes."],
    urgent: ["Fever or infection symptoms during treatment, repeated vomiting, dehydration, or inability to swallow.", "Rapid weight loss, very low intake, new confusion, severe weakness, or uncontrolled diarrhea.", "Any symptom your oncology team has told you to report immediately."],
    faq: [{ q: "Should I avoid sugar because it feeds cancer?", a: "All cells use glucose. Removing all carbohydrates does not selectively starve cancer and can make it harder to get enough energy. Treatment-specific advice should come from your oncology team." }, { q: "Can I take antioxidants or herbal supplements?", a: "Do not assume they are harmless. Some supplements may interact with chemotherapy, radiation, surgery, or other medicines. Review the exact product with oncology." }],
    image: "mosaic/meal-planning.jpg",
    imageAlt: "Flexible nutrition planning during cancer treatment",
    sources: [sources.cancer],
    related: ["digestive-health", "kidney-health", "weight-loss"],
  },
  "high-cholesterol": {
    title: "Lowering cholesterol with food you can keep eating",
    shortTitle: "High Cholesterol",
    intro: "Cholesterol numbers are interpreted together with age, blood pressure, family history, smoking, other conditions, and overall cardiovascular risk. A single total-cholesterol number does not tell the whole story.",
    overview: ["Eating patterns can help lower LDL cholesterol and support heart health. The most useful changes often include replacing saturated fats with unsaturated fats, increasing soluble fiber, choosing more plant foods, and staying active.", "Some people still need medication because genetics and medical risk matter. Food and medicine are not competing choices; they can work together."],
    focus: ["Identify the main saturated-fat sources in meats, dairy, baked foods, coconut or palm oils, and restaurant meals.", "Add soluble fiber from oats, beans, lentils, fruit, and other tolerated foods.", "Use nuts, seeds, fish, avocado, and liquid plant oils in place of some saturated fats.", "Turn lab goals into repeatable breakfasts, snacks, cooking methods, and restaurant choices."],
    visit: ["Review the full lipid panel, family history, medicines, other conditions, and current eating pattern.", "Choose a few high-impact swaps that preserve taste and cultural foods.", "Set a follow-up window with your medical clinician to review labs and medication decisions."],
    urgent: ["High cholesterol itself usually has no urgent symptoms, but chest pain, trouble breathing, fainting, or stroke signs require emergency care.", "A new medicine causes severe muscle pain, weakness, dark urine, or another serious reaction; contact the prescriber promptly."],
    faq: [{ q: "Do eggs cause high cholesterol?", a: "For many people, the overall pattern and saturated fat intake matter more than one food. Your lab response, portions, and other health risks should guide the decision." }, { q: "Can diet replace a statin?", a: "Sometimes lifestyle change is enough for a person's risk level; sometimes medication is strongly recommended. That decision should be based on your overall cardiovascular risk with your clinician." }],
    image: "generated/heart-health-foods.png",
    imageAlt: "Fiber-rich and unsaturated-fat foods for cholesterol care",
    sources: [sources.cholesterol, sources.heart],
    related: ["heart-health", "thyroid-health", "weight-loss"],
  },
  "food-allergies": {
    title: "Food-allergy nutrition that protects safety and variety",
    shortTitle: "Food Allergies",
    intro: "A food allergy is an immune reaction and can become life-threatening. It is different from an intolerance, which may be uncomfortable but does not cause anaphylaxis.",
    overview: ["Medical diagnosis and an emergency plan belong with an allergy clinician. Nutrition support helps you read labels, prevent cross-contact, replace missing nutrients, and make school, restaurant, travel, and family meals safer.", "In the United States, nine major allergens must be identified on packaged foods: milk, egg, fish, crustacean shellfish, tree nuts, peanuts, wheat, soy, and sesame. Labels still need to be checked every time because recipes can change."],
    focus: ["Learn label language, hidden ingredients, and cross-contact risks without avoiding unrelated foods.", "Replace nutrients lost when milk, egg, wheat, soy, nuts, or other staples are removed.", "Create scripts and plans for restaurants, schools, caregivers, travel, and community events.", "Coordinate food challenges, reintroduction, and emergency medication questions with the allergist."],
    visit: ["Review confirmed allergies, testing, past reactions, emergency plan, medicines, and all current restrictions.", "Check whether the diet is missing calories, protein, calcium, vitamin D, fiber, or other nutrients.", "Build a safe-food list, cross-contact plan, and realistic meals for home and outside settings."],
    urgent: ["Trouble breathing, throat tightness, wheezing, fainting, or symptoms affecting more than one body system after eating.", "Use epinephrine as prescribed in your emergency plan and call emergency services for suspected anaphylaxis.", "Repeated vomiting, rapidly spreading hives, swelling, or a reaction that is getting worse."],
    faq: [{ q: "Is a food allergy the same as an intolerance?", a: "No. Allergy involves the immune system and may cause anaphylaxis. Intolerance usually causes digestive or other non-immune symptoms. Testing and history help distinguish them." }, { q: "Should I avoid foods labeled 'may contain'?", a: "Precautionary labels are not standardized in the same way as ingredient labels. Follow the risk plan made with your allergist rather than guessing from package wording alone." }],
    image: "generated/meal-planning-colorful.png",
    imageAlt: "Safe and varied meal planning for food allergies",
    sources: [sources.allergies],
    related: ["celiac-disease", "digestive-health", "pregnancy-postpartum"],
  },
};

const zh = {
  "weight-loss": {
    title: "减重不是发一张所有人都一样的食谱",
    shortTitle: "减重",
    intro: "体重会受到胃口、睡眠、药物、压力、疾病、食物选择、文化习惯和日常作息影响。我们先看完整情况，不从一长串“不能吃”开始。",
    overview: ["真正有用的减重方案，应该能改善健康，也能放进普通的一周里。根据你的情况，可能会谈吃饭结构、活动、睡眠、行为支持、药物或医学评估。", "体重秤只是一个指标。精神、体力、血压、化验结果、肠胃状态和你与食物的关系，同样重要。目标会和你一起定，不用羞耻或责备推动改变。"],
    focus: ["把蛋白质、纤维和你真正喜欢吃的东西放进每餐，让饭后更踏实。", "找出饥饿、压力、作息或药物最容易让吃饭失去节奏的时间。", "把方法放进外食、旅行、家庭聚餐和忙碌工作日，而不是只适合“完美的一天”。", "如果症状、药物或化验结果可能影响体重，和医生一起协调。"],
    visit: ["先了解健康和体重经历、药物、睡眠、活动，以及现在真实怎么吃。", "一起说清楚什么叫“有进步”，也包括不在体重秤上的目标。", "带走两三件这周做得到的事，而不是一张很快就执行不下去的完美餐单。"],
    urgent: ["没有主动减重，体重却在短时间内明显变化。", "反复呕吐、晕倒、无法正常吃喝，或出现脱水。", "对食物、体重或运动的想法已经造成严重痛苦或危险行为。"],
    faq: [{ q: "一定要每天算卡路里吗？", a: "不一定。记录对一些人有帮助，但不是唯一方法。也可以从份量、吃饭时间、饥饿感和稳定的餐食结构入手。" }, { q: "多快才算正常？", a: "没有适合所有人的速度。起点、疾病、药物和过去的减重经历都会影响安全范围。我们更在意营养、肌肉和日常功能有没有被保护。" }, { q: "中餐、外卖和聚餐还能吃吗？", a: "可以。脱离真实生活的方案很难长期执行。我们会在你本来就会吃的食物里，找最值得调整的地方。" }],
  },
  glp1: {
    title: "使用 GLP-1 时，怎么吃得下也吃得够",
    shortTitle: "GLP-1",
    intro: "GLP-1 及相关药物会改变饥饿感、饱腹感、消化速度和食物耐受。营养支持的重点，是在医生管理药物的同时，帮你吃够营养、保护肌肉，并处理常见副作用。",
    overview: ["司美格鲁肽、利拉鲁肽、替尔泊肽等药物有不同适应证、剂量和注意事项，不能互相当成同一种药。是否适合、怎么加量和什么时候停药，都需要由有资质的处方医生决定。", "胃口变小以后，目标不只是“吃得越少越好”。蛋白质、水分、纤维、维生素和总能量仍然要顾到；加量期出现恶心、便秘或很快就饱时，吃法也需要调整。"],
    focus: ["把餐量变小、速度放慢，找出身体舒服的份量。", "把蛋白质和水分分散到一天里，不要到晚餐才一次补。", "恶心、反酸、腹泻或便秘时，调整纤维、油脂、进餐时间和食物质地。", "提前安排旅行、外食、加量期，以及需要问处方医生的问题。"],
    visit: ["核对具体药物、剂量时间、其他药物、症状，以及现在到底能吃喝多少。", "看看是否已经出现摄入不足，例如乏力、体重下降过快、脱水或蛋白质明显不够。", "做一份简单的吃饭与补水安排，并列清楚哪些症状要及时告诉医生。"],
    urgent: ["持续或严重腹痛，特别是同时呕吐。", "反复呕吐、尿色很深、头晕，或喝水也留不住。", "过敏反应、明显意识变化、严重虚弱，或突然出现让你觉得危险的症状。"],
    faq: [{ q: "不饿是不是就可以不吃？", a: "大餐可能吃不下，但如果一整天几乎没吃，蛋白质、水分和微量营养素容易不够。少量多次通常更容易。" }, { q: "一定要喝蛋白粉吗？", a: "不一定。能用食物达到需求就可以；固体食物很难吃下时，蛋白饮品可能是方便工具，但要结合肠胃耐受和疾病情况选择。" }, { q: "营养师能帮我改剂量吗？", a: "不能。剂量调整属于处方医生。营养师可以把吃饭、症状和补水情况整理清楚，让你和医生讨论得更准确。" }],
  },
  "medical-weight-loss": {
    title: "医学减重，也要把每天怎么吃放进方案里",
    shortTitle: "医学减重",
    intro: "医学减重会一起看健康风险、可能影响体重的因素和治疗选择。药物可以是工具之一，但不应该是全部内容。",
    overview: ["医学评估可能会了解血压、症状、睡眠、药物、体重经历、家族史和相关化验。目的不是见面就开药，而是把风险和适合你的方法讲清楚。", "如果药物合适，后续营养照护可以帮助保护肌肉、维持水分、处理副作用，并建立即使治疗变化后仍然有用的习惯。"],
    focus: ["整理清楚饮食、症状和体重经历，方便医学评估。", "根据血压、胆固醇、肠胃、多囊等情况调整吃法。", "跟进胃口、耐受、水分、体力和合理进度。", "把需要医生判断的问题列清楚，避免营养和处方各做各的。"],
    visit: ["先由营养师了解需求和最重要的健康目标。", "涉及临床评估或处方时，安排医生参与。", "之后继续用具体饮食调整和症状记录一起跟进。"],
    urgent: ["胸痛、呼吸困难、晕倒或突然单侧无力。", "体重短时间异常变化、严重水肿或无法正常吃喝。", "开始或调整药物后出现严重反应。"],
    faq: [{ q: "医学减重一定要用药吗？", a: "不一定。医学评估是为了判断药物是否合适。营养、睡眠、活动和相关疾病治疗，也可能是主要方案。" }, { q: "用了药还需要见营养师吗？", a: "需要时很有帮助。营养师处理的是药物本身不会自动解决的吃饭、症状和日常习惯。" }],
  },
  pcos: {
    title: "多囊营养，不把问题都怪在你身上",
    shortTitle: "多囊（PCOS）",
    intro: "多囊卵巢综合征会影响月经、排卵、皮肤、毛发、胰岛素反应和长期健康。它是激素相关问题，不是因为你“吃错了”才发生。",
    overview: ["每个人的多囊表现不同，可能有月经不规律、痤疮、毛发增多、备孕困难或体重变化，也可能只有一部分表现。诊断和药物需要由医生负责。", "并不存在唯一的“多囊食谱”。规律吃饭、足够蛋白质和纤维、适合自己的活动、睡眠，以及关注血脂或血糖可能有帮助，但要根据症状和目标来安排。"],
    focus: ["把吃饭节奏稳定下来，减少长时间不吃以后特别饿或特别想吃甜食。", "增加纤维、蛋白质和有满足感的脂肪，不需要把碳水全部删掉。", "同时考虑备孕、运动、肠胃或体重目标，避免规则互相打架。", "把营养方案和药物、化验、备孕计划放在一起讨论。"],
    visit: ["了解症状、月经、化验、药物、补充剂，以及已经尝试过什么。", "先选现在最困扰的一两件事，例如精力、吃饭规律、胆固醇或食物焦虑。", "做一份灵活方案，并列出需要问妇科或家庭医生的问题。"],
    urgent: ["大量出血、严重盆腔痛、晕倒，或可能怀孕同时出现危险症状。", "严重抑郁、自伤想法，或饮食行为已经不安全。", "明显口渴、多尿、呕吐、意识变化等可能提示血糖很高的表现。"],
    faq: [{ q: "是不是必须戒掉所有碳水？", a: "不需要。碳水仍然可以是均衡饮食的一部分。种类、份量、和什么一起吃，以及能否长期做到，比完全禁掉更重要。" }, { q: "瘦下来多囊就会好了吗？", a: "多囊并不只发生在某一种体型，减重也不是“治愈”。有人会选择体重目标，也有人更需要改善症状、化验、备孕、体力或吃饭规律。" }],
  },
  "thyroid-health": {
    title: "甲状腺问题，食物能帮什么、不能代替什么",
    shortTitle: "甲状腺健康",
    intro: "甲状腺功能减退可能影响精力、怕冷、月经、胆固醇和体重，但这些表现也可能来自其他原因，所以需要化验和医生诊断。",
    overview: ["甲减通常需要甲状腺激素药物治疗，食物不能代替药物。额外补碘也不一定有帮助，海带、昆布或高剂量碘补充剂反而可能让某些自身免疫性甲状腺问题变差。", "营养支持更适合用来保证吃够、改善便秘、帮助胆固醇管理、检查补充剂，并按医生要求安排药物与食物或矿物质补充剂的时间。"],
    focus: ["看看长时间不吃、摄入太少或纤维不足是否让乏力和便秘更明显。", "不要默认碘、生物素、钙、铁或草药补充剂都对甲状腺安全。", "胆固醇偏高时，建立对心脏更友好的饮食。", "把药物时间和复查化验的问题准备好，交给处方医生确认。"],
    visit: ["了解诊断、化验、用药时间、症状、补充剂和日常饮食。", "分清哪些可以通过营养改善，哪些必须靠药物或继续检查。", "在医学随访同时，先处理排便、精力或胆固醇中最实际的问题。"],
    urgent: ["异常嗜睡、意识不清、呼吸困难、体温很低或身体机能明显变慢。", "已经确诊甲状腺疾病又怀孕或刚测出怀孕，请尽快联系医生。", "调整甲状腺药后出现明显心跳过快、心律不齐或严重乏力。"],
    faq: [{ q: "要不要补碘或吃很多海带？", a: "不要自己开始高剂量碘或海带补充剂。过量碘可能让某些自身免疫性甲状腺问题变差，先让医生看具体产品。" }, { q: "甲状腺药会被食物影响吗？", a: "吸收可能受服药时间和钙、铁等补充剂影响。请按处方说明服用，并向医生或药师确认间隔。" }],
  },
  "digestive-health": {
    title: "肠胃不舒服，不等于什么都不能吃",
    shortTitle: "肠胃健康",
    intro: "腹胀、腹痛、便秘、腹泻、反酸和很快就饱可能有很多原因。第一步是看清规律，也要先排除需要医学检查的问题，不要把所有症状都当成“食物不耐受”。",
    overview: ["以肠易激综合征为例，不同人适合的方法不同。纤维种类和份量、吃饭时间、水分、压力、睡眠和某些易发酵碳水都可能有关。直接列一长串禁食清单通常不是好起点。", "低 FODMAP 饮食在合适时应该是短期、结构化尝试，之后逐步重新引入。长期过度限制会让吃饭更困难，也可能不必要地减少食物多样性。"],
    focus: ["把症状、进餐、排便、药物、睡眠和压力放在一起看，不先认定某一种食物一定有问题。", "根据便秘、腹泻或混合症状，逐步调整合适类型的纤维。", "只有目的明确时才做限制，并安排重新引入。", "检查过程中也要保护总能量、蛋白质和食物多样性。"],
    visit: ["梳理症状时间、做过的检查、排便、药物、补充剂和现在已经不吃的东西。", "一次先改变一件可以验证的事，不同时删掉十种食物。", "根据反应决定哪些食物可以加回来，哪些问题要转回消化科。"],
    urgent: ["便血或黑便、持续呕吐、严重或加重的腹痛，或完全无法排便排气。", "非主动体重下降、发烧、贫血、脱水，或症状反复在夜里把你痛醒。", "新出现吞咽困难、食物卡住或吞咽持续疼痛。"],
    faq: [{ q: "需要做一套食物敏感检测吗？", a: "很多商业“敏感”检测不能诊断肠胃症状原因。更可靠的起点是病史和合适的医学检查，而不是先得到一张很长的禁食名单。" }, { q: "低 FODMAP 要吃一辈子吗？", a: "不是。通常是有限时间的尝试，之后有计划地重新引入，找出你自己的耐受范围，尽量恢复到最广泛、舒服的饮食。" }],
  },
  "sports-nutrition": {
    title: "运动营养，服务训练、恢复和真实作息",
    shortTitle: "运动营养",
    intro: "运动营养不只是职业运动员才需要。跑步、力量训练、舞蹈、学生训练和中老年人保持肌力，都可以从足够的能量、水分和恢复饮食中受益。",
    overview: ["训练会增加能量需要，也可能改变碳水、蛋白质、水分和电解质需求。吃得太少会影响表现和恢复，也可能增加受伤风险，影响激素、情绪和骨骼健康。", "补充剂应该排在基础饮食之后。只有少数产品对特定目标有足够证据，而且产品可能含不必要或未标明的成分。正常吃饭和稳定训练仍然是基础。"],
    focus: ["安排训练前后碳水和蛋白质，不让一天变成不停计算。", "根据运动时长、天气、出汗和疾病情况估算水分及电解质。", "为上学、上班、旅行或比赛准备方便携带的餐和加餐。", "核对补充剂的证据、剂量、副作用、相互作用和第三方检测。"],
    visit: ["了解训练项目、频率、目标、伤病、时间表、吃饭、睡眠和补充剂。", "检查乏力、反复受伤、月经停止、恢复差或表现下降等吃不够的信号。", "用熟悉的食物做训练日和休息日计划。"],
    urgent: ["运动时意识不清、晕倒、胸痛、严重呼吸困难或中暑表现。", "体重快速下降、反复受伤、月经停止或无法吃够支撑训练。", "服用来源不明补充剂后出现心悸、严重焦虑、呕吐或突发症状。"],
    faq: [{ q: "一定要喝蛋白粉吗？", a: "不一定。很多人可以从食物吃够；当时间、胃口、旅行或食物条件受限时，蛋白粉只是方便工具。" }, { q: "空腹训练是不是更燃脂？", a: "不一定更好，还可能降低训练质量或让全天摄入不足。要看训练强度、时长、耐受和整体饮食。" }],
  },
  "menopause-nutrition": {
    title: "围绝经期和更年期，吃饭也可以跟着身体调整",
    shortTitle: "更年期营养",
    intro: "更年期是正常人生阶段，但睡眠、身体组成、胆固醇、骨骼和各种症状的变化，可能让过去的吃法不再合适。你不需要排毒，也不需要用极端节食惩罚自己。",
    overview: ["雌激素下降和年龄变化会影响骨密度及心血管风险。蛋白质、钙、维生素 D、纤维、健康脂肪、力量活动和足够总能量都重要，但要结合疾病和药物。", "潮热、睡不好、情绪和肠胃症状也会影响吃饭。我们会找个人触发因素和实际支持，不给所有人同一张限制清单。"],
    focus: ["把蛋白质分散到每餐，并配合适合的力量活动。", "和医生一起检查钙、维生素 D 与骨骼健康需求。", "用纤维和不饱和脂肪支持心脏。", "为睡不好、胃口变化、潮热和照顾家人的忙碌日做准备。"],
    visit: ["了解症状、月经变化、睡眠、骨骼和心脏史、药物、补充剂和饮食。", "先决定当前最需要处理的是肌力、胆固醇、排便、吃饭规律还是体重困扰。", "做一份支持长期健康的计划，不把正常年龄变化当成失败。"],
    urgent: ["绝经后出血、大量出血或严重盆腔痛。", "新发胸痛、呼吸困难、单侧无力或突然严重头痛。", "不明原因快速消瘦、持续呕吐或无法进食。"],
    faq: [{ q: "更年期一定会发胖吗？", a: "身体组成和能量需要可能变化，但每个人不同。力量训练、足够蛋白质、睡眠支持和可持续饮食，即使不只看体重，也能改善健康。" }, { q: "是不是都要补钙和维生素 D？", a: "剂量不能人人一样。饮食、年龄、骨密度、化验、药物和肾脏情况都会影响决定，先让医生核对。" }],
  },
  "heart-health": {
    title: "护心饮食，也可以保留你熟悉的味道",
    shortTitle: "心脏健康",
    intro: "护心不是靠某一种神奇食物，而是看整体吃法。调整钠、脂肪、纤维、烹调和餐食结构，可以支持血压、胆固醇和长期心血管健康。",
    overview: ["对心脏友好的吃法通常包括更多蔬菜水果、全谷、豆类、坚果、鱼或其他瘦蛋白和不饱和脂肪，同时适量减少钠、添加糖、重加工食品和饱和脂肪。", "真正适合的方案还要考虑文化、预算、咀嚼能力、肾功能、药物和做饭条件。有些人认真调整饮食后仍然需要药物。"],
    focus: ["找到包装食品、酱料、外食和腌制食品里最主要的钠。", "把一部分饱和脂肪换成坚果、种子、鱼、牛油果或液体植物油。", "按肠胃耐受逐步增加可溶性纤维和植物性食物。", "把医学目标变成买菜、做饭、点餐和家庭聚餐中的选择。"],
    visit: ["了解血压、血脂、诊断、药物、化验和日常饮食。", "选最可能有效的几项改变，不要求每餐都完美。", "安排看标签、烹调、外食和复查指标的计划。"],
    urgent: ["胸部压迫或疼痛、呼吸困难、晕倒、冷汗，或疼痛放射到手臂、下巴、后背或胃部。", "突然嘴歪、手臂无力、说话含糊、意识异常或严重头痛。", "快速水肿、伴呼吸困难的突然增重，或心脏团队要求你紧急处理的症状。"],
    faq: [{ q: "是不是完全不能放盐？", a: "通常不需要从零盐开始。先找出大部分钠从哪里来，再针对性减少。医生可能根据心脏、血压或肾脏情况给你具体目标。" }, { q: "椰子油对心脏好吗？", a: "椰子油的饱和脂肪较高。日常烹调通常更建议使用富含不饱和脂肪的液体植物油。" }],
  },
  "pregnancy-postpartum": {
    title: "孕期和产后营养，跟着每个阶段慢慢调整",
    shortTitle: "孕期与产后营养",
    intro: "备孕、不同孕期和产后需要的营养会变化。重点是吃够、吃得安全，不是要求完美，也不建议在孕期自行进行减重计划。",
    overview: ["叶酸、铁、钙、维生素 D、碘、胆碱、蛋白质、Omega-3 和总能量会支持孕妇和宝宝。孕期维生素能补上重要缺口，但具体产品和额外补充剂需要让产科医生核对。", "恶心、反酸、便秘、妊娠相关疾病、食物条件、文化习惯和母乳喂养都会改变方案。少量多次或更容易入口的食物，有时比理想菜单更有用。"],
    focus: ["根据当前胃口、恶心、精力和孕期营养需求安排餐和加餐。", "核对食品安全、鱼类、咖啡因、补充剂和草药。", "需要时支持铁、排便、血糖或母乳喂养。", "在宝宝出生前准备一套低劳动量的产后吃饭计划。"],
    visit: ["了解孕周、症状、化验、孕期维生素、药物、食品安全和喂养计划。", "先处理当前最重要的营养或症状问题，不一次改变全部。", "把需要问产科或儿科的问题列好，随着孕期和喂养变化更新方案。"],
    urgent: ["大量出血、严重腹痛、晕倒、剧烈头痛、视力变化、胸痛、呼吸困难或突然水肿。", "持续呕吐或完全喝不下水。", "伤害自己或宝宝的想法、严重恐慌、意识混乱或明显脱离现实。"],
    faq: [{ q: "怀孕是不是要吃两个人的量？", a: "营养需要增加，但热量不是简单翻倍。胃口、孕期阶段、活动和医学建议都重要，重点是足够和均衡。" }, { q: "孕期可以减重吗？", a: "孕期一般不以主动减重为目标。体重、恶心、血糖或胃口问题，需要和产科医生及营养师一起讨论。" }],
  },
  "eating-disorders": {
    title: "进食障碍营养支持，把安全和尊重放在前面",
    shortTitle: "进食障碍",
    intro: "进食障碍是严重的身心健康问题，任何体型、年龄、性别和背景的人都可能经历。恢复通常需要医生、心理治疗师和营养师一起合作。",
    overview: ["营养治疗不是靠意志力，也不是一句“正常吃就好”。营养师会和医疗及心理团队一起恢复规律营养、减少危险行为、慢慢扩大食物弹性并监测身体风险。", "当进食障碍正在发生或高度怀疑时，减重建议可能带来伤害。医学安全和恢复目标优先。"],
    focus: ["按照治疗团队安排，逐步恢复规律进食。", "在保护身体和情绪安全的前提下减少食物规则与恐惧。", "为正餐、学校、工作、家庭、外食和最难熬的时段准备支持。", "和医生、治疗师密切配合，不把营养单独处理。"],
    visit: ["了解现在的摄入、食物规则、相关行为、症状、治疗经历和现有团队。", "先判断当前安全风险，以及是否需要先做医学评估。", "一起确定结构化下一步，并说清医生、治疗师、营养师和家人怎样沟通。"],
    urgent: ["晕倒、胸痛、心律异常、意识不清、严重虚弱、吐血或完全吃喝不下。", "自伤或自杀想法、无法保证自己安全，或相关行为快速升级。", "医生已经提醒生命体征、电解质或再喂养风险不稳定。"],
    faq: [{ q: "一定要看起来很瘦才需要帮助吗？", a: "不需要。任何体型都可能有进食障碍，也可能在没有特定外表时出现严重医学风险。" }, { q: "可以一边减重一边恢复吗？", a: "进食障碍活跃时，主动减重常常会和恢复及安全冲突，优先顺序应由完整治疗团队决定。" }],
  },
  "celiac-disease": {
    title: "乳糜泻营养，不只是买“无麸质”食品",
    shortTitle: "乳糜泻",
    intro: "乳糜泻是麸质引发的小肠自身免疫损伤，和小麦过敏或自己感觉的麸质敏感不同，准确检查很重要。",
    overview: ["如果怀疑乳糜泻，在完成检查前不要自己先停麸质，除非医生明确要求。提前停掉会影响抽血和小肠活检结果，让诊断更困难。", "确诊后需要终身严格无麸质，同时处理交叉接触、标签、外食和可能的营养缺口。目标不是只买加工无麸质食品，而是吃得完整。"],
    focus: ["找出小麦、大麦、黑麦、麦芽和厨房或餐厅的交叉接触。", "用天然无麸质谷物、蛋白质、奶或替代品、蔬果组成均衡餐。", "需要时检查纤维、铁、叶酸、B12、维生素 D 和钙。", "为家庭厨房、旅行、学校、宗教活动和外食制定方法。"],
    visit: ["先确认目前处在检查还是确诊阶段，并了解症状、化验和现有禁食。", "找出最大的交叉接触风险和营养缺口。", "分步骤建立无麸质生活，并列出消化科复查问题。"],
    urgent: ["严重脱水、反复呕吐、黑便或便血、剧烈腹痛。", "非主动快速消瘦、明显虚弱或无法吃够。", "严重过敏反应；乳糜泻和小麦过敏不同，过敏性休克需要急诊。"],
    faq: [{ q: "要不要先停麸质看看会不会舒服？", a: "如果可能是乳糜泻，停之前先问医生。继续摄入麸质时检测通常更准确。" }, { q: "燕麦可以吃吗？", a: "燕麦天然无麸质，但交叉接触常见，有些人还需要额外评估。选择合适标示产品，并听从医疗团队建议。" }],
  },
  "kidney-health": {
    title: "肾脏饮食要看分期和化验，不能一张表管所有人",
    shortTitle: "肾脏健康",
    intro: "不存在一套人人相同的肾脏餐。钠、蛋白质、钾、磷和水分需求，要看肾功能、化验、药物、是否透析，以及有没有吃够。",
    overview: ["没有根据就把所有高钾或高蛋白食物删掉，可能导致营养不足。早期肾病有时只需少量调整，晚期或透析后的方案则可能完全不同。", "肾脏营养师会把化验和医嘱翻译成每天能吃的饭，同时保护总能量、蛋白质、口味和文化饮食。"],
    focus: ["找主要钠来源，降低钠但不让饭完全没味道。", "根据分期和透析状态安排蛋白质数量与来源。", "只有化验和医生方案需要时才限钾、磷或水分。", "检查补充剂和代盐，很多代盐含钾，未必安全。"],
    visit: ["了解肾病诊断、近期化验、血压、药物、水肿、尿量、透析和日常饮食。", "分清现在真正需要调整哪些营养，哪些食物不用删。", "做买菜、做饭、外食和复查计划，化验变化时再更新。"],
    urgent: ["呼吸困难、胸痛、意识不清、严重无力或心跳明显不规律。", "快速水肿、尿量很少、因积液突然增重，或完全喝不下水。", "肾科团队已经给过你钾、血压或水分症状的紧急处理标准。"],
    faq: [{ q: "香蕉、番茄和豆类是不是都不能吃？", a: "不是所有肾病都需要低钾。血钾、药物、分期、份量和烹调方式决定能不能放进方案。" }, { q: "是不是一定要少吃蛋白质？", a: "未透析者有时需要适量蛋白质，透析者反而可能需要更多。吃得太少会营养不良，所以必须个体化。" }],
  },
  "cancer-nutrition": {
    title: "肿瘤治疗前后，营养目标要跟着治疗走",
    shortTitle: "肿瘤营养",
    intro: "肿瘤和治疗会改变胃口、味觉、吞咽、消化、体重、体力，也可能让买菜和做饭变得很难。营养目标必须配合治疗方案，不能直接套用普通“健康减重餐”。",
    overview: ["治疗期间，保持体力和预防营养不良可能比减重或吃得非常理想更重要。有些人需要更多蛋白质和热量、少量多餐、软食或更容易入口的液体。", "补充剂、断食和极端“抗癌饮食”可能和治疗相互作用，也可能让摄入更不足，开始前一定要问肿瘤团队。"],
    focus: ["处理恶心、早饱、味觉变化、口腔疼痛、腹泻、便秘或吞咽困难。", "用能耐受的形式补充蛋白质、热量和水分。", "为治疗日和疲劳期准备省力食物及家人支持。", "把补充剂、管饲和症状变化及时和肿瘤团队沟通。"],
    visit: ["了解肿瘤类型、治疗安排、副作用、体重和摄入变化、化验、药物与补充剂。", "先处理最影响吃饭的一项问题，选择相应食物或质地。", "说清什么时候要联系肿瘤团队，并随治疗变化更新方案。"],
    urgent: ["治疗中发烧或感染表现、反复呕吐、脱水或完全吞不下。", "体重快速下降、摄入很低、意识变化、严重虚弱或腹泻失控。", "肿瘤团队特别交代必须立即报告的任何症状。"],
    faq: [{ q: "是不是要戒糖，因为糖会喂癌细胞？", a: "所有细胞都会使用葡萄糖。完全去掉碳水不能只饿死癌细胞，反而可能让总能量不足。具体吃法要配合治疗。" }, { q: "抗氧化剂或草药可以吃吗？", a: "不要默认天然就安全。有些补充剂会影响化疗、放疗、手术或其他药物，请把具体产品交给肿瘤团队核对。" }],
  },
  "high-cholesterol": {
    title: "降胆固醇，不靠短期戒口",
    shortTitle: "高胆固醇",
    intro: "胆固醇要和年龄、血压、家族史、吸烟、其他疾病和整体心血管风险一起解释，只看总胆固醇一个数字并不够。",
    overview: ["饮食可以帮助降低 LDL 并支持心脏健康。常见有效方向是用不饱和脂肪替代饱和脂肪、增加可溶性纤维和植物性食物，并保持活动。", "遗传和医学风险也很重要，所以有人认真调整饮食后仍需要药物。食物和药物不是二选一，可以一起发挥作用。"],
    focus: ["找出肥肉、全脂奶、烘焙食品、椰子油、棕榈油和外食里的主要饱和脂肪。", "从燕麦、豆类、扁豆、水果等逐步增加可溶性纤维。", "用坚果、种子、鱼、牛油果和液体植物油替代一部分饱和脂肪。", "把化验目标放进早餐、加餐、烹调和点餐。"],
    visit: ["了解完整血脂、家族史、药物、其他疾病和日常饮食。", "保留口味和文化饮食，选几个影响最大的替换。", "和医生安排复查时间，并讨论是否需要药物。"],
    urgent: ["高胆固醇通常没有急症表现，但胸痛、呼吸困难、晕倒或中风征象需要急诊。", "新药后出现严重肌肉疼痛、无力、尿色很深或其他严重反应，请尽快联系处方医生。"],
    faq: [{ q: "鸡蛋会不会让胆固醇升高？", a: "对很多人来说，整体饮食和饱和脂肪比某一种食物更重要。具体还要看化验反应、份量和其他风险。" }, { q: "饮食能不能代替他汀？", a: "有些人的风险适合先生活调整，有些人强烈建议用药。要和医生根据整体心血管风险决定。" }],
  },
  "food-allergies": {
    title: "食物过敏管理，既要安全也要吃得完整",
    shortTitle: "食物过敏",
    intro: "食物过敏是免疫系统反应，严重时可能危及生命；它和食物不耐受不同，不耐受通常不引起过敏性休克。",
    overview: ["医学诊断和紧急处理方案需要由过敏专科负责。营养师可以帮助看标签、预防交叉接触、补上被删食物的营养，并让学校、餐厅、旅行和家庭聚餐更安全。", "美国包装食品必须清楚标示九大过敏原：奶、蛋、鱼、甲壳类海鲜、树坚果、花生、小麦、大豆和芝麻。配方会改变，所以每次都要重新看标签。"],
    focus: ["学会看标签、隐藏成分和交叉接触，不扩大到没有依据的禁食。", "奶、蛋、小麦、大豆、坚果等主食被删掉后，补回缺少的营养。", "为餐厅、学校、照顾者、旅行和社区活动准备沟通方式。", "食物激发试验、重新引入和急救药物问题交给过敏医生。"],
    visit: ["了解已经确认的过敏、检查、过去反应、急救计划、药物和所有禁食。", "检查总能量、蛋白质、钙、维生素 D、纤维等是否不够。", "做安全食物清单、交叉接触方案和家里外面的实际餐食。"],
    urgent: ["进食后呼吸困难、喉咙紧、喘鸣、晕倒，或两个以上身体系统同时出现症状。", "怀疑过敏性休克时，按急救计划使用肾上腺素并呼叫急救。", "反复呕吐、荨麻疹快速扩散、肿胀或反应越来越重。"],
    faq: [{ q: "食物过敏和不耐受一样吗？", a: "不一样。过敏涉及免疫系统，可能导致过敏性休克；不耐受通常是消化或其他非免疫症状，需要结合病史和检查区分。" }, { q: "包装上写‘可能含有’就一定不能吃吗？", a: "这类预警标示并不像配料表那样统一。请按过敏医生制定的风险方案处理，不要只靠猜。" }],
  },
};

const metadata = {
  "weight-loss": { image: en["weight-loss"].image, imageAlt: en["weight-loss"].imageAlt, sources: en["weight-loss"].sources, related: en["weight-loss"].related },
  glp1: { image: en.glp1.image, imageAlt: en.glp1.imageAlt, sources: en.glp1.sources, related: en.glp1.related },
  "medical-weight-loss": { image: en["medical-weight-loss"].image, imageAlt: en["medical-weight-loss"].imageAlt, sources: en["medical-weight-loss"].sources, related: en["medical-weight-loss"].related },
  pcos: { image: en.pcos.image, imageAlt: en.pcos.imageAlt, sources: en.pcos.sources, related: en.pcos.related },
  "thyroid-health": { image: en["thyroid-health"].image, imageAlt: en["thyroid-health"].imageAlt, sources: en["thyroid-health"].sources, related: en["thyroid-health"].related },
  "digestive-health": { image: en["digestive-health"].image, imageAlt: en["digestive-health"].imageAlt, sources: en["digestive-health"].sources, related: en["digestive-health"].related },
  "sports-nutrition": { image: en["sports-nutrition"].image, imageAlt: en["sports-nutrition"].imageAlt, sources: en["sports-nutrition"].sources, related: en["sports-nutrition"].related },
  "menopause-nutrition": { image: en["menopause-nutrition"].image, imageAlt: en["menopause-nutrition"].imageAlt, sources: en["menopause-nutrition"].sources, related: en["menopause-nutrition"].related },
  "heart-health": { image: en["heart-health"].image, imageAlt: en["heart-health"].imageAlt, sources: en["heart-health"].sources, related: en["heart-health"].related },
  "pregnancy-postpartum": { image: en["pregnancy-postpartum"].image, imageAlt: en["pregnancy-postpartum"].imageAlt, sources: en["pregnancy-postpartum"].sources, related: en["pregnancy-postpartum"].related },
  "eating-disorders": { image: en["eating-disorders"].image, imageAlt: en["eating-disorders"].imageAlt, sources: en["eating-disorders"].sources, related: en["eating-disorders"].related },
  "celiac-disease": { image: en["celiac-disease"].image, imageAlt: en["celiac-disease"].imageAlt, sources: en["celiac-disease"].sources, related: en["celiac-disease"].related },
  "kidney-health": { image: en["kidney-health"].image, imageAlt: en["kidney-health"].imageAlt, sources: en["kidney-health"].sources, related: en["kidney-health"].related },
  "cancer-nutrition": { image: en["cancer-nutrition"].image, imageAlt: en["cancer-nutrition"].imageAlt, sources: en["cancer-nutrition"].sources, related: en["cancer-nutrition"].related },
  "high-cholesterol": { image: en["high-cholesterol"].image, imageAlt: en["high-cholesterol"].imageAlt, sources: en["high-cholesterol"].sources, related: en["high-cholesterol"].related },
  "food-allergies": { image: en["food-allergies"].image, imageAlt: en["food-allergies"].imageAlt, sources: en["food-allergies"].sources, related: en["food-allergies"].related },
};

export const conditionSlugs = Object.keys(metadata).filter((slug) => !["weight-loss", "glp1", "medical-weight-loss"].includes(slug));

export const guidePaths = {
  "weight-loss": "/one-to-one-weight-loss",
  glp1: "/glp1-care",
  "medical-weight-loss": "/medical-weight-loss",
  ...Object.fromEntries(conditionSlugs.map((slug) => [slug, `/conditions/${slug}`])),
};

export function getCareGuide(slug, language = "en") {
  if (language.toLowerCase().startsWith("es")) {
    const item = getExpansionContent("es").services.items[slug];
    if (!item || !metadata[slug]) return null;
    return { ...spanishGuide, ...metadata[slug], title: item[0], shortTitle: item[0], intro: item[1], imageAlt: `Orientación nutricional para ${item[0].toLowerCase()}`, locale: "es" };
  }
  const useChinese = language.toLowerCase().startsWith("zh");
  const locale = useChinese ? "zh-CN" : "en";
  const content = useChinese ? zh[slug] : en[slug];
  if (!content || !metadata[slug]) return null;
  return { ...shared[locale], ...metadata[slug], ...content, locale };
}
