import i18n from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";

export const supportedLocales = ["en", "zh-CN", "zh-TW", "es"];

export const localeLabels = {
  en: "English",
  "zh-CN": "简体中文",
  "zh-TW": "繁體中文",
  es: "Español",
};

const resources = {
  en: { translation: {
    language: "Language",
    nav: {
      weight: "Weight Loss", clinical: "Diabetes & Training", insurance: "Insurance",
      team: "Our Team", resources: "Resources", book: "Book a Free Call", menu: "Menu",
      weightIntro: "Personalized care for sustainable weight loss.",
      clinicalIntro: "Education and device training from diabetes specialists.",
      oneToOne: "1:1 Weight Loss", glpCare: "GLP-1 Weight Management", medical: "Medical Weight Loss",
      classes: "Diabetes Classes", pump: "Insulin Pump Training", cgm: "CGM Training & Reports",
      glpTraining: "GLP-1 Medication Training", providers: "For Providers",
      recipes: "Recipes", research: "Research Explained", about: "Meet Our Dietitians"
    },
    home: {
      eyebrow: "1:1 weight loss care · Insurance-friendly",
      title: "Weight loss care built around your health and your life.",
      intro: "Work one-to-one with a registered dietitian on sustainable fat loss, with GLP-1 support and physician oversight available when appropriate.",
      primary: "Book a free consultation", secondary: "Check my insurance",
      trust: "Multilingual care in English, Mandarin, Cantonese, Fuzhounese, Hakka, and Spanish.",
      pathsEyebrow: "Start where you are", pathsTitle: "Three clear paths to better weight care.",
      pathsIntro: "Tell us your goal in one short form. We will match you with the right clinician and verify benefits before care begins.",
      path1Title: "1:1 Weight Loss", path1Text: "A dedicated dietitian for fat loss, meal strategy, accountability, and habits that fit real life.",
      path2Title: "GLP-1 Weight Management", path2Text: "Nutrition support before, during, or after GLP-1 treatment, including protein, hydration, and side-effect planning.",
      path3Title: "Medical Weight Loss", path3Text: "Clinical evaluation and Medical Director oversight when medication or a medical pathway may be appropriate.",
      explore: "Explore care", processEyebrow: "A simple start", processTitle: "Less paperwork. A clearer next step.",
      step1Title: "Tell us what you need", step1Text: "Complete one short appointment request. New and returning patients use the same simple form.",
      step2Title: "We verify and match", step2Text: "Our team reviews your goal, checks insurance, and connects you with the right clinician.",
      step3Title: "Begin your plan", step3Text: "Meet one-to-one and leave with practical next steps tailored to your health and routine.",
      clinicalEyebrow: "More clinical services", clinicalTitle: "Weight loss is our focus. Diabetes expertise strengthens the care around it.",
      clinicalIntro: "Our diabetes specialists also provide structured education, device training, medication training, and referral support.",
      learn: "Learn more", teamEyebrow: "Specialist-led care", teamTitle: "Registered dietitians, supported by medical oversight.",
      teamText: "Our multilingual dietitians bring experience in weight management, diabetes, digestive health, oncology, sports nutrition, intuitive eating, and more.",
      teamLink: "Meet all dietitians", directorTitle: "Medical Director support", directorText: "Leon Katz, MD, provides obesity-medicine leadership, clinical evaluation, and prescribing oversight when needed.",
      finalTitle: "See whether your insurance may cover care.", finalText: "Request a free consultation. We will help identify the right service and verify your benefits.", finalButton: "Check benefits and book"
    },
    insurance: { badge: "Commercial insurance-friendly care", title: "Your plan may cover nutrition visits.", text: "We work with many major commercial insurance plans and verify your individual benefits before care begins.", action: "Check my benefits", note: "Coverage and cost vary by plan and eligibility." },
    about: { eyebrow: "About NutriAll", title: "Nutrition care shaped around the whole person.", intro: "Our registered dietitians connect weight care, diabetes expertise, culture, and daily life in one practical plan.", valuesTitle: "Care that is clinical, practical, and respectful.", value1: "Evidence-based", value1Text: "Recommendations grounded in nutrition science and your health history.", value2: "Made for real life", value2Text: "Plans built around culture, schedule, family, access, and preferences.", value3: "Without shame", value3Text: "Progress and setbacks are information, never a reason for blame.", teamEyebrow: "Our dietitians", teamTitle: "Meet the team behind your care.", teamText: "Our clinicians bring complementary experience across weight management, diabetes, digestive health, oncology, sports nutrition, intuitive eating, and more.", director: "Medical oversight when needed", directorText: "Leon Katz, MD, provides obesity-medicine leadership, clinical evaluation, and prescribing oversight when appropriate.", cta: "Find the right dietitian for you" },
    book: { badge: "Free 15-minute consultation", title: "Start with a quick insurance and care check.", intro: "Tell us when to reach you. We will verify benefits, answer your first questions, and help identify the right service.", short: "One short form", noCommitment: "No commitment", verification: "Insurance verification", whatsapp: "Message us on WhatsApp", starting: "Your starting point", adjust: "We can adjust this when we speak.", request: "Request a call", timeTitle: "Choose a time that works for you.", required: "Required fields help us contact you. Insurance details are optional.", name: "Full name", email: "Email", phone: "Phone", age: "Age", preferred: "Preferred language", selectLanguage: "Select a language", patientQuestion: "Have you worked with NutriAll before?", newPatient: "I'm a new patient", returningPatient: "I'm a returning patient", bestTime: "Best time to reach you", selectTime: "Select a time window", optionalInsurance: "Optional insurance information", insuranceHelp: "Share these details if you would like us to begin checking benefits before we call.", company: "Insurance company", memberId: "Member ID", dob: "Date of birth", submit: "Request my free consultation", submitting: "Submitting...", disclaimer: "By submitting, you authorize NutriAll to contact you about this request. Do not use this form for urgent medical concerns.", error: "We could not submit your request. Please try again or contact us on WhatsApp." },
    weightServices: { eyebrow: "Personalized weight care", help: "How this care helps", process: "What to expect", team: "Your care team", insuranceNote: "Eligible nutrition visits may be covered by commercial insurance. We verify benefits before care begins.", oneToOne: { title: "1:1 Weight Loss", summary: "Fat-loss nutrition built around your health, culture, preferences, and real weekly routine.", points: ["Practical protein and fiber planning", "Meal strategies for work, travel, restaurants, and family", "Support for hunger, plateaus, and consistency", "Accountability without shame or rigid rules"], steps: ["Complete one short consultation request", "Get matched with a registered dietitian", "Build and adjust a repeatable plan"], note: "Your dietitian considers weight history, appetite, medications, movement, sleep, stress, and the barriers that made past plans difficult." }, glpCare: { title: "GLP-1 Weight Management", summary: "Nutrition and clinical support before, during, or after GLP-1 treatment.", points: ["Protein, hydration, fiber, and meal pacing", "Injection or oral medication routines", "Planning for nausea, constipation, and appetite changes", "Questions and symptom tracking for your prescriber"], steps: ["Review your medication stage and goals", "Create a symptom-aware nutrition plan", "Adjust support as appetite and doses change"], note: "Medication requires individualized clinical evaluation. Product choice, prescription, availability, and coverage are not guaranteed." }, medical: { title: "Medical Weight Loss", summary: "A coordinated pathway combining obesity-medicine evaluation with one-to-one nutrition care.", points: ["Medical and weight-history review", "Medication, lab, and risk context", "Personalized nutrition assessment", "Ongoing physician and dietitian follow-up"], steps: ["Start with a short care request", "Meet the appropriate clinician", "Begin with clear medical and nutrition priorities"], note: "Prescription treatment is offered only when clinically appropriate. Individual results vary and no medication or amount of weight loss is guaranteed." }, insurance: { title: "Insurance & Cost", summary: "Understand potential coverage before care begins.", points: ["Medical visit network and cost rules", "Registered dietitian benefits and visit limits", "Referral or prior authorization requirements", "Medication coverage checked separately"], steps: ["Share optional insurance details", "We review the benefits relevant to your service", "You receive a clearer next step before booking care"], note: "Coverage and out-of-pocket cost vary by plan, network, diagnosis, eligibility, and location." } },
    services: {
      eyebrow: "Specialist diabetes care", appointment: "Request an appointment", what: "What we help you with", expect: "What to expect", insurance: "Many eligible visits may be covered by commercial insurance. We verify benefits before care begins.",
      classes: { title: "Diabetes Classes", summary: "Structured diabetes education for food, medication, exercise, monitoring, and daily routines.", points: ["Understanding diabetes and blood glucose", "Food, carbohydrates, and meal planning", "Medication, activity, and risk reduction", "Problem solving and sustainable routines"], steps: ["Education led by diabetes-focused dietitians", "Practical lessons you can apply at home", "Multilingual support and culturally responsive care"] },
      pump: { title: "Insulin Pump Training", summary: "Hands-on setup and confidence building for modern insulin pump systems.", points: ["Pump readiness and system setup", "Infusion sites, cartridges, and supplies", "Bolus, basal, alerts, and safety features", "Troubleshooting and daily confidence"], steps: ["Bring your prescribed device and supplies", "Train one-to-one with a diabetes specialist", "Leave with clear safety and follow-up steps"] },
      cgm: { title: "CGM Training & Reports", summary: "Sensor setup, app support, and glucose pattern interpretation that turns data into useful action.", points: ["Sensor placement and app connection", "Alerts, trend arrows, and time in range", "AGP report review", "Food, activity, and medication pattern insights"], steps: ["Support for major CGM systems", "Reports explained in plain language", "Shareable insights for your medical team"] },
      glpTraining: { title: "GLP-1 Medication Training", summary: "Practical training for injectable and oral GLP-1 medications, including technique and side-effect planning.", points: ["Injection technique and medication routines", "Storage, travel, and missed-dose questions", "Protein, hydration, and meal planning", "Nausea, constipation, and symptom planning"], steps: ["Understand how to use your prescribed medication", "Know what to monitor and when to call your prescriber", "Build nutrition routines that support treatment"] },
      providers: { title: "For Providers", summary: "Referral resources and diabetes education support for clinics and care teams.", points: ["Diabetes self-management education", "Medical nutrition therapy", "Pump, CGM, and medication training", "Clear communication back to the referring team"], steps: ["Refer patients who need more education time", "Give patients multilingual, culturally responsive support", "Extend your clinic's diabetes education capacity"] }
    },
    footer: { note: "One-to-one weight loss, GLP-1 support, diabetes education, and medical oversight when needed.", copyright: "NutriAll Wellness. All rights reserved." },
    mobileCta: "Book free call"
  } },
  "zh-CN": { translation: {
    language: "语言",
    nav: { weight: "减重服务", clinical: "糖尿病与培训", insurance: "保险", team: "营养师团队", resources: "健康资源", book: "免费预约咨询", menu: "菜单", weightIntro: "以长期可持续减重为目标的一对一服务。", clinicalIntro: "由糖尿病专业人员提供教育与设备培训。", oneToOne: "1对1减重", glpCare: "GLP-1 减重管理", medical: "医学减重", classes: "糖尿病课程", pump: "胰岛素泵培训", cgm: "CGM 培训与报告", glpTraining: "GLP-1 用药培训", providers: "医疗机构转诊", recipes: "健康食谱", research: "研究解读", about: "认识营养师" },
    home: { eyebrow: "1对1减重服务 · 支持商业保险", title: "真正适合你的健康与生活的减重方案。", intro: "由注册营养师一对一帮助你长期减脂；需要时可配合 GLP-1 营养支持及医生监督。", primary: "免费预约咨询", secondary: "查询保险", trust: "提供英语、普通话、粤语、福州话、客家话及西班牙语服务。", pathsEyebrow: "从适合你的方式开始", pathsTitle: "三条清晰的减重路径。", pathsIntro: "只需填写一份简短表单，我们会匹配合适的专业人员，并在服务开始前核实保险福利。", path1Title: "1对1减重", path1Text: "专属营养师帮助减脂、饮食规划、持续跟进，并建立适合真实生活的习惯。", path2Title: "GLP-1 减重管理", path2Text: "在 GLP-1 治疗前、中、后提供蛋白质、补水、饮食及副作用管理支持。", path3Title: "医学减重", path3Text: "如药物或医学方案适合你，可安排临床评估及 Medical Director 监督。", explore: "了解服务", processEyebrow: "简单开始", processTitle: "少一点步骤，更清楚的下一步。", step1Title: "告诉我们你的需求", step1Text: "新老患者都填写同一份简短预约表。", step2Title: "核实保险并匹配", step2Text: "团队会了解目标、核实保险并安排合适的专业人员。", step3Title: "开始专属方案", step3Text: "一对一会面，并获得适合你健康状况与日常生活的行动计划。", clinicalEyebrow: "更多专业服务", clinicalTitle: "我们以减重为重点，也提供完整的糖尿病专业服务。", clinicalIntro: "糖尿病专业团队同时提供系统教育、设备培训、用药培训及转诊支持。", learn: "了解更多", teamEyebrow: "专业团队", teamTitle: "注册营养师服务，并配合医学监督。", teamText: "我们的多语言营养师擅长减重、糖尿病、肠胃健康、肿瘤营养、运动营养、直觉饮食等领域。", teamLink: "查看全部营养师", directorTitle: "Medical Director 支持", directorText: "Leon Katz 医生在需要时提供肥胖医学领导、临床评估及处方监督。", finalTitle: "看看你的保险是否可以报销。", finalText: "免费提交咨询，我们会帮助判断合适的服务并核实保险福利。", finalButton: "查询保险并预约" },
    insurance: { badge: "支持商业保险", title: "你的保险可能涵盖营养咨询。", text: "我们接受多家主流商业保险，并会在服务开始前核实你的具体福利。", action: "查询我的保险", note: "实际报销与费用取决于保险计划及资格。" },
    about: { eyebrow: "关于 NutriAll", title: "从完整的你出发，提供营养照护。", intro: "注册营养师把减重、糖尿病专业知识、文化和日常生活连接成一套实际可行的方案。", valuesTitle: "专业、实用并尊重每个人的服务。", value1: "循证专业", value1Text: "根据营养科学和你的健康状况提供建议。", value2: "适合真实生活", value2Text: "结合文化、时间、家庭、资源与个人偏好制定方案。", value3: "没有羞耻与指责", value3Text: "进步与挫折都是信息，不是责备你的理由。", teamEyebrow: "营养师团队", teamTitle: "认识为你提供服务的团队。", teamText: "团队擅长减重、糖尿病、肠胃健康、肿瘤营养、运动营养、直觉饮食等领域。", director: "需要时提供医学监督", directorText: "Leon Katz 医生在合适时提供肥胖医学领导、临床评估及处方监督。", cta: "匹配适合你的营养师" },
    book: { badge: "免费15分钟咨询", title: "先做一个简单的保险与服务确认。", intro: "告诉我们方便联系你的时间。我们会核实保险、回答初步问题并帮助选择合适服务。", short: "一份简短表单", noCommitment: "无需承诺", verification: "核实保险", whatsapp: "通过 WhatsApp 联系", starting: "本次咨询方向", adjust: "通话时可以再调整。", request: "申请回电", timeTitle: "选择方便联系你的时间。", required: "必填项用于联系你，保险资料可选填。", name: "姓名", email: "电子邮箱", phone: "电话", age: "年龄", preferred: "首选语言", selectLanguage: "请选择语言", patientQuestion: "你以前是否在 NutriAll 接受过服务？", newPatient: "我是新患者", returningPatient: "我是老患者", bestTime: "最佳联系时间", selectTime: "请选择时间段", optionalInsurance: "选填保险资料", insuranceHelp: "如希望我们提前查询福利，可以填写以下信息。", company: "保险公司", memberId: "会员编号", dob: "出生日期", submit: "申请免费咨询", submitting: "正在提交...", disclaimer: "提交即表示你同意 NutriAll 就本次申请联系你。紧急医疗问题请勿使用此表单。", error: "提交失败，请重试或通过 WhatsApp 联系我们。" },
    weightServices: { eyebrow: "个性化减重服务", help: "这项服务如何帮助你", process: "服务流程", team: "你的专业团队", insuranceNote: "符合条件的营养咨询可能由商业保险报销，我们会在服务前核实福利。", oneToOne: { title: "1对1减重", summary: "根据你的健康、文化、饮食偏好和真实生活节奏制定减脂方案。", points: ["实用的蛋白质与纤维规划", "适用于工作、旅行、外食与家庭饮食的策略", "应对饥饿、平台期与坚持困难", "不羞辱、不依赖僵化规则的跟进"], steps: ["提交一份简短咨询申请", "匹配注册营养师", "制定并持续调整可执行方案"], note: "营养师会综合体重史、食欲、药物、运动、睡眠、压力及过往计划难以坚持的原因。" }, glpCare: { title: "GLP-1 减重管理", summary: "在 GLP-1 治疗前、中、后提供营养及临床支持。", points: ["蛋白质、补水、纤维与进食节奏", "注射或口服药物使用流程", "恶心、便秘与食欲变化规划", "为医生复诊记录问题与症状"], steps: ["了解用药阶段与目标", "制定兼顾症状的营养方案", "随食欲和剂量变化调整支持"], note: "用药需要个体化临床评估，药品选择、处方、供应及保险报销均不保证。" }, medical: { title: "医学减重", summary: "将肥胖医学评估与一对一营养服务结合的协调方案。", points: ["医学史与体重史评估", "药物、化验与风险背景", "个性化营养评估", "医生与营养师持续跟进"], steps: ["提交简短服务申请", "与合适的专业人员会面", "明确医学与营养优先事项"], note: "只有临床上合适时才会提供处方治疗。个人结果不同，不保证药物或具体减重幅度。" }, insurance: { title: "保险与费用", summary: "在开始服务前了解可能的保险报销。", points: ["医疗就诊网络及费用规则", "注册营养师福利与次数限制", "转诊或预授权要求", "药物报销需单独核实"], steps: ["可选填写保险资料", "核实与你所需服务相关的福利", "预约前获得更清楚的下一步"], note: "实际报销和自付费用取决于保险计划、网络、诊断、资格及所在地。" } },
    services: { eyebrow: "糖尿病专业服务", appointment: "预约咨询", what: "我们可以帮助你", expect: "服务流程", insurance: "符合条件的服务可能由商业保险报销，我们会提前核实。", classes: { title: "糖尿病课程", summary: "系统学习饮食、药物、运动、监测与日常管理。", points: ["了解糖尿病与血糖", "碳水化合物与饮食规划", "药物、运动与风险管理", "问题解决与可持续习惯"], steps: ["由糖尿病专业营养师授课", "内容实用，可直接用于日常生活", "提供多语言及文化适配支持"] }, pump: { title: "胰岛素泵培训", summary: "现代胰岛素泵的实际操作、设置与安全使用培训。", points: ["使用准备与系统设置", "输注部位、储药仓与耗材", "基础率、追加剂量、警报与安全", "故障排查与日常使用"], steps: ["携带已开具的设备与耗材", "与糖尿病专业人员一对一培训", "带着清晰的安全及跟进方案离开"] }, cgm: { title: "CGM 培训与报告", summary: "连续血糖监测设备设置、App 支持及血糖趋势解读。", points: ["传感器佩戴与 App 连接", "警报、趋势箭头及目标范围时间", "AGP 报告解读", "饮食、活动与药物模式分析"], steps: ["支持主流 CGM 系统", "用易懂语言解释报告", "提供可与医疗团队共享的要点"] }, glpTraining: { title: "GLP-1 用药培训", summary: "针对注射及口服 GLP-1 药物的使用、储存和副作用规划。", points: ["注射方法与用药流程", "储存、旅行及漏服处理", "蛋白质、补水与饮食规划", "恶心、便秘等症状管理"], steps: ["正确使用医生开具的药物", "知道要观察什么及何时联系医生", "建立支持治疗的营养习惯"] }, providers: { title: "医疗机构转诊", summary: "为诊所及医疗团队提供转诊、糖尿病教育与培训支持。", points: ["糖尿病自我管理教育", "医学营养治疗", "泵、CGM 及用药培训", "向转诊团队清晰反馈"], steps: ["转诊需要更多教育时间的患者", "提供多语言及文化适配支持", "扩充诊所的糖尿病教育能力"] } },
    footer: { note: "1对1减重、GLP-1 支持、糖尿病教育，以及需要时的医学监督。", copyright: "NutriAll Wellness。保留所有权利。" }, mobileCta: "免费预约"
  } },
};

// Traditional Chinese and Spanish keep the same clinical structure while translating
// every navigation and conversion-critical message.
resources["zh-TW"] = { translation: JSON.parse(JSON.stringify(resources["zh-CN"].translation)) };
Object.assign(resources["zh-TW"].translation, {
  language: "語言",
  nav: { ...resources["zh-CN"].translation.nav, weight: "減重服務", clinical: "糖尿病與培訓", insurance: "保險", team: "營養師團隊", resources: "健康資源", book: "免費預約諮詢", menu: "選單", oneToOne: "1對1減重", pump: "胰島素幫浦培訓", cgm: "CGM 培訓與報告", glpTraining: "GLP-1 用藥培訓", providers: "醫療機構轉介", recipes: "健康食譜", research: "研究解讀", about: "認識營養師" },
  home: { ...resources["zh-CN"].translation.home, title: "真正適合你的健康與生活的減重方案。", primary: "免費預約諮詢", secondary: "查詢保險", pathsTitle: "三條清晰的減重路徑。", processTitle: "少一點步驟，更清楚的下一步。", clinicalTitle: "我們以減重為重點，也提供完整的糖尿病專業服務。", teamTitle: "註冊營養師服務，並配合醫學監督。", finalTitle: "看看你的保險是否可以報銷。", finalButton: "查詢保險並預約" },
  insurance: { badge: "支援商業保險", title: "你的保險可能涵蓋營養諮詢。", text: "我們接受多家主流商業保險，並會在服務開始前核實你的具體福利。", action: "查詢我的保險", note: "實際報銷與費用取決於保險計畫及資格。" },
  footer: { note: "1對1減重、GLP-1 支援、糖尿病教育，以及需要時的醫學監督。", copyright: "NutriAll Wellness。保留所有權利。" }, mobileCta: "免費預約"
});

resources.es = { translation: {
  language: "Idioma",
  nav: { weight: "Pérdida de peso", clinical: "Diabetes y capacitación", insurance: "Seguro", team: "Nuestro equipo", resources: "Recursos", book: "Consulta gratuita", menu: "Menú", weightIntro: "Atención personalizada para una pérdida de peso sostenible.", clinicalIntro: "Educación y capacitación en dispositivos por especialistas.", oneToOne: "Pérdida de peso 1:1", glpCare: "Control de peso con GLP-1", medical: "Pérdida de peso médica", classes: "Clases de diabetes", pump: "Capacitación en bomba", cgm: "CGM e informes", glpTraining: "Capacitación en GLP-1", providers: "Para proveedores", recipes: "Recetas", research: "Investigación explicada", about: "Conozca a las dietistas" },
  home: { eyebrow: "Atención 1:1 · Aceptamos seguros comerciales", title: "Atención para bajar de peso adaptada a su salud y a su vida.", intro: "Trabaje individualmente con una dietista registrada para perder grasa de forma sostenible, con apoyo para GLP-1 y supervisión médica cuando corresponda.", primary: "Reservar consulta gratuita", secondary: "Verificar mi seguro", trust: "Atención multilingüe en inglés, mandarín, cantonés, fuzhounés, hakka y español.", pathsEyebrow: "Empiece donde está", pathsTitle: "Tres caminos claros para un mejor control de peso.", pathsIntro: "Cuéntenos su objetivo en un formulario breve. Le asignaremos el profesional adecuado y verificaremos sus beneficios.", path1Title: "Pérdida de peso 1:1", path1Text: "Una dietista dedicada a la pérdida de grasa, alimentación, seguimiento y hábitos para la vida real.", path2Title: "Control de peso con GLP-1", path2Text: "Apoyo nutricional antes, durante o después de GLP-1, incluyendo proteína, hidratación y efectos secundarios.", path3Title: "Pérdida de peso médica", path3Text: "Evaluación clínica y supervisión del Director Médico cuando un tratamiento médico sea apropiado.", explore: "Ver servicio", processEyebrow: "Un comienzo sencillo", processTitle: "Menos trámites. Un siguiente paso claro.", step1Title: "Cuéntenos qué necesita", step1Text: "Pacientes nuevos y actuales usan el mismo formulario breve.", step2Title: "Verificamos y asignamos", step2Text: "Revisamos su objetivo, verificamos el seguro y buscamos al profesional adecuado.", step3Title: "Comience su plan", step3Text: "Reúnase individualmente y reciba pasos prácticos adaptados a su salud y rutina.", clinicalEyebrow: "Más servicios clínicos", clinicalTitle: "Nos enfocamos en el peso y ofrecemos experiencia completa en diabetes.", clinicalIntro: "Nuestros especialistas también ofrecen educación, capacitación en dispositivos y medicamentos, y apoyo para referidos.", learn: "Más información", teamEyebrow: "Atención especializada", teamTitle: "Dietistas registradas con respaldo médico.", teamText: "Nuestro equipo multilingüe aporta experiencia en peso, diabetes, salud digestiva, oncología, deporte, alimentación intuitiva y más.", teamLink: "Conocer al equipo", directorTitle: "Apoyo del Director Médico", directorText: "Leon Katz, MD, brinda liderazgo en medicina de la obesidad, evaluación clínica y supervisión de prescripción cuando es necesario.", finalTitle: "Averigüe si su seguro puede cubrir la atención.", finalText: "Solicite una consulta gratuita. Le ayudaremos a elegir el servicio y verificar beneficios.", finalButton: "Verificar y reservar" },
  insurance: { badge: "Aceptamos seguros comerciales", title: "Su plan puede cubrir las visitas de nutrición.", text: "Trabajamos con muchos seguros comerciales y verificamos sus beneficios antes de comenzar.", action: "Verificar beneficios", note: "La cobertura y el costo varían según el plan y la elegibilidad." },
  about: { eyebrow: "Acerca de NutriAll", title: "Nutrición centrada en la persona completa.", intro: "Nuestras dietistas conectan el control de peso, la experiencia en diabetes, la cultura y la vida diaria en un plan práctico.", valuesTitle: "Atención clínica, práctica y respetuosa.", value1: "Basada en evidencia", value1Text: "Recomendaciones según la ciencia y su historial de salud.", value2: "Para la vida real", value2Text: "Planes adaptados a cultura, horario, familia, acceso y preferencias.", value3: "Sin vergüenza", value3Text: "El progreso y los contratiempos son información, nunca motivo de culpa.", teamEyebrow: "Nuestras dietistas", teamTitle: "Conozca al equipo que le atiende.", teamText: "El equipo aporta experiencia en peso, diabetes, salud digestiva, oncología, deporte, alimentación intuitiva y más.", director: "Supervisión médica cuando se necesita", directorText: "Leon Katz, MD, brinda liderazgo en medicina de obesidad, evaluación clínica y supervisión de prescripción cuando corresponde.", cta: "Encuentre la dietista adecuada" },
  book: { badge: "Consulta gratuita de 15 minutos", title: "Comience con una breve revisión de seguro y atención.", intro: "Díganos cuándo llamarle. Verificaremos beneficios, responderemos preguntas y le ayudaremos a elegir el servicio.", short: "Un formulario breve", noCommitment: "Sin compromiso", verification: "Verificación de seguro", whatsapp: "Escríbanos por WhatsApp", starting: "Punto de partida", adjust: "Podemos ajustarlo durante la llamada.", request: "Solicitar llamada", timeTitle: "Elija un horario conveniente.", required: "Los campos obligatorios nos ayudan a contactarle. El seguro es opcional.", name: "Nombre completo", email: "Correo electrónico", phone: "Teléfono", age: "Edad", preferred: "Idioma preferido", selectLanguage: "Seleccione un idioma", patientQuestion: "¿Ha recibido atención de NutriAll antes?", newPatient: "Soy paciente nuevo", returningPatient: "Soy paciente actual", bestTime: "Mejor horario para llamar", selectTime: "Seleccione un horario", optionalInsurance: "Información opcional del seguro", insuranceHelp: "Comparta estos datos si desea que verifiquemos beneficios antes de llamar.", company: "Compañía de seguro", memberId: "ID de miembro", dob: "Fecha de nacimiento", submit: "Solicitar consulta gratuita", submitting: "Enviando...", disclaimer: "Al enviar, autoriza a NutriAll a contactarle. No use este formulario para urgencias médicas.", error: "No pudimos enviar su solicitud. Intente de nuevo o contáctenos por WhatsApp." },
  weightServices: { eyebrow: "Atención personalizada para el peso", help: "Cómo le ayuda esta atención", process: "Qué puede esperar", team: "Su equipo", insuranceNote: "Las visitas de nutrición elegibles pueden estar cubiertas por un seguro comercial. Verificamos beneficios antes de comenzar.", oneToOne: { title: "Pérdida de peso 1:1", summary: "Nutrición para perder grasa adaptada a su salud, cultura, preferencias y rutina real.", points: ["Plan práctico de proteína y fibra", "Estrategias para trabajo, viajes, restaurantes y familia", "Apoyo para hambre, estancamientos y constancia", "Seguimiento sin vergüenza ni reglas rígidas"], steps: ["Complete una solicitud breve", "Le asignamos una dietista registrada", "Cree y ajuste un plan repetible"], note: "Su dietista considera historial de peso, apetito, medicamentos, movimiento, sueño, estrés y barreras previas." }, glpCare: { title: "Control de peso con GLP-1", summary: "Apoyo nutricional y clínico antes, durante o después del tratamiento GLP-1.", points: ["Proteína, hidratación, fibra y ritmo de comidas", "Rutinas de medicamentos inyectables u orales", "Plan para náuseas, estreñimiento y apetito", "Preguntas y registro de síntomas para su médico"], steps: ["Revise su etapa y objetivos", "Cree un plan sensible a síntomas", "Ajuste el apoyo con cambios de apetito y dosis"], note: "El medicamento requiere evaluación clínica individual. No se garantizan producto, receta, disponibilidad ni cobertura." }, medical: { title: "Pérdida de peso médica", summary: "Una vía coordinada que combina evaluación médica de obesidad y nutrición individual.", points: ["Revisión médica y del historial de peso", "Contexto de medicamentos, laboratorios y riesgos", "Evaluación nutricional personalizada", "Seguimiento médico y nutricional"], steps: ["Envíe una solicitud breve", "Reúnase con el profesional adecuado", "Comience con prioridades claras"], note: "El tratamiento con receta solo se ofrece cuando es clínicamente apropiado. Los resultados varían y no se garantiza una pérdida específica." }, insurance: { title: "Seguro y costo", summary: "Comprenda la posible cobertura antes de comenzar.", points: ["Red y costos de visitas médicas", "Beneficios y límites de nutrición", "Requisitos de referido o autorización", "Cobertura de medicamentos por separado"], steps: ["Comparta datos opcionales del seguro", "Revisamos los beneficios relevantes", "Reciba un siguiente paso más claro"], note: "La cobertura y el costo dependen del plan, red, diagnóstico, elegibilidad y ubicación." } },
  services: { eyebrow: "Atención especializada en diabetes", appointment: "Solicitar una cita", what: "Cómo podemos ayudarle", expect: "Qué puede esperar", insurance: "Muchas visitas elegibles pueden estar cubiertas por un seguro comercial. Verificamos los beneficios antes de comenzar.", classes: { title: "Clases de diabetes", summary: "Educación estructurada sobre alimentación, medicamentos, ejercicio, monitoreo y rutinas diarias.", points: ["Comprender la diabetes y la glucosa", "Carbohidratos y planificación de comidas", "Medicamentos, actividad y reducción de riesgos", "Resolución de problemas y rutinas sostenibles"], steps: ["Educación por dietistas especializadas", "Lecciones prácticas para usar en casa", "Apoyo multilingüe y culturalmente sensible"] }, pump: { title: "Capacitación en bomba de insulina", summary: "Configuración práctica y confianza para los sistemas modernos de bomba de insulina.", points: ["Preparación y configuración", "Sitios de infusión y suministros", "Basal, bolos, alertas y seguridad", "Solución de problemas"], steps: ["Traiga su dispositivo recetado", "Capacitación individual con un especialista", "Pasos claros de seguridad y seguimiento"] }, cgm: { title: "Capacitación e informes de CGM", summary: "Configuración del sensor, apoyo con aplicaciones e interpretación de patrones.", points: ["Colocación y conexión", "Alertas, tendencias y tiempo en rango", "Revisión de informes AGP", "Patrones de comida, actividad y medicación"], steps: ["Apoyo para los principales sistemas", "Informes explicados claramente", "Información para compartir con su equipo médico"] }, glpTraining: { title: "Capacitación en medicamentos GLP-1", summary: "Capacitación práctica para medicamentos inyectables y orales, incluyendo técnica y efectos secundarios.", points: ["Técnica de inyección y rutinas", "Almacenamiento, viajes y dosis omitidas", "Proteína, hidratación y comidas", "Plan para náuseas y estreñimiento"], steps: ["Use correctamente su medicamento recetado", "Sepa qué vigilar y cuándo llamar", "Cree rutinas nutricionales de apoyo"] }, providers: { title: "Para proveedores", summary: "Recursos de referidos y apoyo educativo para clínicas y equipos de atención.", points: ["Educación para el autocontrol", "Terapia nutricional médica", "Capacitación en bomba, CGM y medicamentos", "Comunicación con el equipo que refiere"], steps: ["Refiera pacientes que necesitan más educación", "Ofrezca apoyo multilingüe y cultural", "Amplíe la capacidad educativa de su clínica"] } },
  footer: { note: "Pérdida de peso 1:1, apoyo GLP-1, educación en diabetes y supervisión médica cuando se necesita.", copyright: "NutriAll Wellness. Todos los derechos reservados." }, mobileCta: "Consulta gratuita"
} };

i18n.use(LanguageDetector).use(initReactI18next).init({
  resources,
  fallbackLng: "en",
  supportedLngs: supportedLocales,
  load: "currentOnly",
  detection: { order: ["querystring", "localStorage", "navigator", "htmlTag"], lookupQuerystring: "lng", caches: ["localStorage"] },
  interpolation: { escapeValue: false },
  react: { useSuspense: false },
});

export default i18n;
