export const dietitians = [
  {
    name: "Siqian (Cici) Chen, MS, RD, LDN",
    role: "Registered Dietitian / Certified Intuitive Eating Counselor",
    image: "team/siqian-chen-studio.jpg",
    imageAlt: "Siqian Cici Chen, registered dietitian",
    imagePosition: "center",
    bio: [
      "Cici earned her Master of Science in Nutrition from CUNY and completed her dietetic internship at Hunter College. Her work centers on weight management, eating disorders, intuitive eating, and mental health.",
      "She helps clients build a healthier relationship with food without weight stigma, combining evidence-based nutrition with practical, compassionate support.",
    ],
    details: ["English, Mandarin, Fuzhounese", "Weight management / Intuitive eating / Eating disorders"],
  },
  {
    name: "Xiaofang Tan, MS, RD, CDN, CDCES",
    role: "Registered Dietitian / Diabetes Care and Education Specialist",
    image: "team/xiaofang-tan-studio.jpg",
    imageAlt: "Xiaofang Tan, registered dietitian",
    imagePosition: "center",
    bio: [
      "Tan earned her Master of Science in Nutrition and completed her dietetic internship at Northwell Health. She is a practicing Registered Dietitian and Certified Diabetes Care and Education Specialist, as well as a NASM Certified Personal Trainer.",
      "Her professional interests include diabetes management, sports nutrition, gastrointestinal conditions such as IBS and IBD, and women's health.",
    ],
    details: ["English, Cantonese, Mandarin, Hakka", "Diabetes / Sports nutrition / Digestive health"],
  },
  {
    name: "Yue Jin, MS, RD",
    role: "Registered Dietitian / Weight-inclusive Nutrition",
    image: "team/yue-jin-studio.jpg",
    imageAlt: "Yue Jin, registered dietitian",
    imagePosition: "center",
    bio: [
      "Yue earned her Master of Science in Nutrition from Cornell University, where she completed dietetic training with Cornell Sports Nutrition and Strong Memorial Hospital. She also holds bachelor's degrees in Clinical Nutrition and Psychology from the University of California, Davis.",
      "Her specialties include intuitive eating, digestive health, eating disorders, and diabetes through a weight-inclusive, evidence-based lens. Her research background includes obesity, mindful eating, and gut health.",
    ],
    details: ["English, Mandarin", "Intuitive eating / Digestive health / Eating disorders / Diabetes"],
  },
  {
    name: "Ziying Zhang, MS",
    role: "RD-eligible Nutrition Professional",
    image: "team/ziying-studio.jpg",
    imageAlt: "Ziying Zhang, nutrition professional",
    imagePosition: "center",
    bio: [
      "Ziying earned her Master of Science in Nutrition and completed her dietetic internship at Teachers College, Columbia University. She supports culturally diverse populations through evidence-based, client-centered care.",
      "Her professional interests include maternal and child nutrition, gastrointestinal health, and weight management. Her approach emphasizes trust, sustainable change, and preserving the joy of food.",
    ],
    details: ["English, Mandarin", "Maternal and child nutrition / Digestive health / Weight management"],
  },
  {
    name: "Yirao (Rebecca) Wang, RDN, LDN, MPH",
    role: "Registered Dietitian / Diabetes Educator",
    image: "team/yirao-wang-studio.jpg",
    imageAlt: "Yirao Rebecca Wang, registered dietitian and diabetes educator",
    imagePosition: "center",
    bio: [
      "Yirao's path into diabetes care began with her father's diagnosis. She learned that people need more than restriction lists: they need practical guidance, cultural understanding, and support that lets them keep enjoying life.",
      "She completed her MPH and dietetics coursework at New York University, with clinical training at Yale New Haven Hospital and long-term care rotations in Florida. She now supports older adults with diabetes and chronic disease management.",
      "Yirao also leads development of culturally tailored diabetes education for Asian communities, with a focus on reducing language barriers and making care more accessible and sustainable.",
    ],
    details: ["Diabetes / Chronic disease management", "Culturally tailored education"],
  },
  {
    name: "Jinhui Zhou, MS, RD, CDN, CDCES",
    role: "Registered Dietitian / Certified Diabetes Care and Education Specialist",
    image: "team/jinhui-zhou-studio.jpg",
    imageAlt: "Jinhui Zhou, registered dietitian and certified diabetes care and education specialist",
    imagePosition: "center",
    bio: [
      "Jinhui helps people manage diabetes in a realistic and sustainable way. Her approach simplifies nutrition information, builds confidence around eating, and turns blood-sugar goals into habits that fit daily routines and culture.",
      "She is especially focused on making food and blood-sugar management feel less overwhelming while giving clients practical tools they can continue using between visits.",
    ],
    details: ["English, Mandarin", "Diabetes / Weight management / Sustainable habits"],
  },
];
