export const dietitians = [
  {
    name: "Siqian (Cici) Chen, MS, RD, LDN",
    role: "Registered Dietitian / Certified Intuitive Eating Counselor",
    image: "team/siqian-chen-studio.jpg",
    imageAlt: "Siqian Cici Chen, registered dietitian",
    imagePosition: "center",
    bio: [
      "Cici earned her Master of Science in Nutrition from CUNY and completed her dietetic internship at Hunter College. Her work centers on weight management, eating disorders, intuitive eating, and mental health.",
      "She helps clients build a healthier relationship with food without weight stigma, combining evidence-based nutrition with practical, compassionate support.",
    ],
    details: ["English, Mandarin, Fuzhounese", "Weight management / Intuitive eating / Eating disorders"],
  },
  {
    name: "Xiaofang Tan, MS, RD, CDN, CDCES",
    role: "Registered Dietitian / Diabetes Care and Education Specialist",
    image: "team/xiaofang-tan-studio.jpg",
    imageAlt: "Xiaofang Tan, registered dietitian",
    imagePosition: "center",
    bio: [
      "Tan earned her Master of Science in Nutrition and completed her dietetic internship at Northwell Health. She is a practicing Registered Dietitian and Certified Diabetes Care and Education Specialist, as well as a NASM Certified Personal Trainer.",
      "Her professional interests include diabetes management, sports nutrition, gastrointestinal conditions such as IBS and IBD, and women's health.",
    ],
    details: ["English, Cantonese, Mandarin, Hakka", "Diabetes / Sports nutrition / Digestive health"],
  },
  {
    name: "Lisa Van Leeuwen, MS, RDN, LDN",
    role: "Trauma-informed Registered Dietitian Nutritionist",
    image: "team/lisa-van-leeuwen-studio.jpg",
    imageAlt: "Lisa Van Leeuwen, registered dietitian nutritionist",
    imagePosition: "center",
    bio: [
      "Lisa earned her Bachelor of Science in Foods and Nutrition from San Diego State University and her Master of Science in Nutrition and Health Promotion, with an eating disorders concentration, from Simmons University.",
      "Her background includes dietetic training and work in inpatient, residential, and partial-hospitalization eating-disorder care. She also completed CBT-E training through the University of Oxford and specialized trauma-informed training.",
      "Her interests include eating disorders and disordered eating, religious trauma, LGBTQIA+ care, mental health, intuitive eating, and sports nutrition.",
    ],
    details: ["English", "Eating disorders / Trauma-informed care / Intuitive eating"],
  },
  {
    name: "Ziying",
    role: "Registered Dietitian / Diabetes Educator",
    image: "team/ziying-studio.jpg",
    imageAlt: "Ziying, registered dietitian and diabetes educator",
    imagePosition: "center",
    bio: [
      "Ziying has supported people across hospitals, medical centers, and private practice. That experience showed her that many people are not short on effort; they need guidance that fits their food, schedule, culture, and real life.",
      "She co-led development of a Diabetes Self-Management Education program designed to make diabetes care more realistic, approachable, and sustainable while helping people enjoy food and life.",
    ],
    details: ["Diabetes self-management education", "Culturally responsive nutrition care"],
  },
  {
    name: "Yirao (Rebecca) Wang, RDN, LDN, MPH",
    role: "Registered Dietitian / Diabetes Educator",
    image: "team/yirao-wang-studio.jpg",
    imageAlt: "Yirao Rebecca Wang, registered dietitian and diabetes educator",
    imagePosition: "center",
    bio: [
      "Yirao's path into diabetes care began with her father's diagnosis. She learned that people need more than restriction lists: they need practical guidance, cultural understanding, and support that lets them keep enjoying life.",
      "She completed her MPH and dietetics coursework at New York University, with clinical training at Yale New Haven Hospital and long-term care rotations in Florida. She now supports older adults with diabetes and chronic disease management.",
      "Yirao also leads development of culturally tailored diabetes education for Asian communities, with a focus on reducing language barriers and making care more accessible and sustainable.",
    ],
    details: ["Diabetes / Chronic disease management", "Culturally tailored education"],
  },
  {
    name: "Jinhui Zhou, MS, RD, CDN, CDCES",
    role: "Registered Dietitian / Certified Diabetes Care and Education Specialist",
    image: "team/jinhui-zhou-studio.jpg",
    imageAlt: "Jinhui Zhou, registered dietitian and certified diabetes care and education specialist",
    imagePosition: "center",
    bio: [
      "Jinhui helps people manage diabetes in a realistic and sustainable way. Her approach simplifies nutrition information, builds confidence around eating, and turns blood-sugar goals into habits that fit daily routines and culture.",
      "She is especially focused on making food and blood-sugar management feel less overwhelming while giving clients practical tools they can continue using between visits.",
    ],
    details: ["English, Mandarin", "Diabetes / Weight management / Sustainable habits"],
  },
];
