// Generated from DiabetesCare_Prototype05. Re-run scripts/extract-xt-clinical-content.mjs to sync.
export const xtClinicalContent = {
  "en": {
    "classes": {
      eyebrow: "ADCES-accredited DSME program",
      chineseFirstBadge: "The first Chinese-language accredited DSME course in the U.S.",
      heroTitle: "Diabetes Self-Management Education (DSME)",
      heroSubtitle: "A practical education program that helps you understand diabetes, eat with confidence, stay active, use medications safely, reduce risks, and solve everyday challenges.",
      bookButton: "Book a class",
      viewCurriculumButton: "View curriculum",
      bilingual: "Bilingual: English & Chinese (Mandarin)",
      delivery: "Online & In-Person",
      coverageNote: "Most eligible patients pay $0 with insurance",
      programLabel: "Program format",
      hours: "Structured DSME Program",
      hoursDescription: "Comprehensive diabetes self-management education",
      outcomes: ["Food and lifestyle skills", "Medication and monitoring basics", "Risk reduction and support"],
      credentialEyebrow: "Accredited education and coverage support",
      credentialTitle: "Certified diabetes education that can be reimbursed by insurance",
      credentialIntro: "This program is built for patients who need structured DSME support and practical help navigating referral and benefit verification.",
      credentials: [
        { title: "ADCES DEAP Accredited", desc: "Program-level accreditation supports nationally recognized diabetes education standards." },
        { title: "Certified diabetes expertise", desc: "Education is led with diabetes care, nutrition, medication, technology, and lifestyle experience." },
        { title: "Registered nutrition care", desc: "Dietitian-led nutrition care supports food, lifestyle, glucose patterns, and long-term self-management." },
      ],
      curriculumEyebrow: "Curriculum",
      curriculumTitle: "Six focused sessions for real-life diabetes management",
      curriculumIntro: "The curriculum is built around practical skills patients can use at home, at meals, during activity, and when glucose numbers do not go as expected.",
      sessionLabel: "Session {{number}}",
      curriculum: [
        {
          title: "Understanding Diabetes",
          subtitle: "Diabetes basics and treatment overview",
          topics: ["Type 1, type 2, prediabetes, and gestational diabetes", "Common signs, symptoms, progression, and glucose targets", "How lifestyle, oral medications, injectables, insulin, and monitoring work together"],
        },
        {
          title: "Healthy Eating",
          subtitle: "Food choices, carbohydrates, and meal planning",
          topics: ["Simple vs. complex carbohydrates and common food sources", "Reading nutrition labels and building balanced meals", "Portion awareness, sauces, snacks, alcohol, and restaurant meals"],
        },
        {
          title: "Being Active",
          subtitle: "Safe movement and individualized activity planning",
          topics: ["Benefits of aerobic and resistance activity", "Short after-meal walks, chair yoga, and muscle-building habits", "How to adapt exercise to age, health conditions, and glucose readings"],
        },
        {
          title: "Medications & Monitoring",
          subtitle: "Using medications and checking glucose safely",
          topics: ["Understanding your medication plan, medication names, and common side effects", "Home glucose monitoring, CGM time in range, and meaningful targets", "When to contact your care team and how to prepare for dose adjustments"],
        },
        {
          title: "Reducing Risk",
          subtitle: "Prevention, warning signs, and complication awareness",
          topics: ["Short-term and long-term complications involving eyes, kidneys, nerves, and feet", "Hypoglycemia and hyperglycemia symptoms, treatment steps, and emergency planning", "Preventive care checklists and critical times to see a diabetes care specialist"],
        },
        {
          title: "Coping & Problem Solving",
          subtitle: "Daily confidence, stress support, and real-world decisions",
          topics: ["Diabetes distress, burnout, depression risk, and support systems", "Communication skills for caregivers and family members", "Case studies, sick-day planning, and strategies for unexpected glucose patterns"],
        },
      ],
      instructorsEyebrow: "Teaching team",
      instructorsTitle: "Educators who make diabetes easier to understand",
      instructorsIntro: "Meet the educators supporting the diabetes education program.",
      instructorsReadFullBio: "Read full bio",
      instructorsCloseBio: "Close bio",
      rosterLabel: "Team roster",
      instructors: [
        {
          name: "Ziying",
          role: "Registered Dietitian",
          bio: [
            "Hi, I’m Ziying, a Registered Dietitian.",
            "Through my work across different healthcare settings, I have supported people through different stages of their health journey. One thing that continues to inspire me is how committed people are to improving their health. At the same time, I’ve seen how easy it is to become overwhelmed by food rules, blood sugar numbers, and conflicting advice.",
            "Over time, I realized that most people are not lacking effort. They are lacking guidance that truly fits their real lives. That realization led me into diabetes education.",
            "Building on my experiences in hospitals, medical centers, and private practice, I co-led the development of a Diabetes Self-Management Education (DSME) program focused on making diabetes care more realistic, approachable, and sustainable in daily life.",
            "To me, successful diabetes education is about helping people feel more confident in caring for their health while still being able to enjoy food and life along the way.",
            "If you’re ready to take control of your health, I’m here to support you.",
          ],
          image: "team/ziying.webp",
        },
        {
          name: "Yirao (Rebecca) Wang, RDN, LDN, MPH",
          role: "Registered Dietitian and Diabetes Educator",
          bio: [
            "My journey into diabetes care began with my father’s diabetes diagnosis during my graduate studies abroad. At first, I tried to help by focusing on food restrictions, but I soon realized that people living with diabetes need more than “what not to eat.” They need practical guidance, cultural understanding, and support that helps them continue enjoying life.",
            "This experience inspired me to pursue nutrition and dietetics in the United States. I completed my MPH and DPD coursework at New York University and received clinical training at Yale New Haven Hospital, followed by long-term care rotations in Florida.",
            "Today, I work as a Registered Dietitian and diabetes educator, supporting older adults with diabetes and chronic disease management. I also lead the development of the first culturally tailored DSME program for Asian communities, with the goal of reducing language barriers and making diabetes and nutrition education more accessible, culturally relevant, and sustainable.",
            "At the heart of my work is connection, compassion, and helping people build healthier lives with confidence while maintaining a high quality of life with diabetes.",
          ],
          image: "team/yirao-wang.webp",
        },
        {
          name: "Jinhui Zhou, MS, RD, CDN, CDCES",
          role: "Registered Dietitian and CDCES",
          bio: [
            "Hi everyone, I’m Jinhui, a Registered Dietitian and CDCES. I am passionate about helping people manage diabetes in a realistic and sustainable way.",
            "My interest in diabetes education comes from seeing how overwhelming food and blood sugar management can feel for many people. I enjoy helping patients simplify nutrition information, build confidence around eating, and create healthy habits that fit their daily lives and culture.",
            "I’m excited to be part of the diabetes education program and look forward to supporting our community!",
          ],
          image: "team/jinhui-zhou.webp",
        },
      ],
      testimonialsEyebrow: "Patient feedback",
      testimonialsTitle: "Patients feel more confident after structured diabetes education",
      testimonials: [
        { quote: "The class finally made my numbers make sense. I learned what to change at breakfast and how to talk to my doctor with better questions.", name: "M. Lee", detail: "DSME participant", image: "testimonials/patient-01.webp" },
        { quote: "I was overwhelmed by medications and glucose readings. The sessions gave me a simple plan I could follow with my family.", name: "R. Johnson", detail: "Type 2 diabetes support", image: "testimonials/patient-02.webp" },
        { quote: "The teaching was clear, patient, and practical. I left knowing how to read labels and prevent low blood sugar more safely.", name: "A. Chen", detail: "Bilingual class participant", image: "testimonials/patient-03.webp" },
      ],
      ctaTitle: "Ready to start learning?",
      ctaBody: "Classes are designed for practical, real-life diabetes management. Medicare / Medicaid and many private insurance plans may reimburse eligible DSME services after referral and benefit verification.",
      startEyebrow: "How to get started",
      startTitle: "A clear path from signup to class",
      startIntro: "We help make the administrative steps less confusing so patients can focus on learning.",
      startSteps: [
        { title: "Sign up", desc: "Submit your information or book a class time." },
        { title: "Referral + verification", desc: "We help coordinate referral needs and verify insurance benefits." },
        { title: "Attend class", desc: "Join structured DSME sessions online or in person." },
        { title: "See results", desc: "Apply the skills to food choices, activity, medication routines, and glucose patterns." },
      ],
      disclaimerTitle: "Disclaimer",
      disclaimerBody: "The information and services provided by XT Diabetes Care are intended to help individuals improve their health through food and lifestyle changes. All information is designed to be for educational purposes only. This information is not to be used as a substitute for medical care or advice, diagnosis or treatment. Individuals should talk to a physician or other qualified healthcare professionals with any medical concerns and prior to starting a diet or exercise program.",
      insuranceButton: "View Insurance Info",
      contactButton: "Contact Us",
    },
    "pumpTraining": {
      heroTitle: "Insulin Pump Training",
      heroSubtitle: "Free insulin pump training with no insurance requirement and no physician referral needed. Bring your device, your questions, and leave with confidence.",
      heroBadges: {
        free: "100% Free",
        noInsurance: "No insurance required",
        noReferral: "No referral needed",
      },
      catalogEyebrow: "Pump catalog",
      catalogTitle: "Major pump brands and current systems",
      catalogSubtitle: "Real product images are grouped by manufacturer so patients can compare the devices they may be trained on.",
      productLabel: "product",
      productsLabel: "products",
      sourceLink: "Official product page",
      pumpBrands: [
        {
          brand: "Omnipod",
          summary: "Tubeless Pod therapy with both automated and manual insulin-management options.",
          products: [
            { name: "Omnipod 5", desc: "Tubeless automated insulin delivery system designed to adjust insulin using CGM data.", image: "pumps/omnipod-5.png", tags: ["Tubeless", "AID", "Pod"], sourceUrl: "https://www.omnipod.com/what-is-omnipod/omnipod-5" },
            { name: "Omnipod DASH", desc: "Tubeless insulin management system using a wearable Pod and handheld controller.", image: "pumps/omnipod-dash.png", tags: ["Tubeless", "Pod", "PDM"], sourceUrl: "https://www.omnipod.com/what-is-omnipod/omnipod-dash" },
          ],
        },
        {
          brand: "twiist",
          summary: "Automated insulin delivery built around the FDA-cleared Tidepool Loop algorithm.",
          products: [
            { name: "twiist AID System", desc: "Automated insulin delivery system using Tidepool Loop and the twiist pump platform.", image: "pumps/twiist-aid.png", tags: ["AID", "Tidepool Loop", "300 units"], sourceUrl: "https://www.twiist.com/" },
          ],
        },
        {
          brand: "Beta Bionics",
          summary: "A simplified bionic pancreas system built to automate insulin dosing decisions.",
          products: [
            { name: "iLet Bionic Pancreas", desc: "Starts with body weight and automates insulin dosing decisions through the iLet system.", image: "pumps/ilet-bionic-pancreas.png", tags: ["AID", "Weight-based start", "CGM"], sourceUrl: "https://www.betabionics.com/ilet-bionic-pancreas/" },
          ],
        },
        {
          brand: "Tandem Diabetes Care",
          summary: "Screen-based and mobile-controlled pump systems using Control-IQ technology.",
          products: [
            { name: "Tandem Mobi", desc: "Small durable pump controlled from a compatible smartphone app.", image: "pumps/tandem-mobi.png", tags: ["AID", "Mobile control", "200 units"], sourceUrl: "https://www.tandemdiabetes.com/products/insulin-pumps/tandem-mobi" },
            { name: "t:slim X2", desc: "Touchscreen insulin pump with Control-IQ technology and software updates.", image: "pumps/tandem-tslim-x2.png", tags: ["AID", "Touchscreen", "300 units"], sourceUrl: "https://www.tandemdiabetes.com/products/insulin-pumps/tslim-x2-insulin-pump" },
          ],
        },
        {
          brand: "MiniMed",
          summary: "Medtronic systems built around SmartGuard automation and Guardian sensor integration.",
          products: [
            { name: "MiniMed 780G", desc: "Automated insulin delivery system with SmartGuard technology.", image: "pumps/minimed-780g.png", tags: ["AID", "SmartGuard", "Guardian"], sourceUrl: "https://www.minimed.com/en-us/products/minimed-780g-insulin-pump-system" },
          ],
        },
        {
          brand: "CeQur",
          summary: "Wearable mealtime insulin patch for people who need bolus insulin without a full pump system.",
          products: [
            { name: "CeQur Simplicity", desc: "Four-day wearable insulin patch that delivers mealtime insulin with simple clicks.", image: "pumps/cequr-simplicity.png", tags: ["Bolus patch", "4-day wear", "No electronics"], sourceUrl: "https://myceqursimplicity.com/" },
          ],
        },
      ],
      expectTitle: "What to Expect During Training",
      expectations: [
        "Understanding your pump components and navigation.",
        "Safe site rotation and infusion set insertion.",
        "Programming basal rates, carb ratios, and correction factors based on your doctor's orders.",
        "Troubleshooting alarms and resolving issues.",
      ],
      needTitle: "Need Training?",
      needBody: "This pump training is completely free. No insurance requirement. No referral required. Schedule directly and get hands-on support.",
      scheduleButton: "Schedule Training",
    },
    "cgm": {
      heroTitle: "CGM Training & Report Analysis",
      heroSubtitle: "Unlock the power of your dynamic glucose monitor. We train you how to use it, interpret reports, and help you and your doctor turn data into better decisions.",
      logoAlt: "{{name}} logo",
      officialWebsite: "Official website",
      lingoFallbackDesc: "Support for Abbott Lingo users who want to understand glucose patterns and lifestyle responses.",
      devices: [
        { name: "FreeStyle Libre", maker: "Abbott", logo: "cgm-logos/freestyle-libre-v2.png", desc: "Training on sensor placement, using your smartphone reader, and understanding trend arrows.", sourceUrl: "https://www.freestyle.abbott/us-en/home.html" },
        { name: "Dexcom G7/G6", maker: "Dexcom", logo: "cgm-logos/dexcom-v2.png", desc: "Setup of alerts and alarms, sharing data with family or clinic, and application process.", sourceUrl: "https://www.dexcom.com/" },
        { name: "Stelo", maker: "Dexcom OTC", logo: "cgm-logos/stelo-v2.png", desc: "Guidance for type 2 diabetes patients on interpreting the over-the-counter biosensor data.", sourceUrl: "https://www.stelo.com/" },
        { name: "Lingo", maker: "Abbott", logo: "cgm-logos/lingo-v2.png", desc: "Support for Abbott Lingo users who want to understand glucose patterns and lifestyle responses.", sourceUrl: "https://www.hellolingo.com/" },
      ],
      features: {
        appSetup: "App Setup",
        arrowTrends: "Arrow Trends",
        agpReports: "AGP Reports",
        reportInterpretation: "Report Interpretation",
        timeInRange: "Time in Range",
      },
      beyondTitle: "Beyond Just Numbers",
      beyondIntro: "A CGM provides hundreds of readings a day, but what do you do with them?",
      beyondBody: "We analyze and interpret your Ambulatory Glucose Profile (AGP) reports to identify patterns. We teach you how different foods, stress, and exercise affect your unique body, helping you maximize your <strong>Time In Range</strong> (TIR).",
      scheduleButton: "Schedule Analysis Session",
    },
    "glp1Training": {
      badge: "GLP-1 injectable and oral medication support",
      imageAlt: "Diabetes educator reviewing GLP-1 medication training with a patient",
      heroTitle: "GLP-1 Medication Training",
      heroSubtitle: "Starting medications such as semaglutide, tirzepatide, liraglutide, or other GLP-1 based therapies can raise practical questions. We teach the daily steps, side effect planning, and follow-up habits that make treatment easier to stay with.",
      scheduleButton: "Schedule GLP-1 Training",
      trainingTitle: "What we cover",
      trainingIntro: "Training is educational and coordinated with the prescribing clinician's instructions.",
      topics: [
        { title: "Injection technique", desc: "How to prepare the pen, choose and rotate injection sites, store medication, and dispose of sharps safely." },
        { title: "Oral medication routine", desc: "How to build a consistent routine for oral GLP-1 medication timing, missed-dose questions, and pharmacy instructions." },
        { title: "Food and hydration strategies", desc: "Practical meal pacing, protein, fluid, and portion strategies during appetite changes and dose escalation." },
        { title: "Dose adjustment", desc: "What to track, when to contact the prescribing clinician, and how to prepare questions before dose changes." },
      ],
      sideEffectTitle: "Side effect management",
      sideEffectIntro: "Common GLP-1 side effects are often gastrointestinal. We help patients plan realistic ways to manage symptoms and identify when medical follow-up is needed.",
      sideEffects: [
        "Nausea, fullness, appetite changes, and meal tolerance",
        "Vomiting, diarrhea, constipation, gas, or abdominal discomfort",
        "Low-blood-sugar risk when GLP-1 therapy is used with insulin or sulfonylureas",
        "Red flags that should be escalated to the prescribing medical team",
      ],
    },
    "providers": {
      badge: "ADCES Accredited Diabetes Education Program",
      heroLine1: "Partnering with Physicians",
      heroLine2: "to Improve Patient Outcomes",
      heroSubtitle: "XT Diabetes Care acts as an extension of your practice. We provide the intensive, systemic diabetes self-management education your patients need, completely covered by insurance.",
      values: [
        { title: "Save Your Time", desc: "We take the time-consuming burden of comprehensive diabetes education off your shoulders, freeing you to focus on diagnosis and medication management." },
        { title: "Structured Curriculum", desc: "Patients receive systematic education on medication usage, diet, physical activity, and psychosocial coping skills." },
        { title: "We Keep You Informed", desc: "We act as your assistant, returning comprehensive reports to you and ensuring patients follow up with you regularly for medication adjustments." },
      ],
      referTitle: "How to Refer Your Patients",
      referIntro: "Medicare / Medicaid and private insurance cover our programs, but require a referral from the treating physician.",
      faxLine: "Fax form to us at (888) 370-1981.",
      referralCandidates: [
        "Patients newly diagnosed with diabetes.",
        "Patients who have never received systematic diabetes self-management training.",
        "Patients transitioning to Insulin Pumps or Continuous Glucose Monitors (CGM).",
      ],
      downloadButton: "Download Referral Form Template",
      accreditedTitle: "ADCES Accredited",
      accreditedId: "ID# 1001155",
      accreditedBody: "Having met all applicable standards and requirements of the Association of Diabetes Care & Education Specialists.",
      certificateAlt: "ADCES DEAP certificate",
    }
  },
  "zh-CN": {
    "classes": {
      eyebrow: "ADCES 认证 DSME 项目",
      chineseFirstBadge: "全美首个中文认证 DSME 课程",
      heroTitle: "糖尿病自我管理教育（DSME）",
      heroSubtitle: "实用教育项目，帮助您理解糖尿病、安心饮食、保持活动、安全用药、降低风险，并处理日常挑战。",
      bookButton: "预约课程",
      viewCurriculumButton: "查看课程内容",
      bilingual: "双语：英语和中文（普通话）",
      delivery: "线上与线下",
      coverageNote: "多数符合条件的患者可通过保险 $0 参加",
      programLabel: "项目形式",
      hours: "结构化 DSME 项目",
      hoursDescription: "全面的糖尿病自我管理教育",
      outcomes: ["饮食和生活方式技能", "用药和监测基础", "风险降低和支持"],
      credentialEyebrow: "认证教育与保险支持",
      credentialTitle: "可由保险报销的认证糖尿病教育",
      credentialIntro: "本项目面向需要结构化 DSME 支持的患者，并提供转诊和福利核实方面的实际协助。",
      credentials: [
        { title: "ADCES DEAP 认证", desc: "项目级认证支持全国认可的糖尿病教育标准。" },
        { title: "认证糖尿病专业能力", desc: "教育结合糖尿病护理、营养、用药、技术和生活方式经验。" },
        { title: "注册营养护理", desc: "营养师主导的营养护理支持饮食、生活方式、血糖模式和长期自我管理。" },
      ],
      curriculumEyebrow: "课程大纲",
      curriculumTitle: "六节聚焦真实生活的糖尿病管理课程",
      curriculumIntro: "课程围绕可在家中、用餐时、活动中，以及血糖数字不如预期时使用的实际技能设计。",
      sessionLabel: "第 {{number}} 节",
      curriculum: [
        { title: "理解糖尿病", subtitle: "糖尿病基础和治疗概览", topics: ["1 型、2 型、糖尿病前期和妊娠糖尿病", "常见症状、疾病进展和血糖目标", "生活方式、口服药、注射药物、胰岛素和监测如何配合"] },
        { title: "健康饮食", subtitle: "食物选择、碳水化合物和餐食规划", topics: ["简单与复杂碳水，以及常见食物来源", "阅读营养标签并搭配均衡餐盘", "份量、酱料、点心、酒精和外食场景"] },
        { title: "保持活动", subtitle: "安全运动和个性化活动计划", topics: ["有氧和抗阻运动的益处", "饭后短时间步行、椅子瑜伽和增肌习惯", "根据年龄、健康状况和血糖读数调整运动"] },
        { title: "用药与监测", subtitle: "安全用药和血糖监测", topics: ["理解您的用药计划、药名和常见副作用", "居家血糖监测、动态血糖仪目标范围内时间和实用目标", "何时联系护理团队，以及如何为剂量调整做准备"] },
        { title: "降低风险", subtitle: "预防、警示信号和并发症意识", topics: ["眼睛、肾脏、神经和足部相关的短期与长期并发症", "低血糖和高血糖症状、处理步骤和应急计划", "预防性护理清单，以及何时应看糖尿病护理专家"] },
        { title: "应对与解决问题", subtitle: "日常信心、压力支持和现实决策", topics: ["糖尿病压力、倦怠、抑郁风险和支持系统", "照护者和家庭成员沟通技巧", "案例学习、生病日计划和意外血糖模式应对策略"] },
      ],
      instructorsEyebrow: "教学团队",
      instructorsTitle: "让糖尿病更容易理解的教育者",
      instructorsIntro: "认识支持糖尿病教育项目的教学团队。",
      instructorsReadFullBio: "查看完整介绍",
      instructorsCloseBio: "关闭介绍",
      rosterLabel: "团队名单",
      instructors: [
        {
          name: "Ziying",
          role: "注册营养师",
          bio: [
            "你好，我是 Ziying，一名注册营养师。",
            "在不同医疗环境中的工作经历，让我陪伴过许多人走过健康旅程中的不同阶段。一直激励我的是，人们为了改善健康所投入的认真和坚持。同时，我也看见，饮食规则、血糖数字和彼此冲突的建议，很容易让人感到不知所措。",
            "随着经验累积，我逐渐意识到，大多数人并不是不够努力，而是缺少真正适合现实生活的指导。这个认识让我走进了糖尿病教育。",
            "基于在医院、医疗中心和私人诊所的经验，我共同主导开发了一个糖尿病自我管理教育（DSME）项目，重点是让糖尿病护理在日常生活中更现实、更容易接近，也更可持续。",
            "在我看来，成功的糖尿病教育，是帮助人们在照顾健康时更有信心，同时仍然能够享受食物和生活。",
            "如果你已经准备好主动掌握自己的健康，我会在这里支持你。",
          ],
          image: "team/ziying.webp",
        },
        {
          name: "Yirao (Rebecca) Wang, RDN, LDN, MPH",
          role: "注册营养师及糖尿病教育者",
          bio: [
            "我走进糖尿病护理，源于我在海外读研期间父亲被诊断出糖尿病。起初，我尝试通过饮食限制来帮助他，但很快意识到，糖尿病患者需要的不只是“不能吃什么”。他们需要实用的指导、文化上的理解，以及能帮助他们继续享受生活的支持。",
            "这段经历促使我在美国继续学习营养与膳食学。我在纽约大学完成了 MPH 和 DPD 课程，并在 Yale New Haven Hospital 接受临床培训，之后又在佛罗里达完成长期护理相关轮转。",
            "如今，我作为注册营养师和糖尿病教育者，支持老年糖尿病患者及慢性病管理。我也主导开发面向亚洲社区的首个文化适配型 DSME 项目，目标是减少语言障碍，让糖尿病和营养教育更易获得、更贴近文化，也更可持续。",
            "我工作的核心，是连接、同理心，以及帮助人们带着信心建立更健康的生活，同时在与糖尿病共处时维持良好的生活质量。",
          ],
          image: "team/yirao-wang.webp",
        },
        {
          name: "Jinhui Zhou, MS, RD, CDN, CDCES",
          role: "注册营养师及认证糖尿病护理与教育专家",
          bio: [
            "大家好，我是 Jinhui，一名注册营养师及认证糖尿病护理与教育专家。我热衷于帮助人们用现实、可持续的方式管理糖尿病。",
            "我对糖尿病教育的兴趣，来自看到很多人在面对饮食和血糖管理时感到压力很大。我喜欢帮助患者简化营养信息，建立对饮食的信心，并养成适合自己日常生活和文化背景的健康习惯。",
            "我很高兴加入糖尿病教育项目，也期待为我们的社区提供支持！",
          ],
          image: "team/jinhui-zhou.webp",
        },
      ],
      testimonialsEyebrow: "患者反馈",
      testimonialsTitle: "结构化糖尿病教育让患者更有信心",
      testimonials: [
        { quote: "课程终于让我看懂自己的数字。我学会早餐该调整什么，也知道如何带着更好的问题和医生沟通。", name: "M. Lee", detail: "DSME 参与者", image: "testimonials/patient-01.webp" },
        { quote: "药物和血糖读数曾让我非常焦虑。课程给了我一个能和家人一起执行的简单计划。", name: "R. Johnson", detail: "2 型糖尿病支持", image: "testimonials/patient-02.webp" },
        { quote: "教学清楚、耐心又实用。结束时我知道如何读标签，也更安全地预防低血糖。", name: "A. Chen", detail: "双语课程参与者", image: "testimonials/patient-03.webp" },
      ],
      ctaTitle: "准备开始学习了吗？",
      ctaBody: "课程为真实生活中的糖尿病管理而设计。转诊和福利核实后，Medicare / Medicaid 以及许多商业保险可能报销符合条件的 DSME 服务。",
      startEyebrow: "如何开始",
      startTitle: "从报名到上课的清晰流程",
      startIntro: "我们协助简化行政步骤，让患者专注于学习。",
      startSteps: [
        { title: "报名", desc: "提交信息或预约课程时间。" },
        { title: "转诊 + 核实", desc: "我们协助处理转诊需求并核实保险福利。" },
        { title: "参加课程", desc: "线上或线下参加结构化 DSME 课程。" },
        { title: "看到结果", desc: "把技能应用到食物选择、活动、用药流程和血糖模式中。" },
      ],
      disclaimerTitle: "免责声明",
      disclaimerBody: "XT Diabetes Care 提供的信息和服务旨在帮助个人通过饮食和生活方式改变改善健康。所有信息仅用于教育目的，不应替代医疗护理、建议、诊断或治疗。如有任何医疗问题，或在开始饮食或运动计划前，请咨询医生或其他合格医疗专业人员。",
      insuranceButton: "查看保险信息",
      contactButton: "联系我们",
    },
    "pumpTraining": {
      heroTitle: "胰岛素泵培训",
      heroSubtitle: "免费胰岛素泵培训，无需保险要求，也无需医生转诊。带上您的设备和问题，带着信心离开。",
      heroBadges: { free: "100% 免费", noInsurance: "无需保险", noReferral: "无需转诊" },
      catalogEyebrow: "胰岛素泵目录",
      catalogTitle: "主要胰岛素泵品牌和当前系统",
      catalogSubtitle: "真实产品图片按厂家分组，方便患者比较可能接受培训的设备。",
      productLabel: "款产品",
      productsLabel: "款产品",
      sourceLink: "官方产品页面",
      pumpBrands: [
        { brand: "Omnipod", summary: "无管 Pod 治疗，提供自动和手动胰岛素管理选项。", products: [
          { name: "Omnipod 5", desc: "无管自动胰岛素输送系统，可根据动态血糖仪数据调整胰岛素。", image: "pumps/omnipod-5.png", tags: ["无管", "AID", "Pod"], sourceUrl: "https://www.omnipod.com/what-is-omnipod/omnipod-5" },
          { name: "Omnipod DASH", desc: "使用可穿戴 Pod 和手持控制器的无管胰岛素管理系统。", image: "pumps/omnipod-dash.png", tags: ["无管", "Pod", "PDM"], sourceUrl: "https://www.omnipod.com/what-is-omnipod/omnipod-dash" },
        ] },
        { brand: "twiist", summary: "基于已获 FDA 批准的 Tidepool Loop 算法进行自动胰岛素输送。", products: [
          { name: "twiist AID System", desc: "使用 Tidepool Loop 和 twiist 泵平台的自动胰岛素输送系统。", image: "pumps/twiist-aid.png", tags: ["AID", "Tidepool Loop", "300 单位"], sourceUrl: "https://www.twiist.com/" },
        ] },
        { brand: "Beta Bionics", summary: "简化型仿生胰腺系统，用于自动化胰岛素剂量决策。", products: [
          { name: "iLet Bionic Pancreas", desc: "以体重作为起点，通过 iLet 系统自动化胰岛素剂量决策。", image: "pumps/ilet-bionic-pancreas.png", tags: ["AID", "体重起始", "动态血糖仪"], sourceUrl: "https://www.betabionics.com/ilet-bionic-pancreas/" },
        ] },
        { brand: "Tandem Diabetes Care", summary: "使用 Control-IQ 技术的屏幕式和手机控制泵系统。", products: [
          { name: "Tandem Mobi", desc: "可通过兼容手机应用控制的小型耐用泵。", image: "pumps/tandem-mobi.png", tags: ["AID", "手机控制", "200 单位"], sourceUrl: "https://www.tandemdiabetes.com/products/insulin-pumps/tandem-mobi" },
          { name: "t:slim X2", desc: "带触摸屏、Control-IQ 技术和软件更新功能的胰岛素泵。", image: "pumps/tandem-tslim-x2.png", tags: ["AID", "触摸屏", "300 单位"], sourceUrl: "https://www.tandemdiabetes.com/products/insulin-pumps/tslim-x2-insulin-pump" },
        ] },
        { brand: "MiniMed", summary: "Medtronic 系统，围绕 SmartGuard 自动化和 Guardian 传感器整合构建。", products: [
          { name: "MiniMed 780G", desc: "配备 SmartGuard 技术的自动胰岛素输送系统。", image: "pumps/minimed-780g.png", tags: ["AID", "SmartGuard", "Guardian"], sourceUrl: "https://www.minimed.com/en-us/products/minimed-780g-insulin-pump-system" },
        ] },
        { brand: "CeQur", summary: "餐时胰岛素可穿戴贴片，适合需要餐时胰岛素但不需要完整泵系统的人。", products: [
          { name: "CeQur Simplicity", desc: "四天佩戴式胰岛素贴片，通过简单点击输送餐时胰岛素。", image: "pumps/cequr-simplicity.png", tags: ["餐时剂量贴片", "4 天佩戴", "无电子元件"], sourceUrl: "https://myceqursimplicity.com/" },
        ] },
      ],
      expectTitle: "培训中会学习什么",
      expectations: ["了解胰岛素泵部件和界面操作。", "安全更换部位和置入输注装置。", "根据医生医嘱设置基础率、碳水比和校正因子。", "处理警报并解决常见问题。"],
      needTitle: "需要培训吗？",
      needBody: "这项胰岛素泵培训完全免费。无需保险要求，无需转诊。您可以直接预约，获得实操支持。",
      scheduleButton: "预约培训",
    },
    "cgm": {
      heroTitle: "动态血糖仪培训与报告分析",
      heroSubtitle: "发挥动态血糖仪的力量。我们教您如何使用、解读报告，并帮助您和医生把数据转化为更好的决定。",
      logoAlt: "{{name}} 标志",
      officialWebsite: "官方网站",
      lingoFallbackDesc: "为 Abbott Lingo 用户提供支持，帮助理解血糖模式和生活方式反应。",
      devices: [
        { name: "FreeStyle Libre", maker: "Abbott", logo: "cgm-logos/freestyle-libre-v2.png", desc: "培训传感器佩戴、手机读取器使用和趋势箭头理解。", sourceUrl: "https://www.freestyle.abbott/us-en/home.html" },
        { name: "Dexcom G7/G6", maker: "Dexcom", logo: "cgm-logos/dexcom-v2.png", desc: "协助设置提醒和警报、与家人或诊所共享数据，以及申请流程。", sourceUrl: "https://www.dexcom.com/" },
        { name: "Stelo", maker: "Dexcom OTC", logo: "cgm-logos/stelo-v2.png", desc: "指导 2 型糖尿病患者解读非处方生物传感器数据。", sourceUrl: "https://www.stelo.com/" },
        { name: "Lingo", maker: "Abbott", logo: "cgm-logos/lingo-v2.png", desc: "支持 Abbott Lingo 用户理解血糖模式和生活方式反应。", sourceUrl: "https://www.hellolingo.com/" },
      ],
      features: {
        appSetup: "应用设置",
        arrowTrends: "趋势箭头",
        agpReports: "AGP 报告",
        reportInterpretation: "报告解读",
        timeInRange: "目标范围内时间",
      },
      beyondTitle: "不只是数字",
      beyondIntro: "动态血糖仪每天提供数百个读数，但下一步该怎么做？",
      beyondBody: "我们分析并解读您的 Ambulatory Glucose Profile (AGP) 报告，找出模式。我们也会教您不同食物、压力和运动如何影响您独特的身体反应，帮助您提高 <strong>目标范围内时间</strong> (TIR)。",
      scheduleButton: "预约分析课程",
    },
    "glp1Training": {
      badge: "GLP-1 注射和口服药物支持",
      imageAlt: "糖尿病教育者与患者一起复习 GLP-1 药物培训",
      heroTitle: "GLP-1 药物使用培训",
      heroSubtitle: "开始使用 semaglutide、tirzepatide、liraglutide 或其他 GLP-1 类治疗时，常会有实际操作问题。我们教授日常步骤、副作用规划和随访习惯，让治疗更容易坚持。",
      scheduleButton: "预约 GLP-1 培训",
      trainingTitle: "培训内容",
      trainingIntro: "培训以教育为目的，并配合开药医生的指示。",
      topics: [
        { title: "注射技巧", desc: "如何准备注射笔、选择和轮换注射部位、储存药物，并安全处理锐器。" },
        { title: "口服药流程", desc: "如何建立一致的口服 GLP-1 服药时间、处理漏服问题，并理解药房说明。" },
        { title: "饮食和补水策略", desc: "在食欲变化和剂量递增期间，安排进食节奏、蛋白质、液体和份量。" },
        { title: "剂量调整", desc: "了解需要记录什么、何时联系开药医生，以及剂量变化前如何准备问题。" },
      ],
      sideEffectTitle: "副作用管理",
      sideEffectIntro: "常见 GLP-1 副作用多与胃肠道有关。我们帮助患者制定现实可行的管理方法，并识别何时需要医学随访。",
      sideEffects: ["恶心、饱胀、食欲变化和进食耐受", "呕吐、腹泻、便秘、胀气或腹部不适", "GLP-1 与胰岛素或磺脲类药物同用时的低血糖风险", "需要及时升级给开药医疗团队的警示信号"],
    },
    "providers": {
      badge: "ADCES 认证糖尿病教育项目",
      heroLine1: "与医生合作",
      heroLine2: "改善患者结果",
      heroSubtitle: "XT Diabetes Care 是您诊所的延伸。我们提供患者所需的深入、系统性糖尿病自我管理教育，并由保险覆盖。",
      values: [
        { title: "节省您的时间", desc: "我们承担耗时的全面糖尿病教育工作，让您专注于诊断和用药管理。" },
        { title: "结构化课程", desc: "患者接受用药、饮食、身体活动和心理社会应对方面的系统教育。" },
        { title: "持续向您反馈", desc: "我们作为您的助手，向您回传综合报告，并确保患者定期与您随访进行用药调整。" },
      ],
      referTitle: "如何转诊患者",
      referIntro: "Medicare / Medicaid 和商业保险覆盖我们的项目，但需要治疗医生转诊。",
      faxLine: "请将表格传真至 (888) 370-1981。",
      referralCandidates: ["新诊断糖尿病患者。", "从未接受系统性糖尿病自我管理培训的患者。", "正在转换到胰岛素泵或动态血糖仪的患者。"],
      downloadButton: "下载转诊表模板",
      accreditedTitle: "ADCES 认证",
      accreditedId: "ID# 1001155",
      accreditedBody: "已符合糖尿病护理与教育专家协会的所有适用标准和要求。",
      certificateAlt: "ADCES DEAP 证书",
    }
  },
  "zh-TW": {
    "classes": {
      eyebrow: "ADCES 認證 DSME 項目",
      chineseFirstBadge: "全美首箇中文認證 DSME 課程",
      heroTitle: "糖尿病自我管理教育（DSME）",
      heroSubtitle: "實用教育項目，幫助您理解糖尿病、安心飲食、保持活動、安全用藥、降低風險，並處理日常挑戰。",
      bookButton: "預約課程",
      viewCurriculumButton: "查看課程內容",
      bilingual: "雙語：英語和中文（普通話）",
      delivery: "線上與線下",
      coverageNote: "多數符合條件的患者可通過保險 $0 參加",
      programLabel: "項目形式",
      hours: "結構化 DSME 項目",
      hoursDescription: "全面的糖尿病自我管理教育",
      outcomes: ["飲食和生活方式技能", "用藥和監測基礎", "風險降低和支持"],
      credentialEyebrow: "認證教育與保險支持",
      credentialTitle: "可由保險報銷的認證糖尿病教育",
      credentialIntro: "本項目面向需要結構化 DSME 支持的患者，並提供轉診和福利覈實方面的實際協助。",
      credentials: [
        { title: "ADCES DEAP 認證", desc: "項目級認證支持全國認可的糖尿病教育標準。" },
        { title: "認證糖尿病專業能力", desc: "教育結合糖尿病護理、營養、用藥、技術和生活方式經驗。" },
        { title: "註冊營養護理", desc: "營養師主導的營養護理支持飲食、生活方式、血糖模式和長期自我管理。" },
      ],
      curriculumEyebrow: "課程大綱",
      curriculumTitle: "六節聚焦真實生活的糖尿病管理課程",
      curriculumIntro: "課程圍繞可在家中、用餐時、活動中，以及血糖數字不如預期時使用的實際技能設計。",
      sessionLabel: "第 {{number}} 節",
      curriculum: [
        { title: "理解糖尿病", subtitle: "糖尿病基礎和治療概覽", topics: ["1 型、2 型、糖尿病前期和妊娠糖尿病", "常見症狀、疾病進展和血糖目標", "生活方式、口服藥、注射藥物、胰島素和監測如何配合"] },
        { title: "健康飲食", subtitle: "食物選擇、碳水化合物和餐食規劃", topics: ["簡單與複雜碳水，以及常見食物來源", "閱讀營養標籤並搭配均衡餐盤", "份量、醬料、點心、酒精和外食場景"] },
        { title: "保持活動", subtitle: "安全運動和個性化活動計劃", topics: ["有氧和抗阻運動的益處", "飯後短時間步行、椅子瑜伽和增肌習慣", "根據年齡、健康狀況和血糖讀數調整運動"] },
        { title: "用藥與監測", subtitle: "安全用藥和血糖監測", topics: ["理解您的用藥計劃、藥名和常見副作用", "居家血糖監測、動態血糖儀目標範圍內時間和實用目標", "何時聯繫護理團隊，以及如何爲劑量調整做準備"] },
        { title: "降低風險", subtitle: "預防、警示信號和併發症意識", topics: ["眼睛、腎臟、神經和足部相關的短期與長期併發症", "低血糖和高血糖症狀、處理步驟和應急計劃", "預防性護理清單，以及何時應看糖尿病護理專家"] },
        { title: "應對與解決問題", subtitle: "日常信心、壓力支持和現實決策", topics: ["糖尿病壓力、倦怠、抑鬱風險和支持系統", "照護者和家庭成員溝通技巧", "案例學習、生病日計劃和意外血糖模式應對策略"] },
      ],
      instructorsEyebrow: "教學團隊",
      instructorsTitle: "讓糖尿病更容易理解的教育者",
      instructorsIntro: "認識支持糖尿病教育項目的教學團隊。",
      instructorsReadFullBio: "查看完整介紹",
      instructorsCloseBio: "關閉介紹",
      rosterLabel: "團隊名單",
      instructors: [
        {
          name: "Ziying",
          role: "註冊營養師",
          bio: [
            "你好，我是 Ziying，一名註冊營養師。",
            "在不同醫療環境中的工作經驗，讓我陪伴過許多人走過健康旅程中的不同階段。一直激勵我的是，人們為了改善健康所投入的認真和堅持。同時，我也看見，飲食規則、血糖數字和彼此衝突的建議，很容易讓人感到不知所措。",
            "隨著經驗累積，我逐漸意識到，大多數人並不是不夠努力，而是缺少真正適合現實生活的指導。這個認識讓我走進了糖尿病教育。",
            "基於在醫院、醫療中心和私人診所的經驗，我共同主導開發了一個糖尿病自我管理教育（DSME）項目，重點是讓糖尿病護理在日常生活中更現實、更容易接近，也更可持續。",
            "在我看來，成功的糖尿病教育，是幫助人們在照顧健康時更有信心，同時仍然能夠享受食物和生活。",
            "如果你已經準備好主動掌握自己的健康，我會在這裡支持你。",
          ],
          image: "team/ziying.webp",
        },
        {
          name: "Yirao (Rebecca) Wang, RDN, LDN, MPH",
          role: "註冊營養師及糖尿病教育者",
          bio: [
            "我走進糖尿病護理，源於我在海外讀研期間父親被診斷出糖尿病。起初，我嘗試透過飲食限制來幫助他，但很快意識到，糖尿病患者需要的不只是「不能吃什麼」。他們需要實用的指導、文化上的理解，以及能幫助他們繼續享受生活的支持。",
            "這段經歷促使我在美國繼續學習營養與膳食學。我在紐約大學完成了 MPH 和 DPD 課程，並在 Yale New Haven Hospital 接受臨床訓練，之後又在佛羅里達完成長期照護相關輪轉。",
            "如今，我作為註冊營養師和糖尿病教育者，支持老年糖尿病患者及慢性病管理。我也主導開發面向亞洲社群的首個文化適配型 DSME 項目，目標是減少語言障礙，讓糖尿病和營養教育更易獲得、更貼近文化，也更可持續。",
            "我工作的核心，是連結、同理心，以及幫助人們帶著信心建立更健康的生活，同時在與糖尿病共處時維持良好的生活品質。",
          ],
          image: "team/yirao-wang.webp",
        },
        {
          name: "Jinhui Zhou, MS, RD, CDN, CDCES",
          role: "註冊營養師及認證糖尿病護理與教育專家",
          bio: [
            "大家好，我是 Jinhui，一名註冊營養師及認證糖尿病護理與教育專家。我熱衷於幫助人們用現實、可持續的方式管理糖尿病。",
            "我對糖尿病教育的興趣，來自看到很多人在面對飲食和血糖管理時感到壓力很大。我喜歡幫助患者簡化營養信息，建立對飲食的信心，並養成適合自己日常生活和文化背景的健康習慣。",
            "我很高興加入糖尿病教育項目，也期待爲我們的社區提供支持！",
          ],
          image: "team/jinhui-zhou.webp",
        },
      ],
      testimonialsEyebrow: "患者反饋",
      testimonialsTitle: "結構化糖尿病教育讓患者更有信心",
      testimonials: [
        { quote: "課程終於讓我看懂自己的數字。我學會早餐該調整什麼，也知道如何帶着更好的問題和醫生溝通。", name: "M. Lee", detail: "DSME 參與者", image: "testimonials/patient-01.webp" },
        { quote: "藥物和血糖讀數曾讓我非常焦慮。課程給了我一個能和家人一起執行的簡單計劃。", name: "R. Johnson", detail: "2 型糖尿病支持", image: "testimonials/patient-02.webp" },
        { quote: "教學清楚、耐心又實用。結束時我知道如何讀標籤，也更安全地預防低血糖。", name: "A. Chen", detail: "雙語課程參與者", image: "testimonials/patient-03.webp" },
      ],
      ctaTitle: "準備開始學習了嗎？",
      ctaBody: "課程爲真實生活中的糖尿病管理而設計。轉診和福利覈實後，Medicare / Medicaid 以及許多商業保險可能報銷符合條件的 DSME 服務。",
      startEyebrow: "如何開始",
      startTitle: "從報名到上課的清晰流程",
      startIntro: "我們協助簡化行政步驟，讓患者專注於學習。",
      startSteps: [
        { title: "報名", desc: "提交信息或預約課程時間。" },
        { title: "轉診 + 覈實", desc: "我們協助處理轉診需求並覈實保險福利。" },
        { title: "參加課程", desc: "線上或線下參加結構化 DSME 課程。" },
        { title: "看到結果", desc: "把技能應用到食物選擇、活動、用藥流程和血糖模式中。" },
      ],
      disclaimerTitle: "免責聲明",
      disclaimerBody: "XT Diabetes Care 提供的信息和服務旨在幫助個人通過飲食和生活方式改變改善健康。所有信息僅用於教育目的，不應替代醫療護理、建議、診斷或治療。如有任何醫療問題，或在開始飲食或運動計劃前，請諮詢醫生或其他合格醫療專業人員。",
      insuranceButton: "查看保險信息",
      contactButton: "聯繫我們",
    },
    "pumpTraining": {
      heroTitle: "胰島素泵培訓",
      heroSubtitle: "免費胰島素泵培訓，無需保險要求，也無需醫生轉診。帶上您的設備和問題，帶着信心離開。",
      heroBadges: { free: "100% 免費", noInsurance: "無需保險", noReferral: "無需轉診" },
      catalogEyebrow: "胰島素泵目錄",
      catalogTitle: "主要胰島素泵品牌和當前系統",
      catalogSubtitle: "真實產品圖片按廠家分組，方便患者比較可能接受培訓的設備。",
      productLabel: "款產品",
      productsLabel: "款產品",
      sourceLink: "官方產品頁面",
      pumpBrands: [
        { brand: "Omnipod", summary: "無管 Pod 治療，提供自動和手動胰島素管理選項。", products: [
          { name: "Omnipod 5", desc: "無管自動胰島素輸送系統，可根據動態血糖儀數據調整胰島素。", image: "pumps/omnipod-5.png", tags: ["無管", "AID", "Pod"], sourceUrl: "https://www.omnipod.com/what-is-omnipod/omnipod-5" },
          { name: "Omnipod DASH", desc: "使用可穿戴 Pod 和手持控制器的無管胰島素管理系統。", image: "pumps/omnipod-dash.png", tags: ["無管", "Pod", "PDM"], sourceUrl: "https://www.omnipod.com/what-is-omnipod/omnipod-dash" },
        ] },
        { brand: "twiist", summary: "基於已獲 FDA 批准的 Tidepool Loop 算法進行自動胰島素輸送。", products: [
          { name: "twiist AID System", desc: "使用 Tidepool Loop 和 twiist 泵平臺的自動胰島素輸送系統。", image: "pumps/twiist-aid.png", tags: ["AID", "Tidepool Loop", "300 單位"], sourceUrl: "https://www.twiist.com/" },
        ] },
        { brand: "Beta Bionics", summary: "簡化型仿生胰腺系統，用於自動化胰島素劑量決策。", products: [
          { name: "iLet Bionic Pancreas", desc: "以體重作爲起點，通過 iLet 系統自動化胰島素劑量決策。", image: "pumps/ilet-bionic-pancreas.png", tags: ["AID", "體重起始", "動態血糖儀"], sourceUrl: "https://www.betabionics.com/ilet-bionic-pancreas/" },
        ] },
        { brand: "Tandem Diabetes Care", summary: "使用 Control-IQ 技術的屏幕式和手機控制泵系統。", products: [
          { name: "Tandem Mobi", desc: "可通過兼容手機應用控制的小型耐用泵。", image: "pumps/tandem-mobi.png", tags: ["AID", "手機控制", "200 單位"], sourceUrl: "https://www.tandemdiabetes.com/products/insulin-pumps/tandem-mobi" },
          { name: "t:slim X2", desc: "帶觸摸屏、Control-IQ 技術和軟件更新功能的胰島素泵。", image: "pumps/tandem-tslim-x2.png", tags: ["AID", "觸摸屏", "300 單位"], sourceUrl: "https://www.tandemdiabetes.com/products/insulin-pumps/tslim-x2-insulin-pump" },
        ] },
        { brand: "MiniMed", summary: "Medtronic 系統，圍繞 SmartGuard 自動化和 Guardian 傳感器整合構建。", products: [
          { name: "MiniMed 780G", desc: "配備 SmartGuard 技術的自動胰島素輸送系統。", image: "pumps/minimed-780g.png", tags: ["AID", "SmartGuard", "Guardian"], sourceUrl: "https://www.minimed.com/en-us/products/minimed-780g-insulin-pump-system" },
        ] },
        { brand: "CeQur", summary: "餐時胰島素可穿戴貼片，適合需要餐時胰島素但不需要完整泵系統的人。", products: [
          { name: "CeQur Simplicity", desc: "四天佩戴式胰島素貼片，通過簡單點擊輸送餐時胰島素。", image: "pumps/cequr-simplicity.png", tags: ["餐時劑量貼片", "4 天佩戴", "無電子元件"], sourceUrl: "https://myceqursimplicity.com/" },
        ] },
      ],
      expectTitle: "培訓中會學習什麼",
      expectations: ["瞭解胰島素泵部件和界面操作。", "安全更換部位和置入輸注裝置。", "根據醫生醫囑設置基礎率、碳水比和校正因子。", "處理警報並解決常見問題。"],
      needTitle: "需要培訓嗎？",
      needBody: "這項胰島素泵培訓完全免費。無需保險要求，無需轉診。您可以直接預約，獲得實操支持。",
      scheduleButton: "預約培訓",
    },
    "cgm": {
      heroTitle: "動態血糖儀培訓與報告分析",
      heroSubtitle: "發揮動態血糖儀的力量。我們教您如何使用、解讀報告，並幫助您和醫生把數據轉化爲更好的決定。",
      logoAlt: "{{name}} 標誌",
      officialWebsite: "官方網站",
      lingoFallbackDesc: "爲 Abbott Lingo 用戶提供支持，幫助理解血糖模式和生活方式反應。",
      devices: [
        { name: "FreeStyle Libre", maker: "Abbott", logo: "cgm-logos/freestyle-libre-v2.png", desc: "培訓傳感器佩戴、手機讀取器使用和趨勢箭頭理解。", sourceUrl: "https://www.freestyle.abbott/us-en/home.html" },
        { name: "Dexcom G7/G6", maker: "Dexcom", logo: "cgm-logos/dexcom-v2.png", desc: "協助設置提醒和警報、與家人或診所共享數據，以及申請流程。", sourceUrl: "https://www.dexcom.com/" },
        { name: "Stelo", maker: "Dexcom OTC", logo: "cgm-logos/stelo-v2.png", desc: "指導 2 型糖尿病患者解讀非處方生物傳感器數據。", sourceUrl: "https://www.stelo.com/" },
        { name: "Lingo", maker: "Abbott", logo: "cgm-logos/lingo-v2.png", desc: "支持 Abbott Lingo 用戶理解血糖模式和生活方式反應。", sourceUrl: "https://www.hellolingo.com/" },
      ],
      features: {
        appSetup: "應用設置",
        arrowTrends: "趨勢箭頭",
        agpReports: "AGP 報告",
        reportInterpretation: "報告解讀",
        timeInRange: "目標範圍內時間",
      },
      beyondTitle: "不只是數字",
      beyondIntro: "動態血糖儀每天提供數百個讀數，但下一步該怎麼做？",
      beyondBody: "我們分析並解讀您的 Ambulatory Glucose Profile (AGP) 報告，找出模式。我們也會教您不同食物、壓力和運動如何影響您獨特的身體反應，幫助您提高 <strong>目標範圍內時間</strong> (TIR)。",
      scheduleButton: "預約分析課程",
    },
    "glp1Training": {
      badge: "GLP-1 注射和口服藥物支持",
      imageAlt: "糖尿病教育者與患者一起復習 GLP-1 藥物培訓",
      heroTitle: "GLP-1 藥物使用培訓",
      heroSubtitle: "開始使用 semaglutide、tirzepatide、liraglutide 或其他 GLP-1 類治療時，常會有實際操作問題。我們教授日常步驟、副作用規劃和隨訪習慣，讓治療更容易堅持。",
      scheduleButton: "預約 GLP-1 培訓",
      trainingTitle: "培訓內容",
      trainingIntro: "培訓以教育爲目的，並配合開藥醫生的指示。",
      topics: [
        { title: "注射技巧", desc: "如何準備注射筆、選擇和輪換注射部位、儲存藥物，並安全處理銳器。" },
        { title: "口服藥流程", desc: "如何建立一致的口服 GLP-1 服藥時間、處理漏服問題，並理解藥房說明。" },
        { title: "飲食和補水策略", desc: "在食慾變化和劑量遞增期間，安排進食節奏、蛋白質、液體和份量。" },
        { title: "劑量調整", desc: "瞭解需要記錄什麼、何時聯繫開藥醫生，以及劑量變化前如何準備問題。" },
      ],
      sideEffectTitle: "副作用管理",
      sideEffectIntro: "常見 GLP-1 副作用多與胃腸道有關。我們幫助患者制定現實可行的管理方法，並識別何時需要醫學隨訪。",
      sideEffects: ["噁心、飽脹、食慾變化和進食耐受", "嘔吐、腹瀉、便祕、脹氣或腹部不適", "GLP-1 與胰島素或磺脲類藥物同用時的低血糖風險", "需要及時升級給開藥醫療團隊的警示信號"],
    },
    "providers": {
      badge: "ADCES 認證糖尿病教育項目",
      heroLine1: "與醫生合作",
      heroLine2: "改善患者結果",
      heroSubtitle: "XT Diabetes Care 是您診所的延伸。我們提供患者所需的深入、系統性糖尿病自我管理教育，並由保險覆蓋。",
      values: [
        { title: "節省您的時間", desc: "我們承擔耗時的全面糖尿病教育工作，讓您專注於診斷和用藥管理。" },
        { title: "結構化課程", desc: "患者接受用藥、飲食、身體活動和心理社會應對方面的系統教育。" },
        { title: "持續向您反饋", desc: "我們作爲您的助手，向您回傳綜合報告，並確保患者定期與您隨訪進行用藥調整。" },
      ],
      referTitle: "如何轉診患者",
      referIntro: "Medicare / Medicaid 和商業保險覆蓋我們的項目，但需要治療醫生轉診。",
      faxLine: "請將表格傳真至 (888) 370-1981。",
      referralCandidates: ["新診斷糖尿病患者。", "從未接受系統性糖尿病自我管理培訓的患者。", "正在轉換到胰島素泵或動態血糖儀的患者。"],
      downloadButton: "下載轉診表模板",
      accreditedTitle: "ADCES 認證",
      accreditedId: "ID# 1001155",
      accreditedBody: "已符合糖尿病護理與教育專家協會的所有適用標準和要求。",
      certificateAlt: "ADCES DEAP 證書",
    }
  },
  "es": {
    "classes": {
      eyebrow: "Programa DSME acreditado por ADCES",
      chineseFirstBadge: "El primer curso DSME acreditado en chino en los EE. UU.",
      heroTitle: "Educación para el automanejo de la diabetes (DSME)",
      heroSubtitle: "Un programa práctico para entender la diabetes, comer con confianza, mantenerse activo, usar medicamentos de forma segura, reducir riesgos y resolver desafíos diarios.",
      bookButton: "Reservar clase",
      viewCurriculumButton: "Ver currículo",
      bilingual: "Bilingüe: inglés y chino (mandarín)",
      delivery: "En línea y en persona",
      coverageNote: "Muchos pacientes elegibles pagan $0 con seguro",
      programLabel: "Formato del programa",
      hours: "Programa DSME estructurado",
      hoursDescription: "Educación integral para el automanejo de la diabetes",
      outcomes: ["Alimentación y estilo de vida", "Medicamentos y monitoreo", "Reducción de riesgos y apoyo"],
      credentialEyebrow: "Educación acreditada y apoyo con cobertura",
      credentialTitle: "Educación certificada en diabetes que puede ser reembolsada por el seguro",
      credentialIntro: "El programa está diseñado para pacientes que necesitan apoyo DSME estructurado y ayuda práctica con referidos y verificación de beneficios.",
      credentials: [
        { title: "Acreditado por ADCES DEAP", desc: "La acreditación del programa respalda estándares reconocidos de educación en diabetes." },
        { title: "Experiencia certificada", desc: "La educación combina diabetes, nutrición, medicamentos, tecnología y manejo del estilo de vida." },
        { title: "Cuidado nutricional registrado", desc: "El cuidado nutricional dirigido por dietistas apoya alimentación, estilo de vida, patrones de glucosa y automanejo a largo plazo." },
      ],
      curriculumEyebrow: "Currículo",
      curriculumTitle: "Seis sesiones enfocadas en el manejo real de la diabetes",
      curriculumIntro: "El currículo se centra en habilidades prácticas para usar en casa, durante las comidas, con la actividad física y cuando los niveles de glucosa no salen como se esperaba.",
      sessionLabel: "Sesión {{number}}",
      curriculum: [
        { title: "Comprender la diabetes", subtitle: "Conceptos básicos y panorama del tratamiento", topics: ["Diabetes tipo 1, tipo 2, prediabetes y diabetes gestacional", "Síntomas, progresión y metas de glucosa", "Cómo se combinan estilo de vida, medicamentos, insulina y monitoreo"] },
        { title: "Alimentación saludable", subtitle: "Alimentos, carbohidratos y planificación", topics: ["Carbohidratos simples y complejos y sus fuentes comunes", "Lectura de etiquetas nutricionales y comidas balanceadas", "Ejemplos de comidas asiáticas, porciones, salsas, meriendas, alcohol y comidas fuera de casa"] },
        { title: "Actividad física", subtitle: "Movimiento seguro y plan individualizado", topics: ["Beneficios del ejercicio aeróbico y de resistencia", "Caminatas después de comer, yoga en silla y hábitos para desarrollar músculo", "Adaptar la actividad a edad, condiciones de salud y lecturas de glucosa"] },
        { title: "Medicamentos y monitoreo", subtitle: "Uso seguro de medicamentos y control de glucosa", topics: ["Entender el plan de medicamentos, nombres y efectos secundarios comunes", "Monitoreo en casa, tiempo en rango con CGM y metas útiles", "Cuándo contactar al equipo de salud y cómo prepararse para ajustes de dosis"] },
        { title: "Reducir riesgos", subtitle: "Prevención, señales de alerta y complicaciones", topics: ["Complicaciones de ojos, riñones, nervios y pies", "Síntomas y pasos de tratamiento para hipoglucemia e hiperglucemia", "Lista de cuidados preventivos y cuándo ver a un especialista en diabetes"] },
        { title: "Afrontamiento y solución de problemas", subtitle: "Confianza diaria, estrés y decisiones reales", topics: ["Estrés por diabetes, agotamiento, riesgo de depresión y sistemas de apoyo", "Comunicación con cuidadores y familiares", "Casos prácticos, plan para días de enfermedad y patrones inesperados de glucosa"] },
      ],
      instructorsEyebrow: "Equipo docente",
      instructorsTitle: "Educadores que hacen la diabetes más fácil de entender",
      instructorsIntro: "Conozca a las educadoras que apoyan el programa de educación en diabetes.",
      instructorsReadFullBio: "Leer biografía completa",
      instructorsCloseBio: "Cerrar biografía",
      rosterLabel: "Equipo",
      instructors: [
        {
          name: "Ziying",
          role: "Dietista registrada",
          bio: [
            "Hola, soy Ziying, dietista registrada.",
            "A través de mi trabajo en distintos entornos de atención médica, he acompañado a personas en diferentes etapas de su camino hacia una mejor salud. Algo que sigue inspirándome es ver cuánto compromiso ponen las personas en mejorar su bienestar. Al mismo tiempo, he visto lo fácil que es sentirse abrumado por reglas sobre la comida, números de glucosa en sangre y consejos contradictorios.",
            "Con el tiempo, comprendí que la mayoría de las personas no carecen de esfuerzo. Lo que les falta es orientación que realmente encaje con su vida diaria. Esa comprensión me llevó a la educación en diabetes.",
            "A partir de mi experiencia en hospitales, centros médicos y práctica privada, codirigí el desarrollo de un programa de Educación para el Automanejo de la Diabetes (DSME) centrado en hacer que el cuidado de la diabetes sea más realista, accesible y sostenible en la vida cotidiana.",
            "Para mí, una educación en diabetes exitosa ayuda a las personas a sentirse más seguras al cuidar su salud, sin dejar de disfrutar la comida y la vida en el proceso.",
            "Si está listo para tomar el control de su salud, estoy aquí para apoyarle.",
          ],
          image: "team/ziying.webp",
        },
        {
          name: "Yirao (Rebecca) Wang, RDN, LDN, MPH",
          role: "Dietista registrada y educadora en diabetes",
          bio: [
            "Mi camino hacia el cuidado de la diabetes comenzó cuando mi padre recibió el diagnóstico de diabetes durante mis estudios de posgrado en el extranjero. Al principio intenté ayudar enfocándome en restricciones alimentarias, pero pronto comprendí que las personas que viven con diabetes necesitan más que saber “qué no comer”. Necesitan orientación práctica, comprensión cultural y apoyo que les permita seguir disfrutando la vida.",
            "Esta experiencia me inspiró a estudiar nutrición y dietética en los Estados Unidos. Completé mi MPH y los cursos de DPD en New York University, recibí formación clínica en Yale New Haven Hospital y después realicé rotaciones de cuidado a largo plazo en Florida.",
            "Hoy trabajo como dietista registrada y educadora en diabetes, apoyando a adultos mayores con diabetes y manejo de enfermedades crónicas. También lidero el desarrollo del primer programa DSME culturalmente adaptado para comunidades asiáticas, con el objetivo de reducir barreras lingüísticas y hacer que la educación en diabetes y nutrición sea más accesible, culturalmente relevante y sostenible.",
            "En el centro de mi trabajo están la conexión, la compasión y ayudar a las personas a construir vidas más saludables con confianza, manteniendo una buena calidad de vida con diabetes.",
          ],
          image: "team/yirao-wang.webp",
        },
        {
          name: "Jinhui Zhou, MS, RD, CDN, CDCES",
          role: "Dietista registrada y CDCES",
          bio: [
            "Hola a todos, soy Jinhui, dietista registrada y CDCES. Me apasiona ayudar a las personas a manejar la diabetes de una manera realista y sostenible.",
            "Mi interés en la educación en diabetes nace de ver lo abrumador que puede sentirse el manejo de la alimentación y la glucosa en sangre para muchas personas. Disfruto ayudar a los pacientes a simplificar la información nutricional, ganar confianza con la comida y crear hábitos saludables que se adapten a su vida diaria y a su cultura.",
            "Me alegra formar parte del programa de educación en diabetes y espero poder apoyar a nuestra comunidad.",
          ],
          image: "team/jinhui-zhou.webp",
        },
      ],
      testimonialsEyebrow: "Comentarios de pacientes",
      testimonialsTitle: "Los pacientes se sienten más seguros después de educación estructurada en diabetes",
      testimonials: [
        { quote: "La clase finalmente hizo que mis números tuvieran sentido. Aprendí qué cambiar en el desayuno y cómo hablar con mi médico con mejores preguntas.", name: "M. Lee", detail: "Participante de DSME", image: "testimonials/patient-01.webp" },
        { quote: "Me sentía abrumado por medicamentos y lecturas de glucosa. Las sesiones me dieron un plan simple que podía seguir con mi familia.", name: "R. Johnson", detail: "Apoyo para diabetes tipo 2", image: "testimonials/patient-02.webp" },
        { quote: "La enseñanza fue clara, paciente y práctica. Salí sabiendo cómo leer etiquetas y prevenir glucosa baja con más seguridad.", name: "A. Chen", detail: "Participante bilingüe", image: "testimonials/patient-03.webp" },
      ],
      ctaTitle: "¿Listo para empezar a aprender?",
      ctaBody: "Las clases están diseñadas para el manejo práctico de la diabetes en la vida real. Medicare / Medicaid y muchos seguros privados pueden reembolsar servicios DSME elegibles después del referido y verificación de beneficios.",
      startEyebrow: "Cómo empezar",
      startTitle: "Un camino claro desde la inscripción hasta la clase",
      startIntro: "Ayudamos a que los pasos administrativos sean menos confusos para que el paciente pueda enfocarse en aprender.",
      startSteps: [
        { title: "Inscríbase", desc: "Envíe su información o reserve un horario de clase." },
        { title: "Referido + verificación", desc: "Ayudamos a coordinar referidos y verificar beneficios del seguro." },
        { title: "Asista a clase", desc: "Participe en sesiones DSME estructuradas en línea o en persona." },
        { title: "Vea resultados", desc: "Aplique las habilidades a comidas, actividad, medicamentos y patrones de glucosa." },
      ],
      disclaimerTitle: "Aviso",
      disclaimerBody: "La información y los servicios proporcionados por XT Diabetes Care tienen el propósito de ayudar a las personas a mejorar su salud mediante cambios en la alimentación y el estilo de vida. Toda la información es solo para fines educativos. Esta información no debe usarse como sustituto de atención médica, consejo médico, diagnóstico o tratamiento. Las personas deben hablar con un médico u otro profesional de salud calificado sobre cualquier inquietud médica y antes de iniciar un programa de dieta o ejercicio.",
      insuranceButton: "Ver información del seguro",
      contactButton: "Contáctenos",
    },
    "pumpTraining": {
      heroTitle: "Capacitación en bombas de insulina",
      heroSubtitle: "Capacitación gratuita en bombas de insulina, sin requisito de seguro ni referido médico. Traiga su dispositivo y sus preguntas, y salga con confianza.",
      heroBadges: {
        free: "100% gratis",
        noInsurance: "No requiere seguro",
        noReferral: "No requiere referido",
      },
      catalogEyebrow: "Catálogo de bombas",
      catalogTitle: "Marcas principales y sistemas actuales",
      catalogSubtitle: "Las imágenes reales de producto están agrupadas por fabricante para que los pacientes comparen los dispositivos que podrían usar en la capacitación.",
      productLabel: "producto",
      productsLabel: "productos",
      sourceLink: "Página oficial del producto",
      pumpBrands: [
        {
          brand: "Omnipod",
          summary: "Terapia Pod sin tubos con opciones automatizadas y de manejo manual de insulina.",
          products: [
            { name: "Omnipod 5", desc: "Sistema automatizado de administración de insulina sin tubos diseñado para ajustar la insulina con datos de CGM.", image: "pumps/omnipod-5.png", tags: ["Sin tubos", "AID", "Pod"], sourceUrl: "https://www.omnipod.com/what-is-omnipod/omnipod-5" },
            { name: "Omnipod DASH", desc: "Sistema de manejo de insulina sin tubos con un Pod portátil y controlador manual.", image: "pumps/omnipod-dash.png", tags: ["Sin tubos", "Pod", "PDM"], sourceUrl: "https://www.omnipod.com/what-is-omnipod/omnipod-dash" },
          ],
        },
        {
          brand: "twiist",
          summary: "Administración automatizada de insulina basada en el algoritmo Tidepool Loop autorizado por la FDA.",
          products: [
            { name: "twiist AID System", desc: "Sistema automatizado de insulina que usa Tidepool Loop y la plataforma de bomba twiist.", image: "pumps/twiist-aid.png", tags: ["AID", "Tidepool Loop", "300 unidades"], sourceUrl: "https://www.twiist.com/" },
          ],
        },
        {
          brand: "Beta Bionics",
          summary: "Sistema de páncreas biónico simplificado para automatizar decisiones de dosificación.",
          products: [
            { name: "iLet Bionic Pancreas", desc: "Comienza con el peso corporal y automatiza decisiones de dosificación de insulina mediante el sistema iLet.", image: "pumps/ilet-bionic-pancreas.png", tags: ["AID", "Inicio por peso", "CGM"], sourceUrl: "https://www.betabionics.com/ilet-bionic-pancreas/" },
          ],
        },
        {
          brand: "Tandem Diabetes Care",
          summary: "Sistemas con pantalla táctil y control móvil que usan tecnología Control-IQ.",
          products: [
            { name: "Tandem Mobi", desc: "Bomba duradera y pequeña controlada desde una app compatible para smartphone.", image: "pumps/tandem-mobi.png", tags: ["AID", "Control móvil", "200 unidades"], sourceUrl: "https://www.tandemdiabetes.com/products/insulin-pumps/tandem-mobi" },
            { name: "t:slim X2", desc: "Bomba de insulina con pantalla táctil, tecnología Control-IQ y actualizaciones de software.", image: "pumps/tandem-tslim-x2.png", tags: ["AID", "Pantalla táctil", "300 unidades"], sourceUrl: "https://www.tandemdiabetes.com/products/insulin-pumps/tslim-x2-insulin-pump" },
          ],
        },
        {
          brand: "MiniMed",
          summary: "Sistemas Medtronic centrados en automatización SmartGuard e integración con sensores Guardian.",
          products: [
            { name: "MiniMed 780G", desc: "Sistema automatizado de administración de insulina con tecnología SmartGuard.", image: "pumps/minimed-780g.png", tags: ["AID", "SmartGuard", "Guardian"], sourceUrl: "https://www.minimed.com/en-us/products/minimed-780g-insulin-pump-system" },
          ],
        },
        {
          brand: "CeQur",
          summary: "Parche de insulina para comidas para personas que necesitan bolos sin un sistema completo de bomba.",
          products: [
            { name: "CeQur Simplicity", desc: "Parche portátil de cuatro días que administra insulina para comidas con clics sencillos.", image: "pumps/cequr-simplicity.png", tags: ["Parche de bolo", "4 días", "Sin electrónica"], sourceUrl: "https://myceqursimplicity.com/" },
          ],
        },
      ],
      expectTitle: "Qué esperar durante la capacitación",
      expectations: [
        "Comprender los componentes de su bomba y cómo navegar sus menús.",
        "Rotación segura de sitios e inserción del set de infusión.",
        "Programación de tasas basales, proporciones de carbohidratos y factores de corrección según las indicaciones de su médico.",
        "Solución de alarmas y problemas comunes.",
      ],
      needTitle: "¿Necesita capacitación?",
      needBody: "Esta capacitación en bombas es completamente gratuita. No requiere seguro ni referido. Programe directamente y reciba apoyo práctico.",
      scheduleButton: "Programar capacitación",
    },
    "cgm": {
      heroTitle: "Capacitación en CGM y análisis de reportes",
      heroSubtitle: "Aproveche todo el potencial de su monitor continuo de glucosa. Le enseñamos a usarlo y ayudamos a usted y a su médico a interpretar los datos para optimizar su salud.",
      logoAlt: "Logotipo de {{name}}",
      officialWebsite: "Sitio web oficial",
      lingoFallbackDesc: "Apoyo para usuarios de Abbott Lingo que desean entender patrones de glucosa y respuestas del estilo de vida.",
      devices: [
        { name: "FreeStyle Libre", maker: "Abbott", logo: "cgm-logos/freestyle-libre-v2.png", desc: "Capacitación sobre colocación del sensor, uso del lector o teléfono inteligente e interpretación de flechas de tendencia.", sourceUrl: "https://www.freestyle.abbott/us-en/home.html" },
        { name: "Dexcom G7/G6", maker: "Dexcom", logo: "cgm-logos/dexcom-v2.png", desc: "Configuración de alertas y alarmas, compartir datos con familiares o la clínica, y apoyo con el proceso de solicitud.", sourceUrl: "https://www.dexcom.com/" },
        { name: "Stelo", maker: "Dexcom OTC", logo: "cgm-logos/stelo-v2.png", desc: "Orientación para pacientes con diabetes tipo 2 sobre cómo interpretar los datos del nuevo biosensor de venta libre.", sourceUrl: "https://www.stelo.com/" },
        { name: "Lingo", maker: "Abbott", logo: "cgm-logos/lingo-v2.png", desc: "Apoyo para usuarios de Abbott Lingo que desean entender patrones de glucosa y respuestas del estilo de vida.", sourceUrl: "https://www.hellolingo.com/" },
      ],
      features: {
        appSetup: "Configuración de la app",
        arrowTrends: "Flechas de tendencia",
        agpReports: "Reportes AGP",
        reportInterpretation: "Interpretación de reportes",
        timeInRange: "Tiempo en rango",
      },
      beyondTitle: "Más que solo números",
      beyondIntro: "Un CGM ofrece cientos de lecturas al día, pero ¿qué se hace con ellas?",
      beyondBody: "Analizamos sus informes de perfil ambulatorio de glucosa (AGP) para identificar patrones. Le enseñamos cómo distintos alimentos, el estrés y el ejercicio afectan a su cuerpo, ayudándole a maximizar su <strong>tiempo en rango</strong> (TIR).",
      scheduleButton: "Programar sesión de análisis",
    },
    "glp1Training": {
      badge: "Apoyo para medicamentos GLP-1 inyectables y orales",
      imageAlt: "Educadora en diabetes revisando capacitación de medicamento GLP-1 con un paciente",
      heroTitle: "Capacitación en medicamentos GLP-1",
      heroSubtitle: "Empezar medicamentos como semaglutida, tirzepatida, liraglutida u otras terapias basadas en GLP-1 puede generar preguntas prácticas. Enseñamos los pasos diarios, la planificación de efectos secundarios y los hábitos de seguimiento que hacen el tratamiento más fácil de sostener.",
      scheduleButton: "Programar capacitación GLP-1",
      trainingTitle: "Qué cubrimos",
      trainingIntro: "La capacitación es educativa y se coordina con las indicaciones del médico que receta.",
      topics: [
        { title: "Técnica de inyección", desc: "Cómo preparar la pluma, elegir y rotar sitios de inyección, almacenar el medicamento y desechar objetos punzantes de forma segura." },
        { title: "Rutina de medicación oral", desc: "Cómo crear una rutina constante para el horario del medicamento oral GLP-1, dosis olvidadas e instrucciones de farmacia." },
        { title: "Comida e hidratación", desc: "Estrategias prácticas de ritmo de comidas, proteína, líquidos y porciones durante cambios de apetito y aumentos de dosis." },
        { title: "Preparación para seguimiento", desc: "Qué registrar, cuándo contactar al médico que receta y cómo preparar preguntas antes de cambios de dosis." },
      ],
      sideEffectTitle: "Manejo de efectos secundarios",
      sideEffectIntro: "Los efectos secundarios comunes de GLP-1 suelen ser gastrointestinales. Ayudamos a planificar formas realistas de manejar síntomas e identificar cuándo se necesita seguimiento médico.",
      sideEffects: [
        "Náusea, sensación de llenura, cambios de apetito y tolerancia a comidas",
        "Vómitos, diarrea, estreñimiento, gases o molestia abdominal",
        "Riesgo de glucosa baja cuando GLP-1 se usa con insulina o sulfonilureas",
        "Señales de alerta que deben escalarse al equipo médico que receta",
      ],
    },
    "providers": {
      badge: "Programa de educación en diabetes acreditado por ADCES",
      heroLine1: "Colaboramos con médicos",
      heroLine2: "para mejorar los resultados de los pacientes",
      heroSubtitle: "XT Diabetes Care funciona como una extensión de su práctica. Ofrecemos la educación intensiva y sistemática de automanejo de la diabetes que sus pacientes necesitan, completamente cubierta por el seguro.",
      values: [
        { title: "Ahorre tiempo clínico", desc: "Asumimos la carga de tiempo que implica una educación integral en diabetes, para que usted pueda enfocarse en el diagnóstico y el manejo de medicamentos." },
        { title: "Currículo estructurado", desc: "Los pacientes reciben educación sistemática sobre uso de medicamentos, alimentación, actividad física y habilidades de afrontamiento psicosocial." },
        { title: "Le mantenemos informado", desc: "Actuamos como apoyo para su práctica, le devolvemos informes completos y ayudamos a que los pacientes hagan seguimiento regular con usted para ajustes de medicamentos." },
      ],
      referTitle: "Cómo referir pacientes",
      referIntro: "Medicare y los seguros privados cubren nuestros programas, pero requieren un referido del médico tratante.",
      faxLine: "Envíe el formulario por fax al (888) 370-1981.",
      referralCandidates: [
        "Pacientes recién diagnosticados con diabetes.",
        "Pacientes que nunca han recibido capacitación sistemática de automanejo de la diabetes.",
        "Pacientes en transición a bombas de insulina o monitores continuos de glucosa (CGM).",
      ],
      downloadButton: "Descargar plantilla del formulario de referido",
      accreditedTitle: "Acreditado por ADCES",
      accreditedId: "ID# 1001155",
      accreditedBody: "Cumple con todos los estándares y requisitos aplicables de la Association of Diabetes Care & Education Specialists.",
      certificateAlt: "Certificado ADCES DEAP",
    }
  }
};
